### ISSUE TITLE
Error using docker-compose + carina

### ISSUE THREAD

**Issue by DanTheColoradan** [JrCs/docker-letsencrypt-nginx-proxy-companion#1]
I'm using [Carina](getcarina.com), which means I'm calling docker-compose remotely and I can't seem to get the companion to work. I'm getting errors similar to the following:

```
https_container | Error: can't get nginx-proxy container id !
https_container | Check that you use the --volumes-from option to mount volumes from the nginx-proxy.
https_container | Error response from daemon: no such id: a8a0fb896a6fc06c7315900011020d6b632b6779139f8a48f71fc8c941079910:rw
```

Any ideas? What's odd is that the hash value matches. So if I run docker ps, I see `a8a0fb896a6f`.

I'm going to try without docker-compose next. I'll keep you posted.

**Comment by DanTheColoradan** [comment]
Well, it appears to work when I use just the docker command :-/ Hmmm.

**Comment by anoopr** [comment]
@DanTheColoradan I'm having the exact same issue with docker-compose. Have you been able to resolve it?

**Comment by anoopr** [comment]
@DanTheColoradan @JrCs Tracked down the issue. This pull request fixes it!

**Comment by DanTheColoradan** [comment]
:clap: awesome.
