### ISSUE TITLE
How is the well-known file to be reached?

### ISSUE THREAD

**Issue by stevenroose** [JrCs/docker-letsencrypt-nginx-proxy-companion#10]
I have this setup: a container listening to 8000 that nginx-proxy should map on 80 and 443. Then I have another container for a websocket backend listening on another port that should be mapped with the same domain, but with `/websocket` path. They both use the same domain.

Apart from the problem of forwarding that path to a separate container using nginx-proxy which I don't know how to solve, Let's Encrypt doesn't work.

I get error messages that the ACME-challenge is not found on the domain. But, how is that file supposed to be in place? Does this companion automatically forward the well known uri to the file?

**Comment by JrCs** [comment]
Yes it automatically forward the well known uri to challenge files by modifying the vhost.d/default file or the vhost.d/yourdomain file if it exists

**Comment by stevenroose** [comment]
Thanks. I think that part works, just not the part forwarding, but that's not an issue here.
