### ISSUE TITLE
Certificate Renewal & Dependant Containers

### ISSUE THREAD

**Issue by danbo** [JrCs/docker-letsencrypt-nginx-proxy-companion#100]
> Automatic certificate renewal
> 
> Every hour (3600 seconds) the certificates are checked and every certificate that will expire in the next 30 days (90 days / 3) are renewed.

The readme does not clearly explain what actually happens upon renewal. By investigating the source, it looks like nginx is restarted.

What about proxied containers that depend on these certificates? ie

```
$ docker run -d \
    --name example-app \
    -e "VIRTUAL_HOST=example.com,www.example.com,mail.example.com" \
    -e "LETSENCRYPT_HOST=example.com,www.example.com,mail.example.com" \
    -e "LETSENCRYPT_EMAIL=foo@bar.com" \
    tutum/apache-php
```

**Will example-app also be automatically restarted to work with the updated certificates?**

Apologies if I missed something.

**Comment by JrCs** [comment]
The nginx proxy is not restart but reload.
Only the nginx proxy have the certificates so no other containers need to be restart/reload.

**Comment by danbo** [comment]
So I don't need to run proxies containers as https and I don't need to give them the letsencrypt certs?

**Comment by JrCs** [comment]
Exactly
