### ISSUE TITLE
Potential race condition when using with multiple servers and L7 LB or DNS A record round-robin

### ISSUE THREAD

**Issue by niieani** [JrCs/docker-letsencrypt-nginx-proxy-companion#101]
I'd like to use this on multiple servers at once with both the certificate and `.well-known` acme volumes shared across all the servers. This can be accomplished either by multiple A records of one domain pointing to multiple servers, or with load balancing, such as the one offered natively by docker 1.12.

The problem might arise (I think) if all the servers start the proxy-companion container and notice missing/invalid certs **at the same time**, upon which they'll **all** request a new certificate. If you have 50 servers, that could potentially be a problem, but even with just 2 you'll use the ACME quotas much faster than intended.

A potential solution would be to use some sort of a mutex, e.g. for the first server that notices the missing certificates to create a lock file/dir alongside certs, which would be removed once the new certificate has been installed. Other servers, seeing the lock file present, should wait for it to be removed and reload their nginx instance upon its removal.

The only problem with this solution I see is that if a server/container crashes for some reason **during** the certificate renewal, the lock would became stale and the certificates would never renew again. 

This could be solved by adding a maximum time limit for the lock file - lets say - if the lock is older than 5 minutes (+ RANDOM 1-5 min to prevent further race conditions), the server could start the certificate renewal/generation despite the lock file presence, touching the file in the process to update its datetime.

Thoughts?

**Comment by niieani** [comment]
Actually, a simpler solution came to my mind. Have a designated, single container on a single server for certificate renewal, set by an ENV variable set to let `proxy-companion` know that. Other servers would only need to reload their nginx config in case the certificates are renewed.

**Comment by JrCs** [comment]
The best is to only start one nginx-proxy. The problem was to reload ALL the nginx-proxy.

**Comment by niieani** [comment]
Yeah (you mean only start one proxy-companion, right?). Can we maybe add an ENV like `RELOAD_ONLY` which, when set, would run the companion, but instead of running renewals, only watch for changing certs and reloading the nginx-proxy?

**Comment by JrCs** [comment]
Updating certs is managed by simp_le, so we can "watch only" for new certificates.
Perhaps the companion proxy is not the right solution for you. Look at [traefik](https://traefik.io) perhaps it's better in your case.

**Comment by niieani** [comment]
Actually, I'm coming from traefik, hoping this help me, as it as the exact same issue: https://github.com/containous/traefik/issues/348. I'll probably have to come up with my own solution.
