### ISSUE TITLE
Not generating certs

### ISSUE THREAD

**Issue by omata-metamax** [JrCs/docker-letsencrypt-nginx-proxy-companion#105]
Hello,

Recently I configured your awesome solution for secure nginx proxy and all worked fine with the test/staging letsencrypt API server setting the **ACME_CA_URI** variable, but when I changed to letsencrypt production API server, *meaning remove* ***ACME_CA_URI*** *variable*, all went wrong no certs were created. Trying to fix this I removed my app containers and only configured the unsecure domain with the **VIRTUAL_HOST** variable, removing the other two required to get *HTTPS* working, but the *SSL* configurations was kept at `default.conf` file, dockergen was generating the secure configuration even when the container was created without **LETSENCRYPT_HOST** and **LETSENCRYPT_EMAIL**. As I'm running this on 3 separate containers as is recommended, I reviewed the logs from the letsencrypt companion container and it returns the following message:

```
2016-09-13 23:20:45,338:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-09-13 23:20:45,528:ERROR:simp_le:1271: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/r-VyI-f9FwWGe3qQAXcrWyyOqO4DFbbgnWOuA-c2fc0
```

I noticed that it is trying to validate the **example.com** domain, but I don't know why; I don't have any **example.com** domain configured in any of my app containers.

So, my last try was removing everything, *meaning 3 proxy-nginx containers including letsencrypt companion*, and re instance them again, prior removing the files generated in the exposed volumes; after that the error is still happening. So I don't know what to do with this.

**BTW: My DNS are set right, the thing did the work with the staging API with the same domain names without issues.**

**Comment by ryneeverett** [comment]
> I noticed that it is trying to validate the example.com domain, but I don't know why; I don't have any example.com domain configured in any of my app containers.

I remember seeing this and being confused as well. I'm pretty sure the error message is giving you a hardcoded *example* of the url it needs to access (and totally failing to make that clear).

**Comment by omata-metamax** [comment]
I solved the issue,

It's look like is mandatory to set `LETSENCRYPT_TEST=false` to get a valid cert. Now the cert was generated and configured.

Just remember to pass **LETSENCRYPT_TEST** as *false* if you want valid certs and no issue in the **nginx-letsencrypt** container log.

Regards,

**Comment by omata-metamax** [comment]
I talked too fast,

I added a second app and it failed again in the same way. I don't understand.

**Comment by omata-metamax** [comment]
Finally,

It's looks like the issue is related to a kind of rate limiting by the **Letsencrypt** API; but there is not enough logging at the **nginx-letsencrypt** container to do a right debug. After a couple of hours I was able to generate the cert for the second app exposed using **nginx-proxy** and **Letsencrypt**.

Best regards,
