### ISSUE TITLE
Cannot establish https connection (nextcloud+nginx+reverse-proxy+letsencrypt)

### ISSUE THREAD

**Issue by mareeba** [JrCs/docker-letsencrypt-nginx-proxy-companion#106]
Have recently been trying to get Nextcloud setup following this:
# https://help.nextcloud.com/t/nextcloud-nginx-reverse-proxy-letsencrypt-in-docker-containers/1687

After discovering there are some issues with the nginx template(s) I have managed to get it all working however I can only access the nextcloud docker container via http and not https (which is obviously what we need!)

Some related issues (esp with the template file etc) are:
# https://github.com/fatk/docker-letsencrypt-nginx-proxy-companion-examples/issues/10

and
# https://github.com/fatk/docker-letsencrypt-nginx-proxy-companion-examples/pull/6

Anyone got any suggestions as to how I might get the https connection to work?

**Comment by buchdag** [comment]
Closed due to old age.
