### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by ippa** [JrCs/docker-letsencrypt-nginx-proxy-companion#11]
Since HTTP/2 builds on https could this proxy-companion be the right place to add optional nginx-http2-configuration? 

Since 1.9.5 nginx supports HTTP/2. The extra conf once https is in place seems minimal, https://www.nginx.com/blog/nginx-1-9-5/

maybe enabled with something like -e ENABLE_HTTP2

**Comment by JrCs** [comment]
@ippa it's not the right place here.
Configuration of the nginx-proxy must be done by the nginx-proxy container.
My container is only used to create Let's Encrypt certificates, not to proxy web request.
