### ISSUE TITLE
Https redirection can't be disabled

### ISSUE THREAD

**Issue by mrgnou** [JrCs/docker-letsencrypt-nginx-proxy-companion#110]
It seems there's no way to kill automated https redirection, which becomes an issue when you have some unregistered subdomains.

I'd prefer dealing with that manually or with my DNS provider, adding an optional env var to disable automatic redirection would be sweet.

**Comment by JrCs** [comment]
It's not managed by the letsencrypt container but by [nginx-proxy](https://github.com/jwilder/nginx-proxy).
Post your issue over there.

**Comment by mrgnou** [comment]
And they do seem to provide an HTTPS_METHOD=noredirect env var.

My bad, thanks.
