### ISSUE TITLE
works with docker-compose v1, does not work with docker-compose v2

### ISSUE THREAD

**Issue by danhimalplanet** [JrCs/docker-letsencrypt-nginx-proxy-companion#119]
using docker-compose and a docker-compose.yml in format v1, I can bring up several containers, register with letsencrypt, and properly proxy traffic to them via ssl.

using docker-compose and a docker-compose.yml in format v2, I end up having an empty block default.conf for nginx in the nginx container for the 'p.amazing.website' backend 

I am attaching my docker-compose.yml v1, my docker-compose.yml v2, and the nginx default.conf that gets generated when I use docker-compose yml format v2

in docker-compose.yml v2, you can see how I tried taking out "-only-exposed" from docker-gen, an older version of the docker-gen container and letsencrypt-nginx-proxy-companion, setting 'expose' and VIRTUAL_PORT in the p.amazing.website service

[docker-compose.yml.v1.txt](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/files/567233/docker-compose.yml.v1.txt)
[docker-compose.yml.v2.txt](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/files/567234/docker-compose.yml.v2.txt)
[default.conf.with_v2.txt](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/files/567246/default.conf.with_v2.txt)

**Comment by JrCs** [comment]
Your issue is not related to the docker-letsencrypt-nginx-proxy-companion container..
Please post your issue to [docker-letsencrypt-nginx-proxy-companion-examples](https://github.com/fatk/docker-letsencrypt-nginx-proxy-companion-examples/issues).

**Comment by danhimalplanet** [comment]
@JrCs the issues filed against https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/ repo are filled with people having the same problem as me.

Lot of people propose various solutions.

I don't see a clear solution for using docker-compose version 2 files.

Can you point me to what everyone should be using?

Thanks.

**Comment by danhimalplanet** [comment]
so I was running docker-compose version 1.6.0, build d99cad6

i upgraded to docker-compose version 1.8.1

using docker-letsencrypt-nginx-proxy-companion with docker-compose.yml v2 works now
