### ISSUE TITLE
Usage with separate nginx and docker-gen container

### ISSUE THREAD

**Issue by konstantinj** [JrCs/docker-letsencrypt-nginx-proxy-companion#12]
Hi,

thanks for this awesome image - exactly what I was looking for. Unfortunately it's not working with my configuration. I'm using docker-compose and I have a separate nginx container and docker-gen in its own container so I can modify the nginx config template.

I'm getting this error on start:
> ,sh: 1: /usr/local/bin/docker-gen: not found

How is this image supposed to work?

**Comment by JrCs** [comment]
My container call the nginx proxy container to recreate the nginx configuration with docker-gen.
Why don't you use the original nginx-proxy container with docker-gen in it ?
If you need to change the template that is used to create the nginx configuration you can mount bind the nginx.tpl with your configuration.

**Comment by konstantinj** [comment]
The default nginx-proxy container is using the /app/nginx.tmpl file which I can't overwrite with a mount. Also by using nginx separately I can use a newer version and the docker socket won't be exposed publicly.

**Comment by bobmaerten** [comment]
Exactly my setup, @konstantinj. I'll try installing/using the @JrCs image to get it running, and I'll report back here then.

**Comment by JrCs** [comment]
To use my container we need to know the container id of the docker-gen container.
@konstantinj is your docker-gen container do an nginx reload ? if yes how ?

**Comment by konstantinj** [comment]
In the readme from https://github.com/jwilder/nginx-proxy it says that the nginx container must be named "nginx". So I guess that's how docker-gen can reload nginx. So it should work the same with your container I guess when the container name is hard "docker-gen".

**Comment by bobmaerten** [comment]
Well, no luck with containerized `docker-gen`, so I switch back on default nginx-proxy for now.

**Comment by JrCs** [comment]
@konstantinj no the docker-gen command of the nginx-proxy call directly the nginx reload command (they are in the same container)

**Comment by konstantinj** [comment]
Yes, when using nginx-proxy image. But in my case, when using docker-gen image and nginx image separately, docker-gen is reloading nginx in the other container.

**Comment by JrCs** [comment]
How the docker-gen image reload the nginx in the other container ?

**Comment by bobmaerten** [comment]
@JrCs `docker-gen` tool has a `-notify-sighup <container_name>` flag to do some sort of `kill -HUP` to the container.

**Comment by falcon15500** [comment]
I have this working (for the most part) with minimal code changes, with official nginx image and docker-gen 0.5.0.  Everything is working as expected getting certs etc.  The only bump I currently have is that docker-gen command run in the docker-gen container doesn't seem to exit properly (or in fact, at all).

So while the LE companion container does it's work correctly and fires off the docker-gen command followed by the nginx container HUP, the docker-gen command never exits so the LE container sits there doing nothing, waiting for it. :(  I have raised an issue with docker-gen and will see what is said.

**Comment by JrCs** [comment]
A PR #20 is open to fix this issue.

**Comment by konstantinj** [comment]
Awesome!
