### ISSUE TITLE
One container - multiple domains

### ISSUE THREAD

**Issue by andrewheald** [JrCs/docker-letsencrypt-nginx-proxy-companion#124]
I have a Wordpress container working with this companion, at the moment LETSENCRYPT_HOST & VIRTUAL_HOST are set like this: "example-domain-a.co.uk,www.example-domain-a.co.uk". I'd like to add another domain which my client owns, but I suspect that I can't set these variables to "example-domain-a.co.uk,www.example-domain-a.co.uk,example-domain-b.co.uk,www.example-domain-b.co.uk". I'll try this on a test environment in the near future, but does anyone know what the form is on this?
Thanks,
Andrew.

**Comment by mickaelperrin** [comment]
See the PR #140 it was created for this purpose.

**Comment by andrewheald** [comment]
Many thanks, Mickael. I'll try it out in the coming days and look forward to your change going mainstream.
