### ISSUE TITLE
Run new container got error DeserializationError: Deserialization error: Wrong directory fields

### ISSUE THREAD

**Issue by anhtranqs3** [JrCs/docker-letsencrypt-nginx-proxy-companion#131]
Previously, I was able to run new container and got ssl without any error. But today, I can't get ssl for new container anymore.
Below is my docker-letsencrypt-nginx-proxy-companion log's content.

```
B2016-12-09T07:02:36.260036476Z Traceback (most recent call last):
d2016-12-09T07:02:36.260174053Z   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1401, in main
I2016-12-09T07:02:36.261845458Z     return main_with_exceptions(cli_args)
t2016-12-09T07:02:36.261936458Z   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1386, in main_with_exceptions
I2016-12-09T07:02:36.262000322Z     persist_new_data(args, existing_data)
p2016-12-09T07:02:36.262058279Z   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1282, in persist_new_data
_2016-12-09T07:02:36.262123560Z     client = registered_client(args, existing_data.account_key)
q2016-12-09T07:02:36.262207829Z   File "build/bdist.linux-x86_64/egg/simp_le.py", line 1224, in registered_client
h2016-12-09T07:02:36.262278038Z     client = acme_client.Client(directory=args.server, key=key, net=net)
j2016-12-09T07:02:36.262329582Z   File "build/bdist.linux-x86_64/egg/acme/client.py", line 63, in __init__
C2016-12-09T07:02:36.263517838Z     self.net.get(directory).json())
n2016-12-09T07:02:36.263642080Z   File "build/bdist.linux-x86_64/egg/acme/messages.py", line 169, in from_json
O2016-12-09T07:02:36.264589912Z     raise jose.DeserializationError(str(error))
c2016-12-09T07:02:36.264714660Z DeserializationError: Deserialization error: Wrong directory fields
 2016-12-09T07:02:36.264798549Z 
P2016-12-09T07:02:36.264810443Z Unhandled error has happened, traceback is above
```

I connect to nginx proxy container and saw only empty folder created for new domain inside certs folder. Nothing in there. That folder is also not removable so I cannot remove it and try again.

**Comment by mlaitinen** [comment]
See #130

**Comment by jamrizzi** [comment]
I'm getting the same error.

**Comment by danhimalplanet** [comment]
The letsencrypt api changed slightly a week ago.  Someone has published a container image that successfully uses the new api.

So if you're using this example from JrCs docs:
>>Then start this container (NGINX_DOCKER_GEN_CONTAINER variable must contain the 
>>docker-gen container name or id):
>>$ docker run -d \
>>    --name nginx-letsencrypt \
>>    -e "NGINX_DOCKER_GEN_CONTAINER=nginx-gen" \
>>    --volumes-from nginx \
>>    -v /path/to/certs:/etc/nginx/certs:rw \
>>    -v /var/run/docker.sock:/var/run/docker.sock:ro \
>>    jrcs/letsencrypt-nginx-proxy-companion

replace "jrcs/letsencrypt-nginx-proxy-companion" with "alastaircoote/docker-letsencrypt-nginx-proxy-companion/"
