### ISSUE TITLE
docker: Error response from daemon: Mounts denied

### ISSUE THREAD

**Issue by bigUNO** [JrCs/docker-letsencrypt-nginx-proxy-companion#137]
I can't get the first step to finish with out error in OSX.

```
-> % docker run -d -p 80:80 -p 443:443 \
    --name nginx \
    -v /etc/nginx/conf.d  \
    -v /etc/nginx/vhost.d \
    -v /usr/share/nginx/html \
    -v /path/to/certs:/etc/nginx/certs:ro \
    nginx
Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx
386a066cd84a: Already exists
386dc9762af9: Already exists
d685e39ac8a4: Already exists
Digest: sha256:3861a20a81e4ba699859fe0724dc6afb2ce82d21cd1ddc27fff6ec76e4c2824e
Status: Downloaded newer image for nginx:latest
bdc47a8fce8bcf61f36db8a103557d436b5466ac899051764be4d7b493e52a3d
docker: Error response from daemon: Mounts denied:
The path /path/to/certs
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

!'m new to both docker and nginx. I might not be fully understanding what's going on in this command, but `-v /path/to/certs:/etc/nginx/certs:ro` seems wrong to me. Why do I want to map my local directory (which doesn't exist) to this docker image? I thought I needed to map / bind the containers together via that mount. I'll try to add more info as I work this issue.

**Comment by ryneeverett** [comment]
> Why do I want to map my local directory (which doesn't exist) to this docker image?

The idea is that you probably want your certificates to be persistent beyond the lifespan of your container. The way the README suggests doing this is to mount a directory on the host, which indeed needs to exist already. To me it seems fairly obvious that `/path/to/certs` could be any path of your choosing, but perhaps that should be made explicit. Another way would be to mount a named volume.

**Comment by bigUNO** [comment]
Ahhh, that's make sense. Thanks for the response!
