### ISSUE TITLE
Nginx Container Loads Content over HTTP not HTTPS

### ISSUE THREAD

**Issue by Nurian** [JrCs/docker-letsencrypt-nginx-proxy-companion#15]
Your docker-letsencrypt-nginx-proxy-companion works perfect with apache containers.
https://hub.docker.com/_/wordpress/
https://hub.docker.com/r/_/owncloud/

But I have problems to get a working nginx container like:
https://hub.docker.com/r/tlongren/docker-wordpress-nginx-ssh/
https://hub.docker.com/r/oskarhane/docker-wordpress-nginx-ssh/

I Already tried ~ 5-10 other nginx wordpress containers and also build my own container 
with diffrent "etc/nginx/nginx.conf" and "/etc/nginx/sites-available/default" files with no luck.
A HTTPS force always trunsaltes in an 502 Error, so that also does not help.

Here is an example how a new nginx container is looking like:
https://freeunitygames.org

Thank you for your efforts :)

**Comment by JrCs** [comment]
Hi,
sorry but it's not the right place to speak about nginx configuration.
My container only create letsencrypt certificates.
I didin't know about to help you about your nginx problem.
Try to report issues to author of docker-wordpress-nginx-ssh.
