### ISSUE TITLE
Renewing certificates for non-dockable services

### ISSUE THREAD

**Issue by TroelsL** [JrCs/docker-letsencrypt-nginx-proxy-companion#157]
I'm pretty smitten with the ease of using nginx-proxy and this companion.

But I have one stubborn service that I can't put in docker (.NET Core project which relies on something that is only implemented on Windows).

Is there any way I can still use this container to renew certificates for it?

In other words, can I edit add something to the configuration that would setup nginx to forward the subdomain tests to the same mechanisms as this image uses, but all other calls to my API on a different IP/port? And that would cause this container to still renew it?

**Comment by JrCs** [comment]
You must change the nginx proxy configuration manually so your api requests will be redirect to your service.

**Comment by TroelsL** [comment]
Not sure I follow you.

I can create the nginx config manually, but then (I assume) I wouldn't get that lovely automatic certificate renewal seeing as I don't have a container to add environment variables to.

What I hope was that it would be possible to add a file somewhere with contents:

    sub1.mydomain.com
    sub2.mydomain.com

And then the companion would automatically create letsencrypt certificates for the two subdomains above and renew them the same way as all the other certificates.

Only without having an actual container running for each of these.

I could then manually create the nginx config to point to these certificates.

**Comment by JrCs** [comment]
See how to add the configuration for your domains in nginx-proxy: https://github.com/jwilder/nginx-proxy#per-virtual_host so
For the companion, the best is perhaps to create a dummy container with the LETSENCRYPT_ variables.
You can also look at another solution: https://traefik.io

**Comment by TroelsL** [comment]
Ah. So a dummy container and then manually override the proxy setting to forward to another server instead?

I guess that is certainly a workable solution, thanks.
