### ISSUE TITLE
Nginx module that implements ACME

### ISSUE THREAD

**Issue by denji** [JrCs/docker-letsencrypt-nginx-proxy-companion#158]
* https://github.com/mozilla/mwos-letsencrypt-2015 (`libcurl-dev`, `curl-devel`)
* https://github.com/kristapsdz/acme-client ( https://kristaps.bsd.lv/acme-client )

**Comment by denji** [comment]
* https://github.com/grahamedgecombe/nginx-ct

**Comment by JrCs** [comment]
Thanks for the informations.
