### ISSUE TITLE
local testing

### ISSUE THREAD

**Issue by hilyin** [JrCs/docker-letsencrypt-nginx-proxy-companion#160]
Heya,

I am attempting to setup this with my existing nginx-proxy setup with several apache and nginx containers. But I am having a little trouble working locally (when letsencrypt fails to create a cert because the ip for the domain i am testing on is set on my /etc/hosts and not actually coming from the ip that links to the domain). 

Is there any setting that would allow me to work on this setup locally without actually having letsencrypt being able to successfully create a cert?

Here is my error log below of what is happening:

`letsencrypt-nginx-proxy-companion    | 2017/02/01 06:02:37 Generated '/app/letsencrypt_service_data' from 3 containers
letsencrypt-nginx-proxy-companion    | 2017/02/01 06:02:37 Running '/app/update_certs'
letsencrypt-nginx-proxy-companion    | 2017/02/01 06:02:37 Watching docker events
letsencrypt-nginx-proxy-companion    | Reloading nginx proxy (using separate container nginx-gen)...
letsencrypt-nginx-proxy-companion    | Creating/renewal forum.roiguild.org certificates... (forum.roiguild.org)
letsencrypt-nginx-proxy-companion    | 2017-02-01 06:02:37,570:INFO:simp_le:1211: Generating new account key
nginx-gen exited with code 2
letsencrypt-nginx-proxy-companion    | 2017/02/01 06:02:37 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
letsencrypt-nginx-proxy-companion    | 2017/02/01 06:02:37 Received event die for container d4d6c37b5203
letsencrypt-nginx-proxy-companion    | 2017-02-01 06:02:38,512:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
letsencrypt-nginx-proxy-companion    | 2017-02-01 06:02:40,029:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): letsencrypt.org
letsencrypt-nginx-proxy-companion    | 2017-02-01 06:02:47,925:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): forum.roiguild.org
letsencrypt-nginx-proxy-companion    | 2017-02-01 06:02:48,049:ERROR:acme.challenges:256: Unable to reach http://forum.roiguild.org/.well-known/acme-challenge/RgnTALbufSbHB1IwXWtgHno8XHroS2huSl783vwKbyU: HTTPConnectionPool(host='forum.roiguild.org', port=80): Max retries exceeded with url: /.well-known/acme-challenge/RgnTALbufSbHB1IwXWtgHno8XHroS2huSl783vwKbyU (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f0b1a636c90>: Failed to establish a new connection: [Errno 111] Connection refused',))
letsencrypt-nginx-proxy-companion    | 2017-02-01 06:02:48,049:WARNING:simp_le:1303: forum.roiguild.org was not successfully self-verified. CA is likely to fail as well!
letsencrypt-nginx-proxy-companion    | 2017-02-01 06:02:48,246:INFO:simp_le:1313: Generating new certificate private key
letsencrypt-nginx-proxy-companion    | 2017-02-01 06:02:50,038:ERROR:simp_le:1271: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/-APYrU9IDbLnuSoeqK2GWYkPmT2H8CoK_j16xEwqWdo
letsencrypt-nginx-proxy-companion    | Challenge validation has failed, see error log.
letsencrypt-nginx-proxy-companion    |
letsencrypt-nginx-proxy-companion    | Debugging tips: -v improves output verbosity. Help is available under --help.
letsencrypt-nginx-proxy-companion    | Sleep for 3600s
letsencrypt-nginx-proxy-companion    | 2017/02/01 06:02:52 Debounce minTimer fired
letsencrypt-nginx-proxy-companion    | 2017/02/01 06:02:53 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'`

**Comment by hilyin** [comment]
I guess my goal is that I want to be able to attempt a successful use of this setup locally before deploying.

**Comment by JrCs** [comment]
No you must use the proxy that is links to the domain
