### ISSUE TITLE
Expiration E-Mail form Letsencrypt despite succesfull renewal

### ISSUE THREAD

**Issue by de-robat** [JrCs/docker-letsencrypt-nginx-proxy-companion#163]
First of all: big thanks for this image!

As stated in the title everything works, but i've got an expiration mail from letsencrypt none the less. So i tried figuring out how the renewal happend and stumbled on the "simp_le" client. It states that the call, this containers script invokes on renewal attempts, either creates a new cert if none is existing already or renews the existing one.

So im wondering if this behaviour of getting an expiration notifcation is something all of you witness or if i've setup the companion poorly and missed something.

**Comment by cpu** [comment]
Hi @de-robat, I don't have direct experience with this project, but may be able to help.

> So im wondering if this behaviour of getting an expiration notifcation is something all of you witness or if i've setup the companion poorly and missed something.

In our [expiration email documentation](https://letsencrypt.org/docs/expiration-emails/) we mention what Let's Encrypt's warning system considers a renewal:

>  We consider a certificate to be renewed if there is a newer certificate with the exact same set of names, regardless of which account created it. If you’ve issued a new certificate that adds or removes a name relative to your old certificate, you will get expiration email about your old certificate. If you check the certificate currently running on your website, and it shows the correct date, no further action is needed.

Can you share the set of domain names you received an expiration warning for, and the set of domain names on the current unexpired certificate you believe should have prevented the warning?

**Comment by JrCs** [comment]
@cpu thx to have replied to @de-robat

**Comment by de-robat** [comment]
Thank you for taking the time to point me to the expiration email document @cpu . I screened all the expiration Mails i've got once again and i did not get one which stated the same exact dns names as the once beeing named in the currently active certificate. So i guess you are spot on and that's the reason why i got the expiration mail. 

So for now there is nothing left to do but wait for the next expiration period to expire. Thanks again!

**Comment by cpu** [comment]
@de-robat Great! Glad to hear you were able to get to the bottom of it. Take care.
