### ISSUE TITLE
Question: How to put all subdomains under 1 SAN cert?

### ISSUE THREAD

**Issue by falcon15500** [JrCs/docker-letsencrypt-nginx-proxy-companion#17]
As the title suggests, I have multiple subdomains such as:
aaa.domain.net
bbb.domain.net
ccc.domain.net etc.

Instead of generating a separate certificate for each one (and hitting the cap), how can I generate a SAN certificate that encompasses all of these and is used for them all?

**Comment by JrCs** [comment]
Put all your domains in the LETSENCRYPT_HOST and it will create a multidomain certificate

**Comment by falcon15500** [comment]
Sorry... I perhaps wasn't very clear.
Each of those subdomains runs in it's own container.  So there are as many containers running as there are subdomains.
Do I use the same LETSENCRYPT_HOST value for all containers?  Containing a list of all the domains?

**Comment by JrCs** [comment]
If each container have their own subdomain, only define the subdomain in the LETSENCRYPT_HOST per container. So each container will have it's own certificate dedicated for the subdomain.
If you don't want to hit the cap use the same LETENCRYPT_HOST value (with all subdomain) for all containers.

**Comment by falcon15500** [comment]
Just an FYI...  I did the above (for a SAN certificate), however in my situation I only needed to put all the subdomains under LETSENCRYPT_HOST in 1 container.  It works fine.  If I put the LETSENCRYPT_HOST env variable on all containers it just makes the process repeat as many times as you have containers (with no real difference in the outcome).
