### ISSUE TITLE
Compatibility with docker-compose v3

### ISSUE THREAD

**Issue by joantune** [JrCs/docker-letsencrypt-nginx-proxy-companion#170]
Hi!

First of all, kudos for the great work and container.

Currently, this container is not supported by docker-compose v3, because this new compose version has no `volumes_from` which is needed at:
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/app/entrypoint.sh#L28

Any ideas on how to get the container's id any other way? I'm happy to do a PR if I have some pointers

I also asked that on an issue on docker-compose just now:

https://github.com/docker/compose/issues/4379#issuecomment-279499040

I don't know the rational for taking out a feature from compose, but I hope it's a good one on behalf of them, otherwise it kinda disencourages one to use it in the first place (IMO the docker engine and docker compose should have the same options possible)

For everyone else stuck on this, for now, just use v2.

**Comment by joantune** [comment]
It seems that this the way to go:

https://github.com/docker/compose/issues/4379#issuecomment-279567234

I can try to use the volumes from, and if it fails, use the label. Should I proceed with a PR?

**Comment by mikumi** [comment]
@joantune I am curious how you solved this, I haven't figured it out yet :)

**Comment by JrCs** [comment]
@joantune yes you can proceed with a PR to use label instead of volumes_from to get the container id.

**Comment by netdesk** [comment]
I did a setup using named volumes, without volumes_from. It works, don't know how as the entrypoint.sh of the letsencrypt container clearly uses VolumeFrom.

Here is the setup as a gist: https://gist.github.com/netdesk/c1db2985b542f9916995139318e5a7ce

The gist also includes a docker-compose setup for gitlab. One could include this in the nginx-proxy setup, but I wanted to separate concerns and the gitlab setup basically has nothing to do with the nginx-proxy thing.
