### ISSUE TITLE
Cert Generation and Nginx Proxy Reload Forces HTTPS | Challenge Request HTTP Only

### ISSUE THREAD

**Issue by ghost** [JrCs/docker-letsencrypt-nginx-proxy-companion#178]
### Description
When running docker-compose and initializing the containers in the following order:
1. Nginx Proxy
2. Lets Encrypt Nginx Proxy Companion
3. Backends

The certificates fail to be verified by lets encrypt due to their challenge requests timing out.

### Analysis

After the lets encrypt proxy companion container generates the cert, it forces a restart on the nginx proxy container. This causes the nginx proxy to rebuild its configuration and only  allow HTTPS connections. Unfortunately, the following lets encrypt challenge request is HTTP only, so an HTTP Timeout is received.

### Work Around

I have gotten around this issue by going through the initialization steps listed above with each backend service having the `HTTPS_METHOD=noredirect` environment variable. This allows the challenge request to go through. However, redirecting HTTP to HTTPS is a good thing, so I then remove these environment variables and restart the containers.

### Thoughts on Fix

Is there a way to place the generated certificate in a place that the Nginx Proxy will not see it until the challenge has been accepted by lets enrypt? At that point, the certificate could be put in the proper location so Nginx Proxy will begin to force HTTPS.

**Comment by lounagen** [comment]
Just had such a problem on renewal. Not sure if i had the same issue than yours, but it looks like:
## Analysis
The HTTP to HTTPS redirection on renewal is not a big deal as LE follows the 'HTTP 301 redirects'.
The problem i encountered is that the 'location /.well-known/acme-challenge' nginx directive was overridden by the 'location /' in the 'HTTPS template' from nginx.tmpl file. and the 'location /' redirects to my webapp container instead of the 'letsencrypt challenges volume'.

## Work Around
I resolved it by declaring the well-known acme location as a prefix string, to avoid continuing to evaluate other nginx locations.

## Fix
Just put my 2 cents into the PR #192 if it could be of any use for someone.

**Comment by ambroisemaupate** [comment]
I get this issue too. 

```
CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/xxxxxxxx, https://acme-v01.api.letsencrypt.org/acme/authz/xxxxxxxxx
Challenge validation has failed, see error log.
```

When I follow links manually in browser, redirections to https happen and do not prevent from download the challenge file.

It’s seems that LE can’t follow 301 redirects.

```json
{
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:connection",
        "detail": "Fetching http://www.xxxxx.fr/.well-known/acme-challenge/xxxxxx: Timeout",
        "status": 400
      },
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/xxxxxxx",
      "token": "xxxxxxx",
      "keyAuthorization": "xxxxxxx",
      "validationRecord": [
        {
          "url": "http://www.xxxxxx.fr/.well-known/acme-challenge/xxxxxxxx",
          "hostname": "www.xxxxxx.fr",
          "port": "80",
          "addressesResolved": [
            "xxxxxxxxx",
            "xxxxxxxxx"
          ],
          "addressUsed": "xxxxxxxx",
          "addressesTried": [
            
          ]
        }
      ]
    }
}
```

**Comment by buchdag** [comment]
LE does follow 301 redirects.

#192 was merged, then reverted as it proved problematic and things seems to have been working fine since, I don't think this issue is relevant anymore so I'm going to close it.
