### ISSUE TITLE
Requests to validate LE certificate are getting redirect 302 responses

### ISSUE THREAD

**Issue by cannfoddr** [JrCs/docker-letsencrypt-nginx-proxy-companion#180]
I am trying to run multiple containers via docker-compose V2.  I have read everything I can find on this and have an "almost" working setup.

I am using the latest nginx.tmp which seems to be https ready.  Everything works well for non https:  I then spin up another container requesting a cert for a.b.com on port 9999.  I can see docker-gem doing its thing and then LE companion springs into life and builds a cert request:

```
letsencrypt-nginx-proxy-companion    | 2017-03-03 12:51:21,600:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): a.b.com
nginx                                | a.b.com 172.18.0.1 - - [03/Mar/2017:12:51:21 +0000] "GET /.well-known/acme-challenge/UiZSeoE1y-j4TIeFr6AtOrkZeZoSsQBASXaLOkwqQg8 HTTP/1.1" 302 0 "-" "python-requests/2.8.1"
nginx                                | a.b.com 172.18.0.1 - - [03/Mar/2017:12:51:21 +0000] "GET / HTTP/1.1" 200 3278 "-" "python-requests/2.8.1"
letsencrypt-nginx-proxy-companion    | 2017-03-03 12:51:21,613:WARNING:simp_le:1303: couchpotato.merwood.com was not successfully self-verified. CA is likely to fail as well!
letsencrypt-nginx-proxy-companion    | 2017-03-03
```

What I can see is happening is that all requests are being redirected to the child site even those for .well-known

I have a conf.d entry looks like this:

```
# a.b.com
upstream a.b..com {
                ## Can be connect with "nginx-proxy" network
            # media_abcom_1
            server 172.18.0.6:5050;
}
server {
    server_name a.b.com;
    listen 80 ;
    access_log /var/log/nginx/access.log vhost;
    include /etc/nginx/vhost.d/default;
    location / {
        proxy_pass http://a.b.com;
    }
}
```

and vhost.d:

```
## Start of configuration add by letsencrypt container
location /.well-known/acme-challenge/ {
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
## End of configuration add by letsencrypt container
```

My read on this is that vhost.d is supposed to act as a global override intercepting every request for .well-known/acme-challenge but it is not.

I read an issue post elsewhere (so many I forget actually where) that suggested adding the following to config.d/default.conf:

```
location /.well-known/acme-challenge {
            root /usr/share/nginx/html;
            break;
    }
```

I'm quite confused about why the vhost.d is not working.

**Comment by buchdag** [comment]
Being more than two years old, I don't think this is still relevant so I'm closing the issue, feel free to re-open if it still is.
