### ISSUE TITLE
Certification error if the proxied service uses port 80

### ISSUE THREAD

**Issue by Nierrrrrrr** [JrCs/docker-letsencrypt-nginx-proxy-companion#182]
I use docker-compose to proxy 2 services, one exposes port 9000 and works great, and the other one which uses port 80 is not working.

The letsencrypt container will access the challenge file on port 80, and nginx seems redirect that access to my proxied service and cause a certification error.

Finally I found a way to solve this by modifying nginx.tmpl, which is mentioned by @domdorn in #107, but I wonder if there's other way to achieve this without modifying nginx.tmpl? (By twisting docker-compose.yml maybe?)

**Comment by buchdag** [comment]
I had to do the same modification to my nginx.tmpl to solve a similar issue. I'd like to know about other solutions as well (which might or might not be better than maintaining our own modified nginx.tmpl).

**Comment by stepankuzmin** [comment]
Same problem here, modificating nginx.tmpl did not help.

**Comment by buchdag** [comment]
#192 Seems to be the correct solution, works straight out of the box with vanilla nginx.tmpl file.

**Comment by almereyda** [comment]
This does not seem to avoid it in all cases. Still for docker networks to work with compose and this proxy, I am using [a patched nginx.tmpl](https://github.com/ecobytes/nginx-proxy/blob/master/nginx.tmpl) to avoid empty upstreams.

Only changing the containers exposed port away from 80 helped successfully validating its domain.

**Comment by buchdag** [comment]
#192 has been merged, reverted, then merged back again and should be here to stay. Closing.
