### ISSUE TITLE
doesn't work with shipyard

### ISSUE THREAD

**Issue by OmgImAlexis** [JrCs/docker-letsencrypt-nginx-proxy-companion#19]
Is there a way to use this without `--volumes-from`?

Shipyard doesn't currently support that command from GUI so there's no way to run it without SSHing into the machine.
https://github.com/shipyard/shipyard/issues/734

**Comment by JrCs** [comment]
Yes you can mount nginx-proxy volumes `/etc/nginx/vhost.d` and `/usr/share/nginx/html`into the docker-letsencrypt-nginx-proxy-companion

**Comment by OmgImAlexis** [comment]
That doesn't work as I just get this.

````
2016-02-05T15:56:20.402903862Z Error: can't get nginx-proxy container id !
2016-02-05T15:56:20.402994232Z Check that you use the --volumes-from option to mount volumes from the nginx-proxy.
````

**Comment by dmp1ce** [comment]
@OmgImAlexis I was also getting this error on a recreate of my containers using docker-compose. I'll keep an eye out for getting this error showing up again. Removing your containers and creating them again might help for whatever reason. It fixed the issue for me.

**Comment by OmgImAlexis** [comment]
@JrCs any ideas?

@dmp1ce it's an issue with shipyard not supporting `--volumes-from`.

**Comment by JrCs** [comment]
The problem is how to identify the nginx-proxy from the LE container using docker API

**Comment by OmgImAlexis** [comment]
Maybe add an optional ENV var that if set bypasses the function?

**Comment by OmgImAlexis** [comment]
@JrCs wouldn't something like this work? I don't really use bash but basically we check if the env var is not set, if it isn't then try and create it using the function otherwise just return the one that's already set.

````
function get_nginx_proxy_cid {
    if [[ -z "${NGINX_PROXY_CID:-}" ]]; then
        # Look for a NGINX_VERSION environment variable in containers that we have mount volumes from.
        local volumes_from=$(docker_api "/containers/$CONTAINER_ID/json" | jq -r '.HostConfig.VolumesFrom[]' 2>/dev/null)
        for cid in $volumes_from; do
            cid=${cid%:*} # Remove leading :ro or :rw set by remote docker-compose (thx anoopr)
            if [[ $(docker_api "/containers/$cid/json" | jq -r '.Config.Env[]' | egrep -c '^NGINX_VERSION=') = "1" ]];then
                export NGINX_PROXY_CID=$cid
                break
            fi
        done
        if [[ -z "${NGINX_PROXY_CID:-}" ]]; then
            echo "Error: can't get nginx-proxy container id !" >&2
            echo "Check that you use the --volumes-from option to mount volumes from the nginx-proxy." >&2
            exit 1
        fi
    fi
}
````

**Comment by JrCs** [comment]
We can't bypass the function because we need to have the nginx-proxy cid

**Comment by OmgImAlexis** [comment]
@JrCs that's what I was saying, you could add an ENV that can just be set manually if the user knows it. Since the nginx-proxy is created before this normally you'd already have it when you create this container.

**Comment by JrCs** [comment]
I have create a dev image, can you test it ?
You must add the NGINX_PROXY_CID environment variable to my LE container.

**Comment by OmgImAlexis** [comment]
Looks like it works, I couldn't even get it to start before.

![screen shot 2016-02-12 at 1 04 09 pm](https://cloud.githubusercontent.com/assets/6525926/12997486/9dc3ed46-d189-11e5-806a-60a68681a5e4.png)
![screen shot 2016-02-12 at 1 07 19 pm](https://cloud.githubusercontent.com/assets/6525926/12997485/9dc1b4c2-d189-11e5-906c-62d9c1f9760a.png)
![screen shot 2016-02-12 at 1 07 32 pm](https://cloud.githubusercontent.com/assets/6525926/12997484/9dbe92d8-d189-11e5-9fdd-c2b3ca7516ac.png)

**Comment by JrCs** [comment]
Close by 0d6d1052701dcb19faf208b1250d4f83b486b559
