### ISSUE TITLE
Reverse proxy for Dreamfactory

### ISSUE THREAD

**Issue by HavardLine** [JrCs/docker-letsencrypt-nginx-proxy-companion#194]
Hi! We have successfully installed the 3-container version described in the README. It works great for us :+1:

We have trouble implementing the DreamFactory API backend. It works fine without proxy. DreamFactory is written in PHP. Thee page is served through the proxy but it seems like something is lost on the way.

### When clicking a button, this line is added to the nginx log:
> Apr 13 07:02:45 localhost docker[22495]: api.lts.no 192.168.1.105 - - [13/Apr/2017:07:02:45 +0000] "POST /api/v2/user/session HTTP/1.1" 403 374 "https://api.lts.no/dreamfactory/dist/index.html" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"

### When clicking a button, these lines are added to the Chromium log:
> POST https://api.lts.no/api/v2/user/session 403 (Forbidden)

> TypeError: Cannot read property 'message' of undefined

Does anyone know how to fix this?

**Comment by augusteo** [comment]
disclaimer: I've never used DreamFactory

the error message sounds like a server failure. if you can get to the 403 at all, the reverse proxy should be working. Maybe better ask the dream factory people instead of here?

**Comment by HavardLine** [comment]
Hi @augusteo. Thanks for your feedback. I will try the DreamFactory comunity.
