### ISSUE TITLE
Error: can't access to '/etc/nginx/vhost.d' directory ! Check that '/etc/nginx/vhost.d' directory is declared has a writable volume.

### ISSUE THREAD

**Issue by ChrisMagnuson** [JrCs/docker-letsencrypt-nginx-proxy-companion#198]
When following the instructions I have created the nginx-proxy container as follows:
```
$ docker run -d -p 80:80 -p 443:443 \
    --name nginx-proxy \
    -v /path/to/certs:/etc/nginx/certs:ro \
    -v /etc/nginx/vhost.d \
    -v /usr/share/nginx/html \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true \
    jwilder/nginx-proxy
```
And then created the letsencrypt-nginx-proxy-companion as follows:
```
$ docker run -d \
    -v /path/to/certs:/etc/nginx/certs:rw \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    jrcs/letsencrypt-nginx-proxy-companion
```
The letsencrypt-nginx-proxy-companion container isn't able to start and the log shows the following error:

```
Error: can't access to '/etc/nginx/vhost.d' directory !
Check that '/etc/nginx/vhost.d' directory is declared has a writable volume.
```

I see that the check for `/etc/nginx/vhost.d` was added in [this commit](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/commit/459b1ed3c94b2d528af4bd32817e2625c75ccb2c).

Do the commands to launch the containers need to be updated in some way to behave more like `/path/to/certs:/etc/nginx/certs` so that both containers share a `/etc/nginx/vhost.d`?

New to docker so maybe I am making a newbie mistake here, will keep digging but if you can point me in the right direction I would appreciate it.

Thanks,

Chris

**Comment by buchdag** [comment]
Hi Chris

You have to add

`--volumes-from nginx-proxy`

to the docker run command for letsencrypt-nginx-proxy-companion in order to give it access to the volumes used by the nginx-proxy container.
