### ISSUE TITLE
nginx.tmpl in the container

### ISSUE THREAD

**Issue by ekkis** [JrCs/docker-letsencrypt-nginx-proxy-companion#202]
would it be possible to just include the nginx.tmpl in the container so the user doesn't have to fetch it and mount it?

I spent a good hour struggling to figure out why SSL support was not created in the nginx.conf until I realised my nginx.tmpl was ancient and didn't include it

the reality is that I don't want to know or care about it.  the container should just include a known-good template (whilst retaining the option for the user to override it)

**Comment by JrCs** [comment]
Hi @ekkis.
No i don't want to include nginx.tmpl in the container because it is a nginx proxy file and it's not used/needed by the letsencrypt container.
The best is to add a working version of nginx.tmpl to your repository and mount bind the file into the nginx proxy at launch.

**Comment by ekkis** [comment]
the `nginx.tmpl` doesn't belong in the nginx-proxy container because that gets a configuration file.  the config file is created by the nginx-docker-gen container which requires the template, but the specific template we're using doesn't belong in that container because it's generic and can be handed templates for various purposes.  the template we're using is specific for creating configurations that support SSL, and more specifically Let's Encrypt.  therefore that template belongs in your container

now, I could fork your project just to include the template but at the time your image is built, it can fetch the template and include it.  that's what this small PR accomplishes

not including said template means having to do a lot of extra manual work as outlined in my project (the one you suggested I create)

could you explain what your objection is?
