### ISSUE TITLE
Missing required env vars: LETSENCRYPT_HOST, LETSENCRYPT_EMAIL

### ISSUE THREAD

**Issue by shirk3y** [JrCs/docker-letsencrypt-nginx-proxy-companion#204]
`LETSENCRYPT_HOST` and `LETSENCRYPT_EMAIL` are required to make it work, but the only env var mentioned in `README` regarding running container is `VIRTUAL_HOST`.
I've spent too many hours on this and I had to read the source code in order to came up with this idea.
Please mention it in `README`. It will save people's time.

**Comment by buchdag** [comment]
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#lets-encrypt ?
