### ISSUE TITLE
HTTP connection to challenge fails

### ISSUE THREAD

**Issue by hasufell** [JrCs/docker-letsencrypt-nginx-proxy-companion#209]
Not sharing the full logs, but the line looks something like

`ERROR:acme.challenges: Unable to reach http://foo.bar/.well-known/acme-challenge/abcdefg: HTTPConnectionPool(host='foo.bar', port=80): Max retries exceeded with url: /.well-known/acme-challenge/abcdefg (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f90311a1000>: Failed to establish a new connection: [Errno 101] Network unreachable',))`

The url is accessible via curl/browser and is not html, but has the correct content.

What makes the HTTP connection fail? This seems like a bogus error and the problem lies somewhere else.

**Comment by markhaasjes** [comment]
I got the same issue. I'm able to retrieve the token from the requested url but I got the same error message.

**Comment by hasufell** [comment]
Anyone knows of a more reliable image/approach than this one?

**Comment by richter-p** [comment]
Is there any temporary fix? I've got a few certificates expiring in two days and really don't want to set up another VPS to fetch certs from there and copy them to the proxy.

**Comment by revolunet** [comment]
for some reason, the challenge file gets created but are deleted instantly, before the request happen... any idea ?

<img width="721" alt="capture d ecran 2017-11-28 a 00 07 51" src="https://user-images.githubusercontent.com/124937/33294299-4bf67a10-d3d0-11e7-8eac-b6eea1128c51.png">

**Comment by buchdag** [comment]
@revolunet `simp_le` will automatically clean the challenge files after the authorization has either succeeded or failed. I can assure you that the file won't be deleted before the request happen.

**Comment by revolunet** [comment]
thanks @buchdag, i had an hard time localizing which library does the removal :)

looks like i had two nginx-proxy instances running at that time, i restarted the setup and it works now OK :)

**Comment by buchdag** [comment]
This is an old issue. Closing.
