### ISSUE TITLE
Grouping alt name cert with domain?

### ISSUE THREAD

**Issue by j16sdiz** [JrCs/docker-letsencrypt-nginx-proxy-companion#21]
Can I group the alternative name with domain, not docker?

Let'sencrypt have a limit on number of certs per domain. And I am running a series of dockers under:

    VIRTUAL_HOST=doc.examplea.com,doc.exampleb.com,doc.examplec.com
    VIRTUAL_HOST=admin.examplea.com,admin.exampleb.com,admin.examplec.com
    VIRTUAL_HOST=www.examplea.com,www.exampleb.com,www.examplec.com
    (you get the idea)

using the current scheme, each domain (examplea, exampleb, examplec) need to request 3 times..
If we can group by the domain, it do more under the let'sencrypt quota.

**Comment by JrCs** [comment]
No we can only group subdomains with a primary domain (aka examplea.com, doc.examplea.com, admin.examplea.com, www.examplea.com) using SAN.

**Comment by j16sdiz** [comment]
@JrCs , you have misunderstood the problem.

I want to group *with same domain*.
But the current setup groups by containers *and* domain, resulting in 9 certs in total.

It should group all same base domains across all containers.

**Comment by JrCs** [comment]
@j16sdiz I need to check but if you define a LETSENCRYPT_HOST with the main domain then all the subdomains it must create only one SAN certificate with the domain and all subdmonain in it.

**Comment by j16sdiz** [comment]
@JrCs 

My use case is.... I have a "webmail" container do all webmail stuff and a "phpmyadmin" container do all phpmyadmin..  like this:

```
docker run -d \
    -e VIRTUAL_HOST=webmail.abc.com,webmail.cde.com  \
    -e LETSENCRYPT_HOST=webmail.abc.com,webmail.cde.com \
    -e LETSENCRYPT_EMAIL=support@abc.com \
    webmail

docker run -d \
    -e VIRTUAL_HOST=phpmyadmin.abc.com,phpmyadmin.cde.com  \
    -e LETSENCRYPT_HOST=phpmyadmin.abc.com,phpmyadmin.cde.com \
    -e LETSENCRYPT_EMAIL=support@abc.com \
    phpmyadmin

docker run -d \
    -e VIRTUAL_HOST=abc.com,cde.com,www.abc.com,www.cde.com  \
    -e LETSENCRYPT_HOST=abc.com,cde.com,www.abc.com,www.cde.com \
    -e LETSENCRYPT_EMAIL=support@abc.com \
    web
```

Because the ratelimit on letsencrypt, it would make sense to do this:
```
   abc.com  SAN=www.abc.com,webmail.abc.com,phpmyadmin.abc.com
   cde.com  SAN=www.cde.com,webmail.cde.com,phpmyadmin.cde.com
```

But it is not currently possible..

**Comment by JrCs** [comment]
You mix abc.com and cde.com so you can only create ONE certificate:
SAN=abc.com, cde.com, www.abc.com, www.cde.com, webmail.abc.com, webmal.cde.com, etc...

In ALL your containers defined LETSENCRYPT_HOST=abc.com, cde.com, www.abc.com, www.cde.com,webmail.abc.com,webmain.cde.com, etc....

I think it must work
