### ISSUE TITLE
Recommended approach for non-standard HTTP ports

### ISSUE THREAD

**Issue by mattberther** [JrCs/docker-letsencrypt-nginx-proxy-companion#213]
Is there a recommended approach or guidance available for how to configure the LE stuff to work when using a non-standard HTTP port (8443 or 8080 in my case). My research has led me to believe that I need to use DNS-01 validation, but not quite sure how to set this up with this container.

Thanks for any suggestions.

**Comment by buchdag** [comment]
Yes, in this case you'll need to use `dns-01` validation but you won't be able to with this project as it is. It uses [simp_le](https://github.com/zenhack/simp_le) as its Let's Encrypt client, and the only challenge method available in simp_le is `http-01`. I saw forks of the [original (abandoned) simp_le](https://github.com/kuba/simp_le) that try add support for `dns-01` challenge, [like this one](https://github.com/meeuw/simp_le/commit/939ecb94f35cbb7437dc53afd55e97ba6a9880e7).
