### ISSUE TITLE
TLSA/HPKP: Any chance to use the existing key on renew?

### ISSUE THREAD

**Issue by narolinus** [JrCs/docker-letsencrypt-nginx-proxy-companion#217]
Is there a way to use the existing key on certificate renewal? By default it seems to generate a new keypair on each renew. This renders TLSA- and HPKP-DNS-entries kind of useless. So there seems to be no easy way to use Public Key Pinning or TLSA together witch nginx-proxy-companion, instead one would need to update the entries manually, including a time window of failing certificate-checks for the length of the DNS-TTL.

**Comment by buchdag** [comment]
That should be possible if `--reuse_key True` is passed to `simp_le`.

That's not possible right now without manually modifying [letsencrypt_service](../blob/master/app/letsencrypt_service#L112) but adding a new environment variable that would make it possible does not seems too hard.

**Comment by narolinus** [comment]
That would be a great addition. I would really appreciate it.

**Comment by buchdag** [comment]
PR opened.

**Comment by buchdag** [comment]
Closed by #218
