### ISSUE TITLE
Usage of certs for other services

### ISSUE THREAD

**Issue by konstantinj** [JrCs/docker-letsencrypt-nginx-proxy-companion#22]
Hi @JrCs ,
could you generate all certificates separately so it's easier to use them directly with other services like postfix?

> -f privkey.pem -f cert.pem -f chain.pem

afterwards you can just cat cert.pem chain.pem > fullchain.pem so all certs are available for direct usage.

Also simp_le calls key only "key.pem" but most services rely on "privkey.pem" since the letsencrypt client is calling it like this.

**Comment by JrCs** [comment]
Are you sure that services like postfix can't use fullchain.pem as certificate ?

**Comment by jokogr** [comment]
Such feature would be helpful for me, too. I have some services running in Docker containers which do not need a reverse proxy, yet they need an SSL certificate.

Do you have any thoughts on how I could handle this?

**Comment by JrCs** [comment]
@jokogr the best is to use a different image container to create your certificates.
You can use this container with a VIRTUAL_HOST in your service docker containers to just create the certificates but it's not really elegant.

**Comment by jokogr** [comment]
@JrCs thanks for the prompt reply! Do you have another Docker image to suggest?

**Comment by JrCs** [comment]
I don't have a docker image to suggest.
The best is perhaps to get a docker image that use the new dns challenge of letsencrypt, so you don't have to use a web server to create a certificate.
