### ISSUE TITLE
simp_le 0.2.0 is outdated

### ISSUE THREAD

**Issue by almereyda** [JrCs/docker-letsencrypt-nginx-proxy-companion#221]
As configured by [`install_simp_le.sh`#L9-L11](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/install_simp_le.sh#L9-L11), simp_le is installed from zenhack/simp_le:0.2.0, yet this branch does not exist anymore. [`master`](https://github.com/zenhack/simp_le/branches) seems to be a valid substitute.

**Comment by almereyda** [comment]
Before I hadn't recognised the releases, which mention `0.2.0`.
Still the readme claims to be advanced to [`0.3.0`](https://github.com/zenhack/simp_le#030), for which no tag exists.

**Comment by buchdag** [comment]
[simp_le 0.3.0 isn't released yet.](https://github.com/zenhack/simp_le/issues/57#)
