### ISSUE TITLE
How to add more info at centification like Organization?

### ISSUE THREAD

**Issue by angelrr7702** [JrCs/docker-letsencrypt-nginx-proxy-companion#23]
Hi,

 Thanks for your docker container . , how I can add more info to the certicated provided by let's encrypt like Organization name etc ?

sincerely
Angel Rodriguez

**Comment by JrCs** [comment]
You need to create your own certificate and let's letsencrypt sign it for you.
You must use a native letsencrypt client to do that.
This container can't be use for that.
