### ISSUE TITLE
[DKIM] Invalid character in DNS name

### ISSUE THREAD

**Issue by andreagentili** [JrCs/docker-letsencrypt-nginx-proxy-companion#233]
As far I can understand, for DomainKeys Identified Mail (DKIM) to work you need domains like `<something>._domainkey.<domain>`, `like mta._domainkey.website.com`. But if I use `LETSENCRYPT_HOST=mta._domainkey.website.com` (e.g. in docker-compose) I get the `Invalid character in DNS name` error:
```
letsencrypt-nginx-proxy-companion_1  | ACME server returned an error: urn:acme:error:malformed :: The request message was malformed :: Error creating new authz :: Invalid character in DNS name

```

Is there any way I can use _domainkey with the companion? Thank you very much.

Note: An online ACE converter like [this](https://www.netim.com/domain-name/accented-domains.html) reports that the _domainkey is identical in ACE format.

**Comment by andreagentili** [comment]
This may be useful: https://community.letsencrypt.org/t/underscore-in-subdomain-fails/31431/6. Lets'encrypt doesn't support underscore in DNS names.

**Comment by buchdag** [comment]
The DKIM public key and its selector are a DNS TXT record you set up at your domain name registrar or DNS provider.

It is unrelated to SSL certificates, Lets Encrypt or proxying.
