### ISSUE TITLE
simp_le claims failed verification, but still generates certificates

### ISSUE THREAD

**Issue by evilstiefel** [JrCs/docker-letsencrypt-nginx-proxy-companion#234]
Since sim_ple has been officially "abandoned", I can't really say how this fits.

The container is functional and generates valid certificates, but when creating these, the following output is produced:

```
2017/07/10 09:08:16 Received event start for container fb4073151690
2017/07/10 09:08:31 Debounce minTimer fired
2017/07/10 09:08:31 Generated '/app/letsencrypt_service_data' from 6 containers
2017/07/10 09:08:31 Running '/app/update_certs'
Creating/renewal <domain1> certificates... (<domain1> <domain2>)
2017-07-10 09:08:32,365:INFO:simp_le:1213: Generating new account key
2017-07-10 09:08:35,089:WARNING:simp_le:1304: <domain1> was not successfully self-verified. CA is likely to fail as well!
2017-07-10 09:08:35,469:WARNING:simp_le:1304: <domain2> was not successfully self-verified. CA is likely to fail as well!
2017-07-10 09:08:35,873:INFO:simp_le:1314: Generating new certificate private key
2017-07-10 09:08:36,931:INFO:simp_le:393: Saving account_key.json
2017-07-10 09:08:36,932:INFO:simp_le:393: Saving key.pem
2017-07-10 09:08:36,932:INFO:simp_le:393: Saving chain.pem
2017-07-10 09:08:36,932:INFO:simp_le:393: Saving fullchain.pem
2017-07-10 09:08:36,932:INFO:simp_le:393: Saving cert.pem
```

As you can see, the tool warns that verification has failed, but then continues to generate the certificates. Is this expected behaviour? I have previously switched to "getssl", since it's still being developed, but liked the composition of docker-proxy, docker-gen and this helper container (as it's being referenced in a lot of tutorials).

**Comment by buchdag** [comment]
[simp_le have a fork that is still actively maintained](https://github.com/zenhack/simp_le), this project switched to it a few months ago.

As for the failed self-verification, I noticed it too but haven't been able to find the reason yet.

**Comment by evilstiefel** [comment]
Thanks for letting me know, maybe someone can shed some light on the "failed verification" messages :)

**Comment by buchdag** [comment]
One thing I'm sure, It is not happening on every host where I deployed the docker nginx-proxy stack and/or on every proxyed containers. Some of them won't self verify, others are ok.

**Comment by buchdag** [comment]
Self verification in `simp_le` is based on certbot / acme `simple_verify`, and [self verification is deemed unreliable by cerbot devs themselves](https://github.com/certbot/certbot/issues/1586#issuecomment-186020863) (as in there is a lot of way to have self verification fail but LE challenge succeed anyway).

So I guess one should not be too concerned if self verification fails as long as certificates get successfully generated.

**Comment by buchdag** [comment]
Self verification have been removed from `simp_le` due to its lack of reliability, so closing this issue.
