### ISSUE TITLE
Use DNS record as challenge method?

### ISSUE THREAD

**Issue by Pylipala** [JrCs/docker-letsencrypt-nginx-proxy-companion#236]
On [LetEncrypt official site](https://letsencrypt.org/how-it-works/), it says the agent could be challenged by 

>Provisioning a DNS record under example.com 

How can we configure docker-letsencrypt-nginx-proxy-compaion to use this method?

**Comment by buchdag** [comment]
You can't, docker-letsencrypt-nginx-proxy-companion use a third party client called [simp_le](https://github.com/zenhack/simp_le) that does not implement DNS challenge.
