### ISSUE TITLE
Can't get new certificates

### ISSUE THREAD

**Issue by ErroneousBosch** [JrCs/docker-letsencrypt-nginx-proxy-companion#238]
I was running two separate web containers for a couple of weeks now, each with its own cert and am adding a third, but LE won't issue a new cert, saying that I have been issued too many. Looking at their[ rate limits](https://letsencrypt.org/docs/rate-limits/), this shouldn't be happening. Is it possible one of my certs was getting created anew each time? I realize I'm going to have to wait a week before I try to get new certs, but I'd appreciate some insight.

Domains redacted out, but I was running two containers (one for xxx.net and one for library.xxx.net). When I try to load the new site (listed as handfuls.xxx.net), it is trying to use the base domain cert, probably because it is erroring when trying to register the new cert? 

```
2017/07/19 16:45:35 Generated '/app/letsencrypt_service_data' from 15 containers
2017/07/19 16:45:35 Running '/app/update_certs'
2017/07/19 16:45:35 Watching docker events
2017/07/19 16:45:36 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
2017-07-19 16:45:37,022:INFO:simp_le:1384: Certificates already exist and renewal is not necessary, exiting with status code 1.
2017-07-19 16:45:37,843:INFO:simp_le:1213: Generating new account key
2017-07-19 16:45:41,628:INFO:simp_le:1306: library.xxx.net was successfully self-verified
2017-07-19 16:45:42,327:INFO:simp_le:1314: Generating new certificate private key
ACME server returned an error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new cert :: too many certificates already issued for exact set of domains: library.xxx.net


Debugging tips: -v improves output verbosity. Help is available under --help.
2017-07-19 16:45:45,635:INFO:simp_le:1384: Certificates already exist and renewal is not necessary, exiting with status code 1.
2017/07/19 16:46:49 Received signal: terminated
2017/07/19 16:46:49 Received signal: terminated
2017/07/19 16:47:10 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
2017/07/19 16:47:10 Watching docker events
2017/07/19 16:47:10 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
2017-07-19 16:47:11,497:INFO:simp_le:1384: Certificates already exist and renewal is not necessary, exiting with status code 1.
2017-07-19 16:47:12,299:INFO:simp_le:1213: Generating new account key
ACME server returned an error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new registration :: too many registrations for this IP


Debugging tips: -v improves output verbosity. Help is available under --help.
2017-07-19 16:47:14,930:INFO:simp_le:1384: Certificates already exist and renewal is not necessary, exiting with status code 1.
2017/07/19 16:52:02 Received event die for container 5ce6e400e9c2
2017/07/19 16:52:02 Received event die for container 10fc5a6f0403
2017/07/19 16:52:02 Received event stop for container 5ce6e400e9c2
2017/07/19 16:52:02 Received event stop for container 10fc5a6f0403
2017/07/19 16:52:03 Received event start for container 967bdce68a05
2017/07/19 16:52:03 Received event start for container 180d307c4b5f
2017/07/19 16:52:12 Received event die for container 174f993bdaf8
2017/07/19 16:52:12 Received event stop for container 174f993bdaf8
2017/07/19 16:52:13 Received event start for container 74aaa2d5281c
2017/07/19 16:52:28 Debounce minTimer fired
2017/07/19 16:52:28 Generated '/app/letsencrypt_service_data' from 15 containers
2017/07/19 16:52:28 Running '/app/update_certs'
2017-07-19 16:52:32,635:ERROR:urllib3.connection:360: Certificate did not match expected hostname: handfuls.xxx.net. Certificate: {'subjectAltName': [('DNS', 'xxx.net')], 'subject': ((('commonName', u'xxx.net'),),)}
2017-07-19 16:52:32,639:ERROR:acme.challenges:311: Unable to reach http://handfuls.xxx.net/.well-known/acme-challenge/DKG3qeOtQWpOpmQK94q_82tgKlBbSxjM-Ujozbqab4Y: hostname 'handfuls.xxx.net' doesn't match 'xxx.net'
2017-07-19 16:52:32,640:WARNING:simp_le:1304: handfuls.xxx.net was not successfully self-verified. CA is likely to fail as well!
2017-07-19 16:52:33,691:INFO:simp_le:1306: xxx.net was successfully self-verified
2017-07-19 16:52:34,927:ERROR:urllib3.connection:360: Certificate did not match expected hostname: library.xxx.net. Certificate: {'subjectAltName': [('DNS', 'xxx.net')], 'subject': ((('commonName', u'xxx.net'),),)}
2017-07-19 16:52:34,931:ERROR:acme.challenges:311: Unable to reach http://library.xxx.net/.well-known/acme-challenge/1nnWT7TrGfD8xMQu5NkIPX7UiR31NKr8fu_BLlYhLK0: hostname 'library.xxx.net' doesn't match 'xxx.net'
2017-07-19 16:52:34,931:WARNING:simp_le:1304: library.xxx.net was not successfully self-verified. CA is likely to fail as well!
2017-07-19 16:52:35,892:INFO:simp_le:1314: Generating new certificate private key
2017-07-19 16:52:38,313:INFO:simp_le:393: Saving key.pem
2017-07-19 16:52:38,314:INFO:simp_le:393: Saving fullchain.pem
2017-07-19 16:52:38,315:INFO:simp_le:393: Saving cert.pem
2017-07-19 16:52:39,154:INFO:simp_le:1384: Certificates already exist and renewal is not necessary, exiting with status code 1.
2017-07-19 16:52:39,973:INFO:simp_le:1384: Certificates already exist and renewal is not necessary, exiting with status code 1.
2017/07/19 16:53:50 Received event die for container 967bdce68a05
2017/07/19 16:53:50 Received event die for container 180d307c4b5f
2017/07/19 16:53:51 Received event stop for container 967bdce68a05
2017/07/19 16:53:51 Received event stop for container 180d307c4b5f
2017/07/19 16:53:51 Received event start for container c6ffdb269c0b
2017/07/19 16:53:52 Received event start for container 8e914c706a30
2017/07/19 16:54:00 Received event die for container 74aaa2d5281c
2017/07/19 16:54:01 Received event stop for container 74aaa2d5281c
2017/07/19 16:54:02 Received event start for container 17f145ae360d
2017/07/19 16:54:17 Debounce minTimer fired
2017/07/19 16:54:17 Generated '/app/letsencrypt_service_data' from 15 containers
2017/07/19 16:54:17 Running '/app/update_certs'
2017-07-19 16:54:18,164:INFO:simp_le:1213: Generating new account key
ACME server returned an error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new registration :: too many registrations for this IP


Debugging tips: -v improves output verbosity. Help is available under --help.
2017-07-19 16:54:21,114:INFO:simp_le:1213: Generating new account key
ACME server returned an error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new registration :: too many registrations for this IP


Debugging tips: -v improves output verbosity. Help is available under --help.
2017-07-19 16:54:24,686:INFO:simp_le:1306: xxx.net was successfully self-verified
2017-07-19 16:54:25,176:INFO:simp_le:1314: Generating new certificate private key
2017-07-19 16:54:26,759:INFO:simp_le:393: Saving key.pem
2017-07-19 16:54:26,759:INFO:simp_le:393: Saving fullchain.pem
2017-07-19 16:54:26,760:INFO:simp_le:393: Saving cert.pem
```

**Comment by ErroneousBosch** [comment]
Oh and I have tried removing and restarting everything, no luck

**Comment by ErroneousBosch** [comment]
I checked and all three certs are coming back as issued, Right now I can get to the main page and the library page fine, but handfuls gives me a NET::ERR_CERT_COMMON_NAME_INVALID, with the cert saying it id for xxx.net instead of handfuls.xxx.net. Just ried it on a completely different machine and browser and it does the same.

I checked and the nginx conf is setup for the correct cert.

**Comment by buchdag** [comment]
Can you post the commands / docker-compose file you are using ?

Does crt.sh shows that some certificates were issued multiple times per week ? (There is a delay before a newly issued certificate shows up there, can't say how much for sure, a few days at most)

**Comment by ErroneousBosch** [comment]
Yes, crt.sh is showing certs are getting issued multiple times per week/day, showing the following:
![screenshot from 2017-07-20 08-47-48](https://user-images.githubusercontent.com/20829218/28418249-0bcfac58-6d29-11e7-8c78-b99ee0e12f4b.png)
![screenshot from 2017-07-20 08-51-25](https://user-images.githubusercontent.com/20829218/28418251-0bd6936a-6d29-11e7-905f-8b271abd4e42.png)
![screenshot from 2017-07-20 08-51-39](https://user-images.githubusercontent.com/20829218/28418250-0bd2dcf2-6d29-11e7-8c6a-395457ae3368.png)


Compose below: 
```
version: '3'
services:
  calibre-web:
    image: technosoft2000/calibre-web
    container_name: calibre-web
    volumes:
      - "/media/Storage/Calibre:/books:rw"
      - "/var/calibre/metadata.db:/books/metadata.db:rw"
    ports:
      - "8083:8083"
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=America/New_York
      - PGID=1000 
      - PUID=1000
      - VIRTUAL_HOST=library.xxx.net
      - VIRTUAL_PORT=8083
      - LETSENCRYPT_HOST=library.xxx.net
      - LETSENCRYPT_EMAIL=user@xxx.net
    depends_on:
      - proxy
      - letsencrypt
    networks:
      - proxynet

  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    networks:
      - proxynet
    ports:
      - "13.13.13.180:80:80"
      - "13.13.13.180:443:443"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    volumes:
      - /var/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/nginx/vhost.d:/etc/nginx/vhost.d 
      - /var/nginx/html:/usr/share/nginx/html
    environment:
      - DEFAULT_HOST=xxx.net

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    networks:
      - proxynet
    volumes:
      - /var/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/nginx/vhost.d:/etc/nginx/vhost.d 
      - /var/nginx/html:/usr/share/nginx/html
    depends_on:
      - proxy
    # environment:
    #   - DEBUG=true

  www_main:
    image: nginx:alpine
    container_name: www_main
    networks:
      - proxynet
    volumes:
      - ../www:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=xxx.net
      - LETSENCRYPT_HOST=xxx.net
      - LETSENCRYPT_EMAIL=user@xxx.net
    depends_on:
      - proxy
      - letsencrypt

  handfuls:
    image: drupal:7
    container_name: handfuls
    networks:
      - proxynet
    volumes:
      - /var/handfuls/modules:/var/www/html/modules
      - /var/handfuls/profiles:/var/www/html/profiles
      - /var/handfuls/themes:/var/www/html/themes
      - /var/handfuls/sites:/var/www/html/sites
    environment:
      - VIRTUAL_HOST=handfuls.xxx.net
      - LETSENCRYPT_HOST=handfuls.xxx.net
      - LETSENCRYPT_EMAIL=user@xxx.net
    depends_on:
      - proxy
    links:
      - mariadb

networks:
  proxynet:
    external:
      name: nginx-proxy

```

**Comment by buchdag** [comment]
I see a bunch of strange stuff / probable misconfiguration:

- ports 8083:8083 on the calibre-web service. That bind the container's port to a public port, potentially bypassing the proxy. Any specific reason of doing this ?
- the le companion require exposed ports on proxyed containers : https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#usage (last paragraph right before separate containers)
- the local docker socket bound to two different places on the letsencrypt container. It should only be bound to /var/run/docker.sock

Still no clue why your certs got generated multiple times a day. Did you wipe the /var/nginx/certs between tests ?

**Comment by ErroneousBosch** [comment]
The port exposure was for testing purposes, to allow me to access it on my local network and make sure the service was running. It wasn't affecting the proxy when I was running with it, external traffic all went through the proxy. The Drupal7 container is based on the official PHP7 Apache container and exposes Port 80. 

I did wipe the certs once when I was setting up the initial two containers, since I had them setup as a SAN, but that was not working across multiple containers, so I wiped and went to one cert per container. I haven't wiped them for this round of testing and spinning up this latest container.

**Comment by ErroneousBosch** [comment]
New development: Library has stopped working now

**Comment by githtz** [comment]
You really need to expose port 80 in your docker-compose file for each docker container you're running. Should do like this:
`version: '3'
services:
  calibre-web:
    image: technosoft2000/calibre-web
    container_name: calibre-web
    volumes:
      - "/media/Storage/Calibre:/books:rw"
      - "/var/calibre/metadata.db:/books/metadata.db:rw"
    ports:
      - "8083:8083"
    expose:
      - "80"
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=America/New_York
      - PGID=1000 
      - PUID=1000
      - VIRTUAL_HOST=library.xxx.net
      - VIRTUAL_PORT=8083
      - LETSENCRYPT_HOST=library.xxx.net
      - LETSENCRYPT_EMAIL=user@xxx.net
    depends_on:
      - proxy
      - letsencrypt
    networks:
      - proxynet

  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    networks:
      - proxynet
    ports:
      - "13.13.13.180:80:80"
      - "13.13.13.180:443:443"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    volumes:
      - /var/nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/nginx/vhost.d:/etc/nginx/vhost.d 
      - /var/nginx/html:/usr/share/nginx/html
    environment:
      - DEFAULT_HOST=xxx.net

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    networks:
      - proxynet
    volumes:
      - /var/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/nginx/vhost.d:/etc/nginx/vhost.d 
      - /var/nginx/html:/usr/share/nginx/html
    depends_on:
      - proxy
    # environment:
    #   - DEBUG=true

  www_main:
    image: nginx:alpine
    container_name: www_main
    networks:
      - proxynet
    volumes:
      - ../www:/usr/share/nginx/html
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=xxx.net
      - LETSENCRYPT_HOST=xxx.net
      - LETSENCRYPT_EMAIL=user@xxx.net
    depends_on:
      - proxy
      - letsencrypt

  handfuls:
    image: drupal:7
    container_name: handfuls
    networks:
      - proxynet
    volumes:
      - /var/handfuls/modules:/var/www/html/modules
      - /var/handfuls/profiles:/var/www/html/profiles
      - /var/handfuls/themes:/var/www/html/themes
      - /var/handfuls/sites:/var/www/html/sites
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=handfuls.xxx.net
      - LETSENCRYPT_HOST=handfuls.xxx.net
      - LETSENCRYPT_EMAIL=user@xxx.net
    depends_on:
      - proxy
    links:
      - mariadb

networks:
  proxynet:
    external:
      name: nginx-proxy`

**Comment by ErroneousBosch** [comment]
The ports actually had no bearing on this issue. Turned out to be a misconfiguration in the nginx files that was killing the linkup. I have updated the containers since then and it seems to have resolved the issues I was having.

Also, what would be the point of exposing port 80 on a container that has no services running on that port? Calibre-web doesn't have anything on port 80; it is a python script and only uses port 8083. Opening port 80 seems to me to have more potential to cause issues than resolve them, since if nginx-proxy looks on that port it will return an http:500 error.

**Comment by dasmedium** [comment]
@ErroneousBosch 
Can you share how you changed the Nginx misconfiguration issue? I am having a similar problem. :)

**Comment by githtz** [comment]
@ErroneousBosch you're right, if there is no application on that port exposing the port is useless. 

I've had a very similar issue a few weeks ago. It looks like the certbot does only retrieve certificates if there is an application on port 80. A few containers that I'm running do not have applications on port 80 but I still needed the certificates. So I created a simple httpd-container that has the VIRTUAL_HOST-variable set to all the hosts that do not export port 80 by their own. @dasmedium maybe this might help you?

**Comment by martinschueller** [comment]
@githtz Thanks for the fix. This wasn't needed in older versions. I suppose this way auto-renewing doesn't work and you'd have to start the httpd-container once in a while to auto renew. Correct?

**Comment by buchdag** [comment]
I don't know how @githtz came to the conclusion that `letsencrypt-nginx-proxy-companion` only retrieves certificates if there is an application on port 80, I never had any issue proxying lots of apps that don't expose and/or listen on port 80 at all (chronograf, gitlab, gogs, grafana, kibana, portainer to name a few) and more importantly there is nothing in the code that could make the container behave this way.

**Comment by martinschueller** [comment]
@buchdag me neither. Also used gitlab, graphana etc. But in the most recent version it doesn't seem to work anymore for apps on different ports.

**Comment by buchdag** [comment]
I'm running the latest version on several hosts with non port 80 containers and zero issues.

I Just forced a certificate renew on two of them without issue either.

![renew](https://user-images.githubusercontent.com/13685826/33447095-7913a764-d602-11e7-9e70-b189690f8ab6.png)

**Comment by githtz** [comment]
@buchdag I came to the conclusion since I didn't get any certs if port 80 was not exposed in either the docker-compose file or the run command of the container, but my conclusion might be faulty of course. I'll keep it a try without exposal and report my results.

**Comment by buchdag** [comment]
Closing due to age and no new comment for more than 90 days.
