### ISSUE TITLE
Docker Compose v3

### ISSUE THREAD

**Issue by tylerbuchea** [JrCs/docker-letsencrypt-nginx-proxy-companion#239]
Do you have any examples of a simple docker-compose setup that uses v3? I think it'd be a great addition to the README.

I was getting an error when trying out [simple-lets-encrypt-docker-compose-sample](https://github.com/dmitrym0/simple-lets-encrypt-docker-compose-sample/blob/master/docker-compose.yml) with docker-compose v3. `volumes_from` isn't supported in v3. My solution was to downgrade to v2 but I'd like to be able to use the latest.

If anyone has suggestions on an easy/simple solution to fix the sample above to use v3 then I'd be happy to make a new example and submit a PR to this repos README 😀

**Comment by tylerbuchea** [comment]
Just found the v3 link 😅

**Comment by opyate** [comment]
Sharing is caring: https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
