### ISSUE TITLE
Certs not generated

### ISSUE THREAD

**Issue by SebastianStehle** [JrCs/docker-letsencrypt-nginx-proxy-companion#243]
Hi, 
I am testing the following config:

	version: '2.1'
	services:
	  squidex_squidex:
		image: "squidex/squidex:latest"
		environment:
		  ...
		  - VIRTUAL_HOST=${SQUIDEX_DOMAIN}
		volumes:
		  - /etc/squidex/keys
		restart: unless-stopped

	  squidex_proxy:
		image: jwilder/nginx-proxy
		ports:
		  - "80:80"
		  - "443:443"
		volumes:
		  - /etc/nginx/vhost.d
		  - /etc/nginx/certs:/etc/nginx/certs:ro
		  - /usr/share/nginx/html
		  - /var/run/docker.sock:/tmp/docker.sock:ro
		depends_on:
		  - squidex_squidex
		labels:
		  - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

	  squidex_encrypt:
		image: jrcs/letsencrypt-nginx-proxy-companion
		volumes:
		  - /etc/nginx/certs:/etc/nginx/certs:rw
		  - /var/run/docker.sock:/var/run/docker.sock:ro
		volumes_from:
		  - squidex_proxy
		depends_on:
		  - squidex_proxy
		restart: unless-stopped

Http works fine, but no certificates are generated. I have no idea what I do wrong. Do you have some tipps?

**Comment by buchdag** [comment]
Do you have the [required LETSENCRYPT environment variables](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#lets-encrypt) on your squidex_squidex service ?

**Comment by SebastianStehle** [comment]
Okay, now it is official: I am stupid
