### ISSUE TITLE
Proxy not routing host header?

### ISSUE THREAD

**Issue by imaia** [JrCs/docker-letsencrypt-nginx-proxy-companion#244]
I'm having a problem where my nginx listening to the proxy is not being able to route the request to my app. It always shows the nginx index, even though it does the SSL handshake with the proxy nginx without problem. What could be causing this?

**Comment by buchdag** [comment]
Your issue seems related to nginx-proxy configuration rather than docker-letsencrypt-nginx-proxy-companion. The letsencrypt-companion only functions are to create / renew certificate and reload the nginx proxy on cert creation or renewal.

**Comment by imaia** [comment]
Thanks @buchdag I'm reaching the nginx-proxy community for help.
