### ISSUE TITLE
host_path - is not a valid absolute path (docker stack file)

### ISSUE THREAD

**Issue by swapnil7434** [JrCs/docker-letsencrypt-nginx-proxy-companion#245]
I have created docker stack file with following configuration

nginx:
image: 'nginx:latest'
ports:

'80:80'
'443:443'
tags:
app=cornerstone
env=dev
volumes:
'/etc/nginx/conf.d'
'/etc/nginx/vhost.d'
'/usr/share/nginx/html'
'../../../volumes/proxy/certs:/etc/nginx/certs:r'
labels:
'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'
nginx-gen:
image: 'jwilder/docker-gen:latest'
tags:
app=cornerstone
env=dev
volumes_from:
nginx
volumes:
'/var/run/docker.sock:/tmp/docker.sock:ro'
'../../../volumes/proxy/templates:/etc/docker-gen/templates:ro'
labels:

'com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen'
command: '-notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf'
nginx-letsencrypt:
image: 'jrcs/letsencrypt-nginx-proxy-companion:latest'
tags:
app=cornerstone
env=dev
volumes_from:
nginx
volumes:
'/var/run/docker.sock:/var/run/docker.sock:ro'
'../../../volumes/proxy/certs:/etc/nginx/certs:rw'
But when i am redeploying file, i am getting following error.

Service 'nginx': {u'binddefinition': {u'host_path': [u"'host_path': ../../../volumes/proxy/certs is not a valid absolute path"]}}

**Comment by buchdag** [comment]
The error message is rather clear, you can't use relative (../../stuff) paths for docker volumes, only absolute path (like /path/to/stuff).

That's not entirely true with compose files though, as you can do stuff like this:

```
volumes:
  - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
```

if the `nginx.tmpl` file is located right next to your compose file. But `../` wont work wether you are using a compose file or not.

**Comment by buchdag** [comment]
No answers from issue creator for more than three months, closing.
