### ISSUE TITLE
Was not successfully self-verified.

### ISSUE THREAD

**Issue by raisiqueira** [JrCs/docker-letsencrypt-nginx-proxy-companion#246]
I'm running this image on a server with a valid domain, yesterday I ran the tests on my VPS and it worked normal using [Dmitry's docker-compose](https://github.com/dmitrym0/simple-lets-encrypt-docker-compose-sample), but today doing the same test again, is returning the log down:
```
letsencrypt                          | 2017-08-03 17:41:28,175:INFO:simp_le:1213: Generating new account key
nginx-proxy                          | nginx.1    | b.suadieta.net 35.188.64.201 - - [03/Aug/2017:17:41:30 +0000] "GET /.well-known/acme-challenge/5emB8QeqwEjNy58-CfclrAnPII4sC36qzYf4XyLxfEI HTTP/1.1" 302 0 "-" "python-requests/2.18.1"
nginx-proxy                          | nginx.1    | b.suadieta.net 35.188.64.201 - - [03/Aug/2017:17:41:30 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 3824 "-" "python-requests/2.18.1"
letsencrypt                          | 2017-08-03 17:41:30,697:WARNING:simp_le:1304: b.suadieta.net was not successfully self-verified. CA is likely to fail as well!
letsencrypt                          | 2017-08-03 17:41:30,809:INFO:simp_le:1314: Generating new certificate private key
nginx-proxy                          | nginx.1    | b.suadieta.net 66.133.109.36 - - [03/Aug/2017:17:41:31 +0000] "GET /.well-known/acme-challenge/5emB8QeqwEjNy58-CfclrAnPII4sC36qzYf4XyLxfEI HTTP/1.1" 302 0 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
nginx-proxy                          | nginx.1    | b.suadieta.net 66.133.109.36 - - [03/Aug/2017:17:41:31 +0000] "GET /wp-admin/install.php HTTP/1.1" 200 3824 "http://b.suadieta.net/.well-known/acme-challenge/5emB8QeqwEjNy58-CfclrAnPII4sC36qzYf4XyLxfEI" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
letsencrypt                          | 2017-08-03 17:41:35,259:ERROR:simp_le:1272: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/m1PeM5lIcMjgwY5DafWViebIpfgKB2ouGIDJYaHQ5nA
letsencrypt                          | Challenge validation has failed, see error log.
letsencrypt                          | 
letsencrypt                          | Debugging tips: -v improves output verbosity. Help is available under --help.
letsencrypt                          | Sleep for 3600s
```

**Comment by stratosgear** [comment]
I get the same error I do not know how to debug it and start looking what is wrong.  I DO expose the proper ports and everything but I still get the same error... :(

**Comment by aneumeier** [comment]
The same happens here in an installation that was working before.

Upgraded both nginx-proxy and letsencrypt-nginx-proxy-companion to the respective latest versions, still the same.

**Comment by karimtabet** [comment]
Same here. Could be a problem with LE.

**Comment by buchdag** [comment]
Just tried and it worked out of the box on a fresh host.

Ubuntu 16.04
Docker 17.06
docker-compose 1.15.0

`Creating Diffie-Hellman group (can take several minutes...)
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
............+............++*++*
Sleep for 3600s
2017/08/07 14:03:50 Generated '/app/letsencrypt_service_data' from 3 containers
2017/08/07 14:03:50 Running '/app/update_certs'
2017/08/07 14:03:50 Watching docker events
2017/08/07 14:03:50 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
Reloading nginx proxy (7b26f73a05f7634a2c8a30e4e7185b1d11fbbf146bf0782f8f90592af7ad856c)...
Q2017/08/07 14:03:51 Generated '/etc/nginx/conf.d/default.conf' from 3 containers
;2017/08/07 14:03:51 [notice] 43#43: signal process started
Creating/renewal testle.domain.tld certificates... (testle.domain.tld)
2017-08-07 14:03:52,633:INFO:simp_le:1213: Generating new account key
2017-08-07 14:03:58,047:INFO:simp_le:1306: testle.duuu.ch was successfully self-verified
2017-08-07 14:03:58,310:INFO:simp_le:1314: Generating new certificate private key
2017-08-07 14:04:03,565:INFO:simp_le:393: Saving account_key.json
2017-08-07 14:04:03,566:INFO:simp_le:393: Saving key.pem
2017-08-07 14:04:03,566:INFO:simp_le:393: Saving chain.pem
2017-08-07 14:04:03,567:INFO:simp_le:393: Saving fullchain.pem
2017-08-07 14:04:03,567:INFO:simp_le:393: Saving cert.pem
Reloading nginx proxy (7b26f73a05f7634a2c8a30e4e7185b1d11fbbf146bf0782f8f90592af7ad856c)...
2017/08/07 14:04:03 Generated '/etc/nginx/conf.d/default.conf' from 3 containers
2017/08/07 14:04:03 [notice] 55#55: signal process started
Sleep for 3600s`

**Comment by karimtabet** [comment]
Hmm. Thanks for confirming that @buchdag 

Could you please have a look and see if there is anything obvious about why my configuration isn't working?

**docker-compose.yml:**
```version: '2.1'
services:

  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"
    volumes_from:
      - creativeopportunities
    depends_on:
      - creativeopportunities

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  creativeopportunities:
    image: karimtabet/papusa:0.2.77
    container_name: creativeopportunities
    volumes:
      - "./volumes/nginx-creativeopportunities/conf.d/:/etc/nginx/conf.d"
      - /srv/logs
      - /srv/papusa
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=www.creativeopportunities.co.uk,creativeopportunities.co.uk
      - LETSENCRYPT_HOST=www.creativeopportunities.co.uk,creativeopportunities.co.uk
      - LETSENCRYPT_EMAIL=dev@karimtabet.com
```
**nginx.conf:**

```
upstream creativeopportunities {
  ip_hash;
  server creativeopportunities:8000;
}

# portal
server {
    listen 8000;
    server_name localhost;
    location / {
        proxy_pass http://creativeopportunities/;
    }
    location /static {
        alias /srv/papusa/static;
    }
}
server {
    listen 80;
    server_name creativeopportunities.co.uk;
    location / {
        proxy_pass http://creativeopportunities/;
    }
    location /static {
        alias /srv/papusa/static;
    }
}
```
Am I missing something here?

**Comment by unguiculus** [comment]
I recently got this too. I added DEBUG=true which revealed the actual error: `SERVFAIL looking up CAA`. I don't have a solution yet.

See https://community.letsencrypt.org/t/caa-servfail-changes/38298

**Comment by andiwi** [comment]
I had a similar problem `SERVFAIL looking up A for ...com`
There were some misconfigurations with the DNS Servers. I am using namecheap and disabled the DNSSEC. Now the certification process finally works again! *yay!*

This post helped me: https://community.letsencrypt.org/t/dns-problem-servfail-looking-up-a-for-sub-domain-tld/19864 

Hopefully this helps you too!

**Comment by buchdag** [comment]
Self verification is no longer relevant (it was unreliable and consequently removed from `simp_le`) and a note on CAA was added to both the README and project's wiki, so I'm closing this issue.
