### ISSUE TITLE
Which container needs environment variables

### ISSUE THREAD

**Issue by mjmayer** [JrCs/docker-letsencrypt-nginx-proxy-companion#252]
Looking over the documentation, it is not clear when using static container names which container needs which environment variables.

Is it correct that the nginx-letsencrypt container needs 'NGINX_DOCKER_GEN_CONTAINER=nginx-gen' and the nginx-gen container needs '-e NGINX_PROXY_CONTAINER=nginx' ?

**Comment by buchdag** [comment]
Hi

The environment variables `NGINX_DOCKER_GEN_CONTAINER` and `NGINX_PROXY_CONTAINER` both go the `letsencrypt-nginx-proxy-companion` container.

You are right, the doc is unclear.

**Comment by wendellm** [comment]
I had the same exact same question

**Comment by buchdag** [comment]
Fixed by #257
