### ISSUE TITLE
I got 404 when use www

### ISSUE THREAD

**Issue by AlexanderKozhevin** [JrCs/docker-letsencrypt-nginx-proxy-companion#255]
What kind of issue it could be?
I specified both www.domain.com and domain.com on .env file.
But still getting 404 for www

Registrator name config is correct.

**Comment by buchdag** [comment]
If you get a 404 the problem lies with nginx-proxy/docker-gen. The letsencrypt-companion only functions are to create / renew certificates, put them and the private key on the correct place with the correct name, and reload the nginx proxy on cert creation or renewal.
