### ISSUE TITLE
HTTP Authentication

### ISSUE THREAD

**Issue by kevindesousa** [JrCs/docker-letsencrypt-nginx-proxy-companion#259]
Hello,

It's possible to set up HTTP Authentication without nginx-proxy, like this setup : https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion ?

Thanks.

**Comment by buchdag** [comment]
Your link is a 404 and the original URL points to a repo that does not make any mention of HTTP Authentication.

**Comment by kevindesousa** [comment]
Sorry I fix the link.

**Comment by buchdag** [comment]
Are asking if HTTP authentication also works with the three container setup (nginx/docker-gen/letsencrypt-nginx-proxy-companion) ?

**Comment by kevindesousa** [comment]
Yes ! 0:)

**Comment by buchdag** [comment]
I've not tested this feature personally but yes, every configuration option for nginx-proxy should work wether you're using the standalone container or nginx + docker-gen, as long as you use [the latest nginx.tmpl](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl) with docker-gen.

Note that your question is not related to letsencrypt-nginx-proxy-companion, if you have further question about nginx-proxy it would be best to ask them [on the project's repository](https://github.com/jwilder/nginx-proxy/issues).
