### ISSUE TITLE
Adding a domain will not recreate the certificate

### ISSUE THREAD

**Issue by dominikkukacka** [JrCs/docker-letsencrypt-nginx-proxy-companion#260]
Adding a domain to a running container and recreating it (certs are in a volumen) will not recreate the certificate.
Is this a bug or known behaviour?

**Comment by buchdag** [comment]
Just tried it and it worked fine.

**Comment by dominikkukacka** [comment]
never worked for me but I noticed in the latest tag there is a script /app/force_renew (https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/app/force_renew) which I trigger after adding a domain. this workes for me :)

**Comment by buchdag** [comment]
`force_renew` has an issue and will only renew the domain(s) for the first container id found on the `letsencrypt_service_data` file, not all of them as it should.

#270 will fix this when merged, before that you can manually patch it by removing the ` && shift` on [line 73 of `letsencrypt_service` ](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/app/letsencrypt_service#L73) if you need complete forced renewal.
