### ISSUE TITLE
Support for certificate transparency

### ISSUE THREAD

**Issue by mhilaire** [JrCs/docker-letsencrypt-nginx-proxy-companion#261]
Hi,
I'd like to know how can I enable certificate transparency with this image?
Thanks

**Comment by buchdag** [comment]
Hi. Unfortunately at the moment there is nothing in this container that will help you implement certificate transparency.

You'll need at least a custom built nginx with the nginx-ct module acting as the proxy, modification to the `nginx.tmpl` from nginx-proxy plus scripts to submit certificates to log servers as -if I'm correct (@cpu ?)- LE does not offer SCT and does not plan to in the near future.

more info here: https://www.certificate-transparency.org/resources-for-site-owners/nginx

**Comment by cpu** [comment]
100% of Let's Encrypt issued certificates are published in the certificate transparency ecosystem. If your request is to deliver the SCT as part of the Nginx TLS handshake then @buchdag's recommendation is correct - you'll need to handle this with your Nginx installation and the `nginx-ct` module. 

The alternative way to deliver an SCT proof to a client is to embed it into the certificate itself, which is where CA support is required, e.g. this would be a Let's Encrypt feature request and not something the docker-nginx-proxy-companion project can help with.

> LE does not offer SCT and does not plan to in the near future.

We don't presently embed SCTs into our certificates but we **do** plan to do so in the future. More [details are available here](https://github.com/letsencrypt/boulder/wiki/Embedded-SCT-plan). I believe all CAs will have to embed SCTs from 1 or more trusted logs for Chrome to consider the certificate valid sometime after April 2018 but I can't find the announcement of that policy decision handy.
