### ISSUE TITLE
Request IP Address Not Correct

### ISSUE THREAD

**Issue by k2xl** [JrCs/docker-letsencrypt-nginx-proxy-companion#262]
I have the nginx set to a local python wsgi app (falcon framework)
`request.remote_addr` is always the ip address of the container. How can I get the ip address forwarded correctly?

**Comment by buchdag** [comment]
You have to configure your backend web server serving your falcon app to use the nginx-proxy HTTP `X-Forwarded-For` header. Here is how to do it with apache: https://www.daveperrett.com/articles/2009/08/10/passing-ips-to-apache-with-nginx-proxy

This is completely unrelated to `docker-letsencrypt-nginx-proxy-companion`

**Comment by k2xl** [comment]
Yeah, I've tried that, and it is still the IP of the docker network interface.

**Comment by k2xl** [comment]
Hmm I'm wondering if it is related to this (actual) docker bug: https://github.com/moby/moby/issues/15086

**Comment by buchdag** [comment]
If you are using Docker on mac, it might be.

But again `docker-letsencrypt-nginx-proxy-companion` is unrelated to the actual proxying, it's just there to automate creation and renewal of certificates, and trigger reloads of nginx configuration on creation / renewal of those certificates. Nothing more.

**Comment by k2xl** [comment]
Super strange - doesn't make sense to me. How are apps supposed to log the users IP address with containers?

**Comment by k2xl** [comment]
If I wanted to get this letsencrypt nginx proxy to work with host networking, are there any steps I need to do? it doesn't seem like `network_mode: host` works

**Comment by buchdag** [comment]
How are you running your containers ? `docker run` or `docker-compose` ? Are you on mac ?

**Comment by k2xl** [comment]
`docker-compose` i'm on mac, but this is always happening on our linux instance.

**Comment by buchdag** [comment]
Is your instance reachable through IPv6 ?

**Comment by k2xl** [comment]
Not sure - it's a recently spun up EC2 instance

**Comment by k2xl** [comment]
I found a solution to get the IP address in my wsgi app!
`request.environ.get('HTTP_X_REAL_IP', request.remote_addr)`
