### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by Nardian** [JrCs/docker-letsencrypt-nginx-proxy-companion#27]
Hello,

I'm not quite sure if I should ask my questions here or in the nginx-proxy section, as the questions are related to both topics, and maybe also how certifications work in general.

Currently I've managed to setup the following:
* a container running jwilder/nginx-proxy
* a container running jrcs/letsencrypt-nginx-proxy-companion
* a container running a customized web-server (I think apache2). 

I own a domain, lets call it domain.com
My custom container is configured for sub.domain.com via VIRTUAL_HOST and LETSENCRYPT_HOST.
Everything is working, letsencrypt generates certificates, https is working, everything works fine. 

Here are the questions: 
a) Is it possible to use nginx-proxy itself to host a very minimalistic main site? I know, this is mainly a question for the other github-repository, but if it is possible, how do I have to configure / start the nginx-proxy that it gets a certificate for "domain.com", as I cannot set the VIRTUAL_HOST environment as else it would end up in an endless redirecting.
If possible I would like to prevent creating a new container only for this purpose.
b) Currently if I try to visit a non-existent-sub.domain.com, I get an error from my browser that the server only owns a certificate for sub.domain.com. I don't really know how to solve this. Wildcard-certificates (If yes, how to get one with jrcs/letsencrypt-nginx-proxy-companion and how do I have to configure the containers?)? Automatically redirect all unknown-sub.domain.com requests to a fallback site (e.g to a main-site on "domain.com")?

Thanks in advance

**Comment by JrCs** [comment]
For question
a), it think you can you the DEFAULT_HOST of nginx-proxy and/or add minimal site files in the /usr/share/html directory of the nginx-proxy.
b) you can't create wilcard certificates with letsencrypt. I think you can create a conf in conf.d to redirect a non existent site to another. But you need to check how to do that in the README.md of the nginx-proxy (see Proxy-wide and Per-VIRTUAL_HOST configuration)

**Comment by Nardian** [comment]
Thanks, got it working :)
