### ISSUE TITLE
Unable to verify: Unable to reach http://amankapoor.me/.well-known/acme-challenge/

### ISSUE THREAD

**Issue by amankapoor** [JrCs/docker-letsencrypt-nginx-proxy-companion#271]
Hey,

Below are the logs
```
Debugging tips: -v improves output verbosity. Help is available under --help.
Sleep for 3600s
2017/11/05 20:21:24 Received event die for container 2f82ed7595b0
2017/11/05 20:21:24 Received event stop for container 2f82ed7595b0
2017/11/05 20:21:39 Debounce minTimer fired
2017/11/05 20:21:39 Generated '/app/letsencrypt_service_data' from 1 containers
2017/11/05 20:21:39 Running '/app/update_certs'
Sleep for 3600s
2017/11/05 20:27:20 Received event start for container c673b7addb40
2017/11/05 20:27:20 Received event die for container c673b7addb40
2017/11/05 20:27:20 Received event start for container 569e379d1e58
2017/11/05 20:27:21 Received event die for container 569e379d1e58
2017/11/05 20:27:22 Received event start for container 7039252acf68
2017/11/05 20:27:37 Debounce minTimer fired
2017/11/05 20:27:37 Generated '/app/letsencrypt_service_data' from 2 containers
2017/11/05 20:27:37 Running '/app/update_certs'
Creating/renewal amankapoor.me certificates... (amankapoor.me)
2017-11-05 20:27:37,525:INFO:simp_le:1213: Generating new account key
2017-11-05 20:27:42,602:ERROR:acme.challenges:311: Unable to reach http://amankapoor.me/.well-known/acme-challenge/AuWKk8DDRFgqqKyL8EdrarI5nJo074uEZ_WFPT1J5AQ: HTTPConnectionPool(host='amankapoor.me', port=80): Max retries exceeded with url: /.well-known/acme-challenge/AuWKk8DDRFgqqKyL8EdrarI5nJo074uEZ_WFPT1J5AQ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f38bed38090>: Failed to establish a new connection: [Errno 111] Connection refused',))
2017-11-05 20:27:42,602:WARNING:simp_le:1304: amankapoor.me was not successfully self-verified. CA is likely to fail as well!
2017-11-05 20:27:42,913:INFO:simp_le:1314: Generating new certificate private key
2017-11-05 20:27:44,512:ERROR:simp_le:1272: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Is there a warning log entry about unsuccessful self-verification? Are all your domains accessible from the internet? Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/3lSkp7D0A8tgpYIx64-BAfuUlnc2S8D9sQ8-7FsWpP8
Challenge validation has failed, see error log.
```

My golang application is very basic, see this 
```
package main

import (
	"net/http"
)

func main() {
	r := http.NewServeMux()

	r.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("Hello Aman"))
	})

	http.ListenAndServe(":8080", r)
}
```

The associated Dockerfile is:
```
FROM golang:onbuild
LABEL Name=ws Version=0.0.1 
EXPOSE 8080
```

And the `docker-compose.yml`, looks like following:
```
version: '3'

services:
  ws:
    container_name: ws
    image: ws
    build: .
    environment:
      VIRTUAL_HOST: amankapoor.me
      LETSENCRYPT_HOST: amankapoor.me
      LETSENCRYPT_EMAIL: aman.sk95@gmail.com
      ACME_CA_URI: https://acme-staging.api.letsencrypt.org/directory
    expose:
      - "80"
      - "443"

networks:
  default:
    external:
      name: nginx-proxy

```

I have followed this link https://medium.com/@francoisromain/host-multiple-websites-with-https-inside-docker-containers-on-a-single-server-18467484ab95 as setup guide.

Where am I missing? What is the problem and what do I do to make it work?
Also, if you are familiar with Go, then could you please tell me if I need to use `http.ListenAndServeTLS`?
And, the ACME_CA_URI env var is for testing purpose right? So, when I need to push it for production, I will remove this env var.

Also FYI, I use AWS and Cloudflare, so I have put an A record of my site above with the public IP provided by AWS, in the DNS settings of Cloudflare.

**Comment by amankapoor** [comment]
Additionally, this is how `docker ps` looks,

```
/srv/www/vhost.d$ docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                             PORTS                                      NAMES
7039252acf68        ws                                       "go-wrapper run"         28 minutes ago      Up 28 minutes                      80/tcp, 443/tcp, 8080/tcp                  ws
9786bed0572b        jwilder/docker-gen                       "/usr/local/bin/do..."   2 hours ago         Restarting (1) About an hour ago                                              nginx-gen
e957ddb6c52f        jrcs/letsencrypt-nginx-proxy-companion   "/bin/bash /app/en..."   2 hours ago         Up 2 hours                                                                    nginx-letsencrypt
dce85311d0b6        nginx                                    "nginx -g 'daemon ..."   2 hours ago         Up 2 hours                         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx

```

`ws` is the simple go web app. And `docker-gen` remains closed, I don't know why, but it has been like this since the creation of these containers. And it restarted once, probably when `ws` container was created or doing something related to certificates.

**Comment by buchdag** [comment]
If docker-gen keep restarting something is misconfigured and the stack won't work. Most probable cause is you did not grab the nginx.tmpl template file from jwilder/nginx-proxy.

Try the [two containers setup](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#usage) with a compose file version 2 before going for the unnecessary complex (for a first try) three container setup on compose file version 3. If you need a starting point you can grab [this one](https://raw.githubusercontent.com/buchdag/letsencrypt-nginx-proxy-companion/master/docker-compose/2-containers/compose-v2/docker-compose.yaml) and replace `duch` with `jrcs`.

I know this repo's doc says the three container setup is recommended but truth is it's not.

Also your golang application container expose only port 8080 (on which something is listening) but your docker-compose file also expose ports 80 and 433 on which nothing is listening. When a proxyed container has multiple ports exposed including port 80, [nginx-proxy will default to port 80](https://github.com/jwilder/nginx-proxy#multiple-ports).

Remove this `expose:` directive from your app compose file or you app won't work even if the cert get generated.

**Comment by buchdag** [comment]
Oh and right now your domain appears to resolve to cloudflare, I have no idea if the le-companion container will work behind cloudflare.

**Comment by amankapoor** [comment]
Hey, thank you for your comments. I followed what you wrote above and I was able to generate a certificate for my site. But the problem is that I can't get Cloudflare to work with it when using it as DNS+HTTP Proxy. If I only set it as DNS, then it works fine.

Where can I learn more to make it work in sync with Cloudflare? Do we have any settings available to make any changes required for Cloudflare? Or, any trusted GitHub repo of the same? From what I have researched till now, there are ways to make it work with CF when using http-01 and dns-01 as challenges.

**Comment by amankapoor** [comment]
Strange observation:

You already know I was saying that my site doesn't run when with CF. But now if you see the ssl certificate on my site, you will find that its from Cloudflare. And how I got it working? My observation is, when I first got the LE certificate, Cloudflare DNS+HTTP Proxy (Orange Cloud) was on. As far as I remember, I did not change it and I got a certificate using your methods above. Then I observed that turning the cloud to grey (DNS only), resolved to my IP, showed LE cert and I could see the content. What I did just now, changed the grey cloud back to orange and my site's content is accessible and cert is of Cloudflare (COMODO). The SSL setting which I have is Full (strict) which mean, ssl between my origin (aws) server and cloudflare and between cloudflare and client is fully https, which is true. So, this way I got it working. The steps will be fully clear to me as I will be deploying more sites in the coming days. 

Btw, before closing this issue, I wish to have clarity on two more things:

1. I want certificates for all the subdomains that I will ever create in future, so this time I did LETSENCRYPT_HOST=amankapoor.me only, but should I be doing like this -> LETSENCRYPT_HOST=amankapoor.me, *.amankapoor.me 

2. And, regarding test certificates, this time I did not add LETSENCRYPT_TEST=true, but only ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory. So which type of certificate do I have now? A test certificate?

**Comment by buchdag** [comment]
1. Let's Encrypt does not support wildcard certificates yet : https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html

2. Yes, you'll get a test certificate too. What `LETSENCRYPT_TEST=true` does behind the scene is telling `simp_le` to use the staging api endpoint.
