### ISSUE TITLE
TOS hash mismatch

### ISSUE THREAD

**Issue by flexbrane** [JrCs/docker-letsencrypt-nginx-proxy-companion#278]
Hello,

I see the previous issue, from 2016 that seems to be resolved.

But I am facing the same problem, using the last Docker version (`17.10.0-ce, build f4ffd25`) and the last image `JrCs/docker-letsencrypt-nginx-proxy-companion`.

I want to generate a new certificate, but there is an error: `TOS hash mismatch. Found: cc88d8d9517f490191401e7b54e9ffd1a2b9082ec7a1d4cec6101f9f1647e7c`.

**Comment by cpu** [comment]
Hi @flexbrane - this is a duplicate of https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/277 - see the workaround & root cause identifier there.

**Comment by flexbrane** [comment]
Sorry, I didn't see this one. Thank you I'll see that.
