### ISSUE TITLE
Option to proxy HTTPS instead of HTTP?

### ISSUE THREAD

**Issue by cfriedtpv** [JrCs/docker-letsencrypt-nginx-proxy-companion#284]
It would seem that incoming HTTPS requests on port 443 are unconditionally proxied to their respective HTTP services on port 80.

I tried setting VIRTUAL_PORT to 443, but that did not work (400 Bad Request The plain HTTP request was sent to HTTPS port).

Is there a way to prevent this from happening and to just use a direct HTTPS<->HTTPS proxy?

From [what I've (briefly) read](https://stackoverflow.com/questions/516323/https-connections-over-proxy-servers), HTTPS<->HTTPS proxies are technically possible, and mounting the Let's Encrypt certificate directory read-only inside multiple containers is quite straight-forward.

However, there does not seem to be anything present in the documentation about how to use a straight HTTPS<->HTTPS proxy.

Some web applications are particularly sensetive to this and seem to not work unless HTTP is used. Particularly gitlab/gitlab-ce . As you can probably imagine, I would like to avoid using plain HTTP for transmitting sensitive information, even within the proxy network. In fact, the world would likely be a much better place if everyone just used HTTPS even within their proxies... but that is another issue.

**Comment by ajoergensen** [comment]
Does https://github.com/jwilder/nginx-proxy#ssl-backends work?

**Comment by cfriedt** [comment]
Yes! I believe it probably does. I didn't see that configuration page, so thank you for pointing it out :-)

**Comment by grahamcolgate** [comment]
Hi, I've been trying to get this to work too.

If you set the VIRTUAL_PORT to 443 you get the error as mentioned by @cfriedtpv so in addition to this you also need to do the following (not really a suitable workaround or fix but illustrates its possible and should be simple to fix.

I found that if you go the volume where the nginx proxy config is located, in my case I have a specified volume in my docker-compose.yml
`./volume_data/conf.d:/etc/nginx/conf.d`

 and edit the default.conf file

simply changing the line from
`proxy_pass http://example.com;`
to
`proxy_pass https://example.com;`

Note the additions of the 's' to http**s** which then enabled the ssl to work to the backend server (end to end encryption :)

The http**s** lets nginx know that its should encrypt the payload again.

this is obviously not a suitable work around as the config gets overwritten each time you need to restart your service etc

how do we add a feature request for this or does someone now how to sort this and pull request?

**Comment by grahamcolgate** [comment]
Hi

So after some more looking around, there is actually a proper supported solution.

( I am assuming that you are using the docker container -> [jwilder/docker-gen](https://github.com/jwilder/docker-gen) )

If so, in addition to adding VIRTUAL_PORT you also need to add VIRTUAL_PROTO=https (or in compose file VIRTUAL_PROTO: https )

check the readme in the link above.

Hope this helps and thanks @cfriedtpv for your question and getting me on the path to a solution.

**Comment by cfriedt** [comment]
I did get it working after some time. Thanks!
