### ISSUE TITLE
How to set nginx server location 

### ISSUE THREAD

**Issue by m4teh** [JrCs/docker-letsencrypt-nginx-proxy-companion#286]
I'm not sure if I'm missing something or whether I'm just completely inexperienced

I'm wanting to run something proxied at https://subdomain.domain.com/app - normally this is via specifying "location /xyz" in nginx confugration.

Is this supported with the docker lets encrypt stack?

**Comment by buchdag** [comment]
hi @m4teh 

Unfortunately that's currently not supported by `nginx-proxy` and it does no appear that it will be in the foreseeable future: https://github.com/jwilder/nginx-proxy/pull/254

**Comment by m4teh** [comment]
Wow that's surprising. I thought I was overlooking something majorly. Nothing I was trying was working. 

Thanks for advising. I'm a little shocked something seemingly so straight forward/common isn't a feature!
