### ISSUE TITLE
OpenSSL error Diffie-Hellman

### ISSUE THREAD

**Issue by osteenbergen** [JrCs/docker-letsencrypt-nginx-proxy-companion#29]
When running the letsecnrypt container in separate containers I received this error:

```
# docker logs -f proxy-letsencrypt 
Creating Diffie-Hellman group (can take several minutes...)
/app/entrypoint.sh: line 59:    17 Terminated              openssl dhparam -out /etc/nginx/certs/.dhparam.pem.tmp 2048 2> /dev/null
mv: can't rename '/etc/nginx/certs/.dhparam.pem.tmp': No such file or directory
```

Might be due to lack of randomness, but the error is written to ```/dev/null``` so could not debug it. Starting the container again fixed the issue. Would suggest adding a warning that it can take a few minutes in the readme. 

Failure of the letsencrypt container also kills the docker-gen container for some reason. Nginx continues running without any problem.

**Comment by JrCs** [comment]
Images and readme was updated. Thanks.
