### ISSUE TITLE
/.well-known/acme-challenge/ with reverse proxy, basic auth and docker

### ISSUE THREAD

**Issue by pir1981** [JrCs/docker-letsencrypt-nginx-proxy-companion#290]
Hi,
I have a reverse proxy (https://github.com/jwilder/nginx-proxy) with separate containers. 
Behind the proxy is a web server and a few monitoring/logging containers that are only reachable through basic auth. 

Everything was running fine till yesterday, when I started getting:

```
alertmanager.mydomain.com someip - - [28/Nov/2017:08:44:14 +0000] "GET /.well-known/acme-challenge/cEunwMkby6GM7gkW6dhwUEHNoIj4prPghIA0liEHMpw HTTP/1.1" 503 213 "-" "python-requests/2.18.4"
alertmanager.mydomain.com someip  - - [28/Nov/2017:08:44:15 +0000] "GET /.well-known/acme-challenge/cEunwMkby6GM7gkW6dhwUEHNoIj4prPghIA0liEHMpw HTTP/1.1" 503 213 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
cadvisormaster.mydomain.com someip  - - [28/Nov/2017:08:44:21 +0000] "GET /.well-known/acme-challenge/VbnS3q1GjIEXx-p52DDSxxcXhUVNLf8DHxkj04xpiE8 HTTP/1.1" 503 213 "-" "python-requests/2.18.4"
cadvisormaster.mydomain.com someip  - - [28/Nov/2017:08:44:22 +0000] "GET /.well-known/acme-challenge/VbnS3q1GjIEXx-p52DDSxxcXhUVNLf8DHxkj04xpiE8 HTTP/1.1" 503 213 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
grafana.mydomain.com someip  - - [28/Nov/2017:08:44:24 +0000] "GET /.well-known/acme-challenge/bBHzLhDLpByDpycH3a97fFvdjHBCDVxQRla_IC9yx9Y HTTP/1.1" 503 213 "-" "python-requests/2.18.4"
grafana.mydomain.com someip  - - [28/Nov/2017:08:44:24 +0000] "GET /.well-known/acme-challenge/bBHzLhDLpByDpycH3a97fFvdjHBCDVxQRla_IC9yx9Y HTTP/1.1" 503 213 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
kibana.mydomain.com someip  - - [28/Nov/2017:08:44:27 +0000] "GET /.well-known/acme-challenge/-IqcxhyGxjjHm2lhaTr5zjm5EWUL0NONQWIq9LO5LDg HTTP/1.1" 503 213 "-" "python-requests/2.18.4"
kibana.mydomain.com someip  - - [28/Nov/2017:08:44:27 +0000] "GET /.well-known/acme-challenge/-IqcxhyGxjjHm2lhaTr5zjm5EWUL0NONQWIq9LO5LDg HTTP/1.1" 503 213 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
prometheus.mydomain.com someip  - - [28/Nov/2017:08:44:30 +0000] "GET /.well-known/acme-challenge/HEFBdFfF_PbtVSbX9fKk_fGAMMn-VPtrIceMy9LfHBM HTTP/1.1" 503 213 "-" "python-requests/2.18.4"
prometheus.mydomain.com someip  - - [28/Nov/2017:08:44:31 +0000] "GET /.well-known/acme-challenge/HEFBdFfF_PbtVSbX9fKk_fGAMMn-VPtrIceMy9LfHBM HTTP/1.1" 503 213 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
```

I have now read a few posts and restarted everything, pulled the latest docker-letsencrypt-nginx-proxy-companion, checked my docker-compose

i.e. websever
```
expose:
    - 80
environment:
    VIRTUAL_HOST=mydomain.com,www.mydomain.com
    LETSENCRYPT_HOST=mydomain.com,www.mydomain.com

```
i.e. cadvisor
```
expose:
  - 8080
environment:
      - VIRTUAL_HOST=cadvisormaster.mydomain.com
      - LETSENCRYPT_HOST=cadvisormaster.mydomain.com
      - LETSENCRYPT_EMAIL=someone@mydomain.com
      - LETSENCRYPT_TEST=false
      - HTTPS_METHOD=nohttp
```

I have not yet deleted the certificates, to fetch them again, as I would like to avoid this interference in the future.

after pulling the newest docker image I now get on an hourly basis

`2017-11-28T12:18:17.849Z -- mydomain-- reverseproxyssl_letsencrypt_1 -- ERROR -- 2017-11-28 12:18:17,849:ERROR:simp_le:1421: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If you haven't setup correct CAA fields or if your DNS provider does not support CAA, validation attempts after september 8, 2017 will fail.  Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/Ia3qYHV6DFP0ZYOl0NA2ji49nOX1vhLCsFabkYG-q6U`

I have only A entries set up

and the access.log states 

```
alertmanager.mydomain.com someip   - - [28/Nov/2017:12:18:16 +0000] "GET /.well-known/acme-challenge/a903jtIQaX6KoUJB-l5dWuk2xmTmtxRDYGe4iVLeVl8 HTTP/1.1" 503 213 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
cadvisormaster.mydomain.com  someip  - - [28/Nov/2017:12:18:20 +0000] "GET /.well-known/acme-challenge/SV_TyH3-VUI39b34qG6hRdVMMoR-RTRBnjB6omARdlE HTTP/1.1" 503 213 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
grafana.mydomain.com someip  - - [28/Nov/2017:12:18:24 +0000] "GET /.well-known/acme-challenge/J87ui-d-UVXw0PyLdIDEKGGCX9BRk5uFEdMew8yFf6A HTTP/1.1" 503 213 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
kibana.mydomain.com someip   - - [28/Nov/2017:12:18:27 +0000] "GET /.well-known/acme-challenge/mDXC9DpsXNa03YeNEA3_Y6Qezdsr2HvliC_p3Qi-bHM HTTP/1.1" 503 213 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
prometheus.mydomain.com someip   - - [28/Nov/2017:12:18:31 +0000] "GET /.well-known/acme-challenge/VwHaKH0nXMdBdemDOwzPL4RHKFIPovNsqVnh-9bbX_M HTTP/1.1" 503 213 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
```

what am I missing?

**Comment by buchdag** [comment]
Hi. The only thing I can tell from your logs is that the LE validation server are getting a 503 when they try to get the challenge file. Is your `nginx` container working ok ?

**Comment by pir1981** [comment]
Both servers, reverse-proxy-nginx and web-nginx (app server - which is not behind basic auth) are reachable. I can also log into all the alertmanages/cadvisor .... without any issues (using basic auth).
So everything is running.

Any ideas what I should/could look at?

**Comment by buchdag** [comment]
I did not catch the `HTTPS_METHOD=nohttp` on cadvisor.

That won't work, see https://github.com/jwilder/nginx-proxy/issues/471

**Comment by pir1981** [comment]
I was actually just un-commenting exactly that to see if that was the issue. will close, if that resolves it. will know in an hour :)

**Comment by buchdag** [comment]
You can trigger a forced certificate renewal (of all certificates) with:

`docker exec yourLEcontainername /app/force_renew`.

**Comment by pir1981** [comment]
deleting HTTPS_METHOD=nohttp did the trick, thanks
