### ISSUE TITLE
Allow one account key for all registrations.

### ISSUE THREAD

**Issue by almereyda** [JrCs/docker-letsencrypt-nginx-proxy-companion#291]
Recently we ran into the rate limit for registrations per IP address.

- https://letsencrypt.org/docs/rate-limits/

Alternatively, it shall be possible to configure a single account key for all issuances.

- https://letsencrypt.org/docs/integration-guide/

How would such a setting require changes to the current companion?

**Comment by buchdag** [comment]
I've already got this feature covered, I'll try to merge it in `dev` this week end.

**Comment by buchdag** [comment]
A first version of the feature has been commited to `dev` : 4334d1593e841c8a16b013e565980351d1d25d57.

It's closely inspired by the way `certbot` handle account keys. [You can check the doc](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/tree/dev#acme-account-keys) and try it now by pulling and using `jrcs/letsencrypt-nginx-proxy-companion:dev`.

**Note:** if you use the `dev` version with an existing certificates volume/dir, on the next certificate(s) renewal it will replace corresponding account keys with a symlink to

`/etc/nginx/certs/accounts/acme-v01.api.letsencrypt.org/directory/default.json`

This new file will be copied from the account key of the first renewed certificate.

This will in turn cause a re-validation of all the other domains to the new common ACME account when their certificates are due for renewal. So be sure that your `nginx-proxy` stack is working properly and that you have no issues wit LE domain validation before using `jrcs/letsencrypt-nginx-proxy-companion:dev`, and backup you certificates volume.

You can also disable the feature entirely by setting the `REUSE_ACCOUNT_KEYS` to `false` on the letsencrypt container. This will make the container behave as it does currently in `master` (create a new ACME account for almost every new domain).

The automatic switch to a common ACME account key on renewal has been tested with success on two separate hosts running different services.

I pondered about having the whole feature be opt-in or opt-out, IMHO the current behaviour is generating enough issues on its own for this to be opt-out.

**Comment by JrCs** [comment]
LGTM

**Comment by buchdag** [comment]
Merged in master as of #298
