### ISSUE TITLE
LetsEncrypt error: could not access http://example.com/.well-known/acme-challenge/X

### ISSUE THREAD

**Issue by ToniSoftware** [JrCs/docker-letsencrypt-nginx-proxy-companion#296]
Hey everyone,
i'm trying for 2 days to get this working on my fresh installed Server.
I used the recommended steps with seperate containers. I tried remove and add the containers new several times, but that didn't work.. 
so this is a quote from docker logs nginx-letsencrypt

> CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If you haven't setup correct CAA fields or if your DNS provider does not support CAA, validation attempts after september 8, 2017 will fail.  Failing authorizations: https://acme-staging.api.letsencrypt.org/acme/authz/P_guAGIS0n_fIVPMW54ELG0yVH0We36rKsZDIaUYnAA

This happens when i add a test container for nginx. With http it works, but how you can see i can't get anything to work with https..
Thats my test container for nginx with letsencrypt:

> docker run -d \
    --name nginx-test \
    -v /srv/nginx-test:/usr/share/nginx/html:ro \
    -e "VIRTUAL_HOST=asdf.domain.de" \
    -e "LETSENCRYPT_HOST=asdf.domain.de" \
    -e "LETSENCRYPT_EMAIL=email@email.de" \
    -e "LETSENCRYPT_TEST=true" \
    --network=web \
    nginx

And just for completeness the whole process:

> docker network create web

> docker run -d -p 80:80 -p 443:443 \
  --name nginx-proxy \
  -v /etc/nginx/conf.d  \
  -v /etc/nginx/vhost.d \
  -v /usr/share/nginx/html \
  -v /srv/nginx/certs:/etc/nginx/certs:ro \
  --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy \
  --network=web\
  nginx

> curl https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl > /etc/docker-gen/templates/nginx.tmpl

> docker run -d \
  --name nginx-controller \
  --volumes-from nginx-proxy \
  -v /srv/docker-gen/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro \
  -v /var/run/docker.sock:/tmp/docker.sock:ro \
  --label com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen \
  --network=web \
  jwilder/docker-gen \
  -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

> docker run -d \
  --name nginx-letsencrypt \
  --volumes-from nginx-proxy \
  -v /srv/nginx/certs:/etc/nginx/certs:rw \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -e NGINX_DOCKER_GEN_CONTAINER=nginx-controller \
  -e NGINX_PROXY_CONTAINER=nginx-proxy \
  --network=web \
  jrcs/letsencrypt-nginx-proxy-companion

I hope someone can help me out.. I'm getting really desperate because I don't have any idea what to do..
Thanks in advance

**Comment by buchdag** [comment]
Can you try again with the [two containers setup](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#usage) rather than the three container setup ?

**Comment by ToniSoftware** [comment]
@buchdag Well that shouldn't fix the problem, because it's just a problem with the let's encrypt part.. but I'll give it another try^^ I think I already tried it and it didn't fix the problem but..
