### ISSUE TITLE
HTTPS client certificates and LetsEncrypt

### ISSUE THREAD

**Issue by alexharrington** [JrCs/docker-letsencrypt-nginx-proxy-companion#299]
I'm using nginx-proxy and your LetsEncrypt wrapper to secure some sites which also use client-side certificates to validate that the users browser is authorised to access the website.

This works really well until the LE certificate expires.

Looking at what's happening, it seems the request from LE for `/.well-known` gets caught by the HTTPS redirect rule (which is the default if you turn HTTPS on for that container), and then fails as LE don't have one of our client certificates.

Could  a change me made so that the incomming HTTP request for `/.well-known` is served over HTTP and not redirected to HTTPS, and therefore failing the renewal?

**Comment by buchdag** [comment]
Maybe with `HTTPS_METHOD=noredirect` ?

https://github.com/jwilder/nginx-proxy#how-ssl-support-works

> To serve traffic in both SSL and non-SSL modes without redirecting to SSL, you can include the environment variable `HTTPS_METHOD=noredirect` (the default is `HTTPS_METHOD=redirect`).  `HTTPS_METHOD` must be specified on each container for which you want to override the default behavior. If `HTTPS_METHOD=noredirect` is used, Strict Transport Security (HSTS) is disabled to prevent HTTPS users from being redirected by the client. If you cannot get to the HTTP site after changing this setting, your browser has probably cached the HSTS policy and is automatically redirecting you back to HTTPS. You will need to clear your browser's HSTS cache or use an incognito window / different browser.

**Comment by alexharrington** [comment]
I want it to redirect in normal operation. It's just the acme challenge
that should not be redirected to HTTPS.

**Comment by buchdag** [comment]
That can't be done solely from this project's side as it depends on an `nginx.tmpl` modification, but nothin prevents you from using a modified `nginx.tmpl` if needed.

I gave it a shot [there](https://gist.github.com/buchdag/5132a8ea962f1d07323b848fb47e6946). Changes are from line 196 to 207. 

Test using this template seems ok, `/.well-known/acme-challenge` isn't redirect to https but everything else is. If you test with a browser you already used to navigate to one of your site, HSTS will force it to use https but [Let's Encrypt ignore HSTS for HTTP-01 validation](https://community.letsencrypt.org/t/hsts-and-lets-encrypt/38257/5).

The method for clearing the HSTS settings depends on you browser. I prefer to use TorBrowser for that kind of test as it clears most of its config when you request a new identity.

**Comment by alexharrington** [comment]
Thank you very much. That appears to work brilliantly. Worth me reporting to the nginx-proxy project? Only I presumed they would say it was an implementation detail of Lets Encrypt and not generally useful.

**Comment by buchdag** [comment]
I think you presume correctly, this is probably too specific to LE or to this project to get merged in the upstream `nginx.tmpl`.

Maybe we should have a separate doc on this repo that covers modifying the template for stuff like this.

**Comment by codekitchen** [comment]
Thanks for this, I was just dealing with the same issue. I ended up applying the changes to nginx.tmpl [in the form of a patch file](https://gist.github.com/codekitchen/2c519eb7572002afab6a5f979cd42913) so that hopefully tracking nginx-proxy container changes will be a bit easier. But I wonder if nginx-proxy would accept a change to support custom include files in the redirect `server {}` block, like they currently do for the other server blocks.
