### ISSUE TITLE
Docker Version Dependent

### ISSUE THREAD

**Issue by atomaka** [JrCs/docker-letsencrypt-nginx-proxy-companion#3]
While running Docker 1.7.1 I received the following error:

```
/app/entrypoint.sh: line 36: NGINX_PROXY_CID: unbound variable
```

After upgrading to 1.9.1, this was resolved.  I didn't do any research, but it might be worthwhile to note version issues in the README since `jwilder/nginx-proxy` does support 1.7.1.

**Comment by jacobtomlinson** [comment]
Same for me, updating docker fixed.

**Comment by JrCs** [comment]
Yes currently this container only work with docker 1.9.1.
I'm working on a version that will work on all docker version

**Comment by JrCs** [comment]
Done by 6f731e4716df67d5f0138f39d7d0c756145d4ae4
