### ISSUE TITLE
Disable a host when no valid certificate is available?

### ISSUE THREAD

**Issue by s2929346** [JrCs/docker-letsencrypt-nginx-proxy-companion#301]
Hi,

I stumbled yesterday on the `5 certificates per week`-limit. No big deal, it was on a development platform. However, I noticed that the host was still available on port 80.

Is it somehow possible to disable a host completely when no certificate is available, for whatever reason?

My initial thought was just to not map port 80 to the host, but that would probably break the let's encrypt process?

Any ideas?

Thanks guys!

**Comment by buchdag** [comment]
That should not be too difficult with a modified version of `nginx.tmpl`.

I think deleting from [line 296](https://github.com/jwilder/nginx-proxy/blob/73f29846b3d58631e7cb3b6cb4a2a8aa2432607b/nginx.tmpl#L296) to [line 355](https://github.com/jwilder/nginx-proxy/blob/73f29846b3d58631e7cb3b6cb4a2a8aa2432607b/nginx.tmpl#L355) included will get you pretty close.

**Comment by buchdag** [comment]
No answers from issue creator for more than three months, closing.
