### ISSUE TITLE
Support for supplying ownership information

### ISSUE THREAD

**Issue by dscottboggs** [JrCs/docker-letsencrypt-nginx-proxy-companion#303]
When I visit my sites that are secured with this (awesome) container, and view the certificate information in Firefox, it says

  **Owner:  This website does not supply ownership information.**

Is there any way that we could set up a LETSENCRYPT_OWNER environment variable to be able to set, so that this field isn't simply left blank? If this feature already exists, could we include a brief entry about it in the README file?

**Comment by buchdag** [comment]
Hi,

Providing ownership information requires either an OV (organization validated) or EV (extended validation) certificate.

Those two type of certificates are obtained through a manual validation process, you have to prove that you are the organization you claim to be, and not just prove that you own a certain domain or set of domains. So Let's Encrypt aim being to provide free certificates in an automated way, they only issue DV (domain validated) certificates.

https://community.letsencrypt.org/t/adding-ownership-information/20174
