### ISSUE TITLE
Reverse proxy docker with lxc container on proxmox

### ISSUE THREAD

**Issue by lilp69** [JrCs/docker-letsencrypt-nginx-proxy-companion#304]
Hi,
I need a reverse proxy for my lxc proxmox container.
I install Docker on a VM, and I thinking about use your Docker for making my reverse proxy.
But I see it's works for Dockes only?
Because the part : Then start any containers you want proxied with a env var VIRTUAL_HOST=subdomain.youdomain.com
I can do it on lxc proxmox container.

Do you know if it's available with lxc proxmox container?

Thks

**Comment by buchdag** [comment]
Hi.

The reverse proxy is in fact another project : https://github.com/jwilder/nginx-proxy

This project (JrCs/docker-letsencrypt-nginx-proxy-companion) "only" functions are to enable the automatic creation of certificates, to put them in the right place with the right name so they can be used by nginx-proxy and to reload the proxy when needed.
