### ISSUE TITLE
Issue on ECS

### ISSUE THREAD

**Issue by tradziej** [JrCs/docker-letsencrypt-nginx-proxy-companion#308]
`docker-letsencrypt-nginx-proxy-companion` is failing on my AWS ECS cluster with `Error: can't get my container ID !`

It is failing on cluster with agent version `1.16.0` (I have other one with `1.15.0` and it is working there).

This is strange because if i run `cat /proc/self/cgroup | sed -nE 's/^.+docker[\/-]([a-f0-9]{64}).*/\1/p' | head -n 1` from `docker run -it --entrypoint=/bin/bash jrcs/letsencrypt-nginx-proxy-companion:latest` it is working.

How to fix it?

**Comment by buchdag** [comment]
@tradziej please take a look at this pending pull request: #300

**Comment by buchdag** [comment]
Closed by #300
