### ISSUE TITLE
Add an ENV variable to adjust the RSA key bit-length (2048 (default), 4096, ...)

### ISSUE THREAD

**Issue by gabrielsanterre** [JrCs/docker-letsencrypt-nginx-proxy-companion#31]
```cmd
$ docker run -d \
    -e RSA_KEY_BIT_LENGTH=4096 \
    -v /path/to/certs:/etc/nginx/certs:rw \
    --volumes-from nginx-proxy \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    jrcs/letsencrypt-nginx-proxy-companion
```
or
```cmd
$ docker run -d \
    -e VIRTUAL_HOST="foo.bar.com,bar.com" \
    -e LETSENCRYPT_RSA_KEY_BIT_LENGTH=4096 \
    -e LETSENCRYPT_HOST="foo.bar.com,bar.com" \
    -e LETSENCRYPT_EMAIL="foo@bar.com" ...
```

**Comment by JrCs** [comment]
The RSA key is already a 4096 bit-length by default.
Use a service like [Qualsys SSL Server Test/](https://www.ssllabs.com/ssltest/) to list parameters of the generated certificates.

**Comment by aphillipo** [comment]
Just a comment to say 4096 bit keys take out 10x longer to process (and possibly more, depending on the mobile device, hardware acceleration, even the kernel) - and they add zero value compared to 2048 bit keys for now at least.

LETSENCRYPT_KEYSIZE=2048 if SSL stuff is taking a large percentage of your load time.
