### ISSUE TITLE
Too much logs to stderr

### ISSUE THREAD

**Issue by paulusd** [JrCs/docker-letsencrypt-nginx-proxy-companion#310]
Following log ist written to STDERR.
`2017-12-26 03:53:43,170:INFO:simp_le:1534: Certificates already exist and renewal is not necessary, exiting with status code 1. `

Is it possible to write logs like this to STDOUT?

**Comment by buchdag** [comment]
Hi. The program writing to STDERR inside the container is `simp_le`, which is a different project. Could you open an issue there ? https://github.com/zenhack/simp_le

**Comment by paulusd** [comment]
Thank you for your reply
I have created an issue.
https://github.com/zenhack/simp_le/issues/97
