### ISSUE TITLE
New account key reuse creates broken link for account_key.json (simple fix)

### ISSUE THREAD

**Issue by fspc** [JrCs/docker-letsencrypt-nginx-proxy-companion#311]
After updating to the most recent release with the new account key reuse feature, I observed that the new link for account_key.json is broken:

current symbolic link: `account_key.json -> /etc/nginx/certs/accounts/acme-v01.api.letsencrypt.org/directory/default.json`

This issue is easily resolved by changing line 133 in app/letsencrypt_service from an absolute path:

`account_key_dir="/etc/nginx/certs/accounts/${acme_ca_uri#*://}"`

to a relative path:

`account_key_dir="../accounts/${acme_ca_uri#*://}"`

corrected symbolic link: `account_key.json -> ../accounts/acme-v01.api.letsencrypt.org/directory/default.json`

**Comment by buchdag** [comment]
What do you mean by "broken" ? Did you have an issue related to the fact that the symlink point to an absolute path rather than a relative one ?

I agree that the symlink should be relative though, do you want to submit a PR ?

**Comment by fspc** [comment]
O.k., I see what is causing the issue, I was viewing the link from a volume mounted on the host system so it appeared broken, but within the nginx-proxy container, an absolute path does properly link.  That being said, it would avoid future portability issues if the certificate location ever changed for some reason  if the link was relative. 

I will submit a PR.
