### ISSUE TITLE
Documentation for VIRTUAL_PORT more visible

### ISSUE THREAD

**Issue by cdrage** [JrCs/docker-letsencrypt-nginx-proxy-companion#318]
Spent a few hours reconfiguring another container (to use 80 as expose) when I just realized I could of simply passed in VIRTUAL_PORT to the container...

We should have some documentation that VIRTUAL_PORT can also be supplied.

**Comment by buchdag** [comment]
Hi @cdrage 

I understand the issue but I'm afraid that adding documentation from nginx-proxy in the README might turn out to be a slippery slope toward more and more people thinking this project _is_ nginx-proxy and opening issues that don't belong here.

I'm not really happy with the doc as it is and any modification that would clarify the fact that additional knowledge of the [nginx-proxy doc](https://github.com/jwilder/nginx-proxy/blob/master/README.md) is also required to use this project would be welcome (I'm not a native english speaker so doc related stuff take huge amounts of time for me).

On the other hand I started a Wiki for this project, and that might be the right place for something like _"nginx-proxy docs relevant to this project"_ (this is a bad name but I think you'll get what I mean). Again help from people more fluent in english than me is welcome.

**Comment by cdrage** [comment]
@buchdag Mind assigning this issue to me? I totally don't mind updating the README / Wiki a little bit :) I've done this on similar projects (see my GitHub).

Thanks and I appreciate the long reply!

**Comment by buchdag** [comment]
I think the recent work on the Wiki took care of this issue:

https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Basic-usage#step-3---proxyed-containers

Contributions to the Wiki are still welcome.
