### ISSUE TITLE
Wildcard Certificate

### ISSUE THREAD

**Issue by PixiBixi** [JrCs/docker-letsencrypt-nginx-proxy-companion#320]
Hi,

As you must know, Lets Encrypt will provide wildcard certificates from February, 27th. (It will requires DNS validation)

Does someone know if there's any ETA for when certifcates will be supported (If it will?)

More info: https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html

**Comment by buchdag** [comment]
Duplicate of #319
