### ISSUE TITLE
simp_le is failing to get to the acme url

### ISSUE THREAD

**Issue by dmanser92** [JrCs/docker-letsencrypt-nginx-proxy-companion#323]
I am trying for hours to get this to work with separate containers.
Everything seems okay, configuration gets created, but the Certificate is not created:

I tested it manually, it gives me the same errors:

> bash-4.4# bash /app/start.sh -v
/etc/nginx/certs/example.ch /app
Reloading nginx docker-gen (using separate container 5f819c4de1ce034c11c87d34199dff50ac26c2a1ad5e1c460cef29d1d1650d7e)...
Reloading nginx (using separate container 30cc532fc6d7a86381e10a2b175d9a7e872399ff1500541254916cea17b06f4f)...
Creating/renewal example.ch certificates... (example.ch)
2018/01/29 13:29:51 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
2018/01/29 13:29:51 Watching docker events
2018/01/29 13:29:51 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
2018-01-29 13:29:51,652:INFO:simp_le:1538: Retrieving Let's Encrypt latest Terms of Service.
('Connection to %s failed.', 'https://acme-v01.api.letsencrypt.org/directory')
Debugging tips: -v improves output verbosity. Help is available under --help.
/app
Sleep for 3600s

I'm getting the exact same error in the log when I add a container with the right labels. Tried it with stack and with docker run commands.

So my guess was that it has something to do with my proxy settings. The https_proxy and http_proxy variables are set in the container and curl gets the content from the url above (wget in alpine for some reason doesn't), but still it won't work.

Any ideas what could be the cause of this problem? Also, if there already is a wildcard certificat covering my chosen URL, could this be a problem?

Thanks for your help

**Comment by dmanser92** [comment]
I should maybe also state that I needed to define the http_proxy and https_proxy variable and install a proxy certificate in alpine to get curl to work. Maybe simp_le isn't using the cert?

**Comment by buchdag** [comment]
Hi, can you try with `jrcs/letsencrypt-nginx-proxy-companion:dev` ?

**Comment by dmanser92** [comment]
Cool, now I have an error. Do you know what I have to do? (I suppose it's because of the proxy)
SSLError: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))

**Comment by buchdag** [comment]
Obviously `simp_le` is unable to reach the letsencrypt api endpoint. I have zero experience with running python apps with http proxys, so I don't really know what's going wrong here.

**Comment by dmanser92** [comment]
hmm me neither, but I will keep trying to resolve this. Maybe there's a way to globally set the verification to false in python or to properly install the certs so that python uses these

**Comment by dmanser92** [comment]
Did you start Docker with IPv6? I restarted Docker with IPv6 support but still get the same error.
Would that mean that the whole environment must only use IPv6 from DNS->Firewall->Proxy->Docker for these requests?

**Comment by buchdag** [comment]
@andre-dierker what you describe is Let's Encrypt servers being unable to reach the host.

@dmanser92 issue is the other way around, `simp_le` running inside the container on the host can't reach the Let's Encrypt API endpoint.

**Comment by andre-dierker** [comment]
@buchdag yes, I commented the wrong issue. Sorry for that.

**Comment by russiano** [comment]
Have the same issue, `jrcs/letsencrypt-nginx-proxy-companion:v1.6` works fine.

https://github.com/certbot/certbot/issues/4933

**Comment by buchdag** [comment]
@russiano I don't think it's linked to requests or urllib3 versions as stated in the certbot issue, they're the same in `v1.6`, `v1.7`, `latest` and `dev`: requests-2.18.4 and urllib3-1.22

`simp_le` version is also the same across `v1.6`, `v1.7` and `latest`.

Could you try building a letsencrypt-nginx-proxy-companion image with the current Dockerfile but with `alpine:3.6` instead of `alpine:3.7` ? I don't have a proxy myself so I can't really test this.

**Comment by dmanser92** [comment]
We found the problem!

In http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification, we found the info how python handles trusted CA's. Because it isn't specified in the code itself that it should use the ca-certificate-File, we had to do it with an environment variable:

> This list of trusted CAs can also be specified through the REQUESTS_CA_BUNDLE environment variable.

So we just added this environment Variable to the compose-file with the path to the ca-certificate File
