### ISSUE TITLE
Multiple sites, nginx-proxy and php-fpm containers

### ISSUE THREAD

**Issue by perarg** [JrCs/docker-letsencrypt-nginx-proxy-companion#326]
Hello, i have setup a jwilder/nginx-proxy container for a multi domain environment. In my host i have a folder called sites and every domain has its own folder there. So i have a structure like this:
```
~/sites
  - example.com
    - html
  - example2.com
    - html
  - example3.com
    - html
etc.
```
In my nginx-proxy container, i have setup a volume so my site's folder is attached to /var/www in nginx-alpine image.
For each one website, i use a php-fpm container and for example a part of the docker-compose.yml for domain example.com is the following

```
...
environment:
      - VIRTUAL_HOST=example.com
      - VIRTUAL_ROOT=/var/www/example.com/html
      - VIRTUAL_PORT=9000
      - VIRTUAL_PROTO=fastcgi
      - LETSENCRYPT_EMAIL=myEmail@gmail.com
      - LETSENCRYPT_HOST=example.com
```

So far, so good. Everything is working.

And now comes the letsencrypt part :). I need for some domains to use SSL Certificate.
Do i have to run a different container each time i need a certificate? My issue is about the /usr/share/nginx/html path for writing the .well-known folder ? I have different folder for every website. As i noticed the JrCs/docker-letsencrypt-nginx-proxy-companion container renews every existing certificate when is running, so i think it would be a bad idea to have multiple containers...

In my experiments just for one site, i checked that the .well-known folder is not created into my html subfolder. The *.cert files are not created too (should be placed at certs' folder ?)

I think i am missing something. Could you please enlighten me ?

**Comment by Archcry** [comment]
> And now comes the letsencrypt part :). I need for some domains to use SSL Certificate.
Do i have to run a different container each time i need a certificate?
The whole idea of using docker is to distribute your application as a container, this means that each container has its own webserver. So yes, you'll be deploying every website in a different container. This should not cause a lot of overhead though.

**Comment by buchdag** [comment]
Closing in favor of the more complete discussion in https://github.com/jwilder/nginx-proxy/issues/1052
