### ISSUE TITLE
NGINX proxy on antoher port then 80

### ISSUE THREAD

**Issue by nofear87** [JrCs/docker-letsencrypt-nginx-proxy-companion#327]
I have running the nginx proxy under port 3039. The proxy answers corectly when browsing test.local:3039. Then I have started a cloud container exposing port 80. Virtual Host is cloud.test.local.

When I browse to cloud.test.local:3039 there is still the nginx default page...no forwarding will be done.

Generated config looks good for me;

```
# cloud.test.local
upstream cloud.test.local {
                        ## Can be connect with "bridge" network
                        # nextcloud-app
                        server 172.17.0.6:80;
}
server {
        server_name cloud.test.local;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://cloud.test.local;
        }
}
```

Is there a missing port 3039 in proxy_pass?

nginx logs did not show the subdomain in docker logs (my other proxy on port 80 shows the called subdomain in front of client ip):

`nginx.1    | 10.100.xxx.xx - - [08/Feb/2018:10:55:09 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36" "-"`

**Comment by buchdag** [comment]
Hi.

This project (letsencrypt-nginx-proxy-companion) is separate from nginx-proxy and maintained by different people. We only deal with issues related to letsencrypt-nginx-proxy-companion.

[Please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)

Also note that you won't be able to use the letsencrypt-nginx-proxy-companion [if your nginx proxy does not run on the default ports 80 and 443](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki#requirements).
