### ISSUE TITLE
Launching those 3 containers into a docker-compose

### ISSUE THREAD

**Issue by pascalandy** [JrCs/docker-letsencrypt-nginx-proxy-companion#33]
Yves,
Thanks for the sharing this! I appreciate. Have you been able to put together those [three containers](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#separate-containers-recommended-method) into a docker-compose.yml ?

The way I see my backend is:

1) a docker-compose for: FrontEnd (proxy/servers/firewalls) ([those three guys](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#separate-containers-recommended-method))
2) a docker-compose for: production apps
3) a docker-compose for: labs/staging apps
4) a docker-compose for: dev apps
5) a docker-compose for: database
6) a docker-compose for: monitoring solutions like Nagio
7) more ... backup, GUI stations, etc

///

I tought about launching various `docker run -parameters about a container` from the docker-compose ./app1 but I'm not successful  at that point.

Cheers!

**Comment by fatk** [comment]
Have a look at [this compose file](https://github.com/pixelfordinner/pixelcloud-docker-apps/blob/master/nginx-proxy/docker-compose.yml)

It uses the 3 images you mention (The nginx is a bit modified from the official image because it has a lot of SSL conf embedded in it, but you should be able to use the official one without trouble)

**Comment by pascalandy** [comment]
@fatk I used your [compose file](https://github.com/pixelfordinner/pixelcloud-docker-apps/blob/master/nginx-proxy/docker-compose.yml) and I works! Thank you so much!

Now I have to fix this. https://github.com/jwilder/nginx-proxy/issues/304#issuecomment-195616673

**Comment by JrCs** [comment]
Thanks @fatk and @pascalandy
