### ISSUE TITLE
Redirect port 80 -> 443?

### ISSUE THREAD

**Issue by hookenz** [JrCs/docker-letsencrypt-nginx-proxy-companion#330]
I'm using the letsencrypt proxy companion container with nginx-proxy.  It seems you need port 443 and 80 open for validation.

But I want to enforce https.  Is it possible to get nginx-proxy to redirect 80 to 443 when used?

**Comment by buchdag** [comment]
Hi. When you have https enabled for a virtual host, nginx-proxy automatically redirect http traffic to https.

**Comment by hookenz** [comment]
Thanks, I discovered this later that after https cert is issued, it will create the redirect.

**Comment by buchdag** [comment]
If needed you can control this behavior with the `HTTPS_METHOD` environment variable on the nginx-proxy container (or on the docker-gen container if you are using the three containers setup): https://github.com/jwilder/nginx-proxy#how-ssl-support-works

Do you mind if I close the issue ?

**Comment by hookenz** [comment]
Thanks for the update.  You can close it.  It was a misunderstanding of usage.
