### ISSUE TITLE
Had a lot of problems with wrong certificates being chosen as default

### ISSUE THREAD

**Issue by mortenhartvig** [JrCs/docker-letsencrypt-nginx-proxy-companion#337]
(not sure if this is a feature or bug, or once in a lifetime, hence this post - sorry if it fits more with jwilder/nginx-proxy, but they seem connected. Feel free to mark it solved.)

I had a domain very close to the rate limit (1 weekly request from it) 
(a container who ran with **example.tld, www.example.tld** in both virtual_host and letsencrypt_host)

Then i somehow added (by mistake) another domain into the mix:
(lets say i re-created the container with **example.tld, www.example.tld, otherexample.tld, www.otherexample.tld**  in both virtual_host and letsencrypt_host)

--------
Problem: 
The letsencrypt started nagging about the request was now rate-limited (it thought that all 4 was for the same domain?).

----------------
I then correctly seperated them into two different containers:
Container A: example.tld, www.example.tld in both virtual_host and letsencrypt_host
Container B: otherexample.tld, www.otherexample.tld in both virtual_host and letsencrypt_host

----------
New problem:

Container A continued to work without problems, but container B would not use the right certificate.
 In fact it was thrown a few different ones, (even though it had correctly requested new certificates for the new domain and subdomain - and setting the "cert_name" enviroment variable didn't do any good, in fact it was worse)

The sollution:
--------------------
- I restarted the nginx-proxy container (didnt work - this was a test to rule it out),
- Then i added a "default_host" to it's run command, and built/started it again (problem fixed).

Posting this as others may run into the same issue.

**Comment by buchdag** [comment]
Hi @mortenhartvig , thanks for your report, I think I identified a bug thanks to it: the certificate creation / renewal process does not care wether the certificate issuance succeeded or not when creating symlink to certificates, so you can end up with say a `www.domain.tld.crt` symlink to a certificate that actually does not include this domain. I'll try to fix this soon.
