### ISSUE TITLE
Unable to access challenge file

### ISSUE THREAD

**Issue by rednil** [JrCs/docker-letsencrypt-nginx-proxy-companion#34]
Hello there, many thanks for sharing this. However, I cannot get it to work. As I try to setup a test, I am fighting with two issues:
(1) My first attempt involved the following docker-compose using the following configuration file:
[docker-compose.txt](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/files/172549/docker-compose.txt)
For some reason, it gets stuck at
letsencrypt_1 | + check_writable_directory /usr/share/nginx/html
letsencrypt_1 | + local dir=/usr/share/nginx/html
letsencrypt_1 | + [[ ! -d /usr/share/nginx/html ]]
letsencrypt_1 | + echo 'Error: can'\''t access to '\''/usr/share/nginx/html'\'' directory !'
letsencrypt_1 | Error: can't access to '/usr/share/nginx/html' directory !
letsencrypt_1 | + echo 'Check that '\''/usr/share/nginx/html'\'' directory is declared has a writable volume.'
Note that the previous check on /etc/nginx/vhost.d succeeds without error. When I launch the letsencrypt container manually and attach to it, there is no /usr/share/nginx directory (which IS present in the nginx-proxy container). I have no clue how to debug this further, since
(2) To my total amazement, this works if I start the nginx-proxy container using the docker command directly (like in the description of this project). However, the letsencrypt challenge fails with the following log messages:
[error.txt](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/files/172562/error.txt)
If I attach to either the nginx-proxy or the letsencrypt container, I can see the challenge file at its place under /usr/share/nginx/html/.well-known/acme-challenge, but (obviously) not so in the test container. How is this supposed to work? Does your container remap the proxy settings for a specific folder or why can I even expect to reach the challenge file at this place?

Somewhat puzzled over here (probably due to profound ignorance of both docker AND letsencrypt),
Would be very thankful for any hint 
rednil

**Comment by JrCs** [comment]
Hi, the directory /usr/share/nginx/html from the nginx-proxy container MUST be export and import in this letsencrypt container.
If you want to use docker-compose see #33

**Comment by fatk** [comment]
Your .txt file has a misspelled volume:

```
nginx-proxy:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ../volumes/secureproxy/certs:/etc/nginx/certs:ro
    - /etc/nginx/vhost.d
    - /user/share/nginx/html
  ports:
    - 443:443
    - 80:80
letsencrypt:
  image: jrcs/letsencrypt-nginx-proxy-companion
  environment:
    - DEBUG=true
  volumes_from:
    - nginx-proxy
  volumes:
    - ../volumes/secureproxy/certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
test:
  image: nginx
  environment:
    - VIRTUAL_HOST=test.XXX.YYY
    - LETSENCRYPT_HOST=test.XXX.YYY
    - LETSENCRYPT_EMAIL=ZZZ@XXX.YYY

``` 

```
    - /user/share/nginx/html
```

It should be "/usr/share/nginx/html"

**Comment by JrCs** [comment]
Thanks @fatk for finding the problem.
