### ISSUE TITLE
Default SSL certificate for subdomains

### ISSUE THREAD

**Issue by Giampa** [JrCs/docker-letsencrypt-nginx-proxy-companion#343]
I'm using Let's Encrypt companion on docker-compose v3. I have multiple hosts with SSL. On my Nginx container I expose:

  - VIRTUAL_HOST=api.example.com,service.example.com
  - LETSENCRYPT_HOST=api.example.com,service.example.com
  - LETSENCRYPT_EMAIL=tech@example.com

This setting is working fine except for the fact that if I read SSL certificate details on service.example.com I get as name api.example.com. Is this the expected behaviour or can I fix it somehow? Many thanks.

**Comment by buchdag** [comment]
Hello. When you request a certificate with multiple domain names, Let's Encrypt will issue a SAN (Subject Alternative Name) certificate. The first domain provided will be the CN or Common Name of the certificate, all the others will appear under the `Certificate/Extensions/Certificate Subject Alt Name` field (using Firefox as an example) along with the Common Name.

**Comment by Giampa** [comment]
Ok thanks for your response. How can I separate domain name request? Should I add a Nginx (or other web server )container for each domain? What's the best practice for that?

**Comment by buchdag** [comment]
Do you mind if I ask why would you want to do this ?

What is bothering you with the way SAN certificate works ?

**Comment by Giampa** [comment]
Because I've never seen this behaviour before, but I trust you that's correct, I'm quite new in SSL. You can close and thanks again for your work.
