### ISSUE TITLE
ACME v2 support

### ISSUE THREAD

**Issue by Undeadhunter** [JrCs/docker-letsencrypt-nginx-proxy-companion#348]
Let's Encrypt just released v2 as well as wildcard support.
https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

Would be great to have this added so only 1 certificate needs to be used instead of 1 per sub domain.

**Comment by buchdag** [comment]
Support for wildcard certs won't be possible, see #319
