### ISSUE TITLE
Is Letsencrypt Wildcard available

### ISSUE THREAD

**Issue by Hackbard** [JrCs/docker-letsencrypt-nginx-proxy-companion#349]
Hi there,

first of all thanks for the great work. 
This is one of my favorite Docker container ;)

I would like to ask if we can already generate wildcard certs?

Kind Regards
Hackbard

**Comment by Kiina** [comment]
#319 

No and seems like it wont happen

**Comment by Hackbard** [comment]
Ok i see. 
that's sad
