### ISSUE TITLE
Error under Separate Containers: /etc/docker-gen/templates/nginx.tmpl is a directory.

### ISSUE THREAD

**Issue by hyp530** [JrCs/docker-letsencrypt-nginx-proxy-companion#35]
I exactly follow the instructions as below:

docker run -d -p 80:80 -p 443:443 \
--name nginx \
-v /etc/nginx/conf.d \
-v /etc/nginx/vhost.d \
-v /usr/share/nginx/html \
-v /path/to/certs:/etc/nginx/certs:ro \
nginx

docker run -d \
--name nginx-gen \
--volumes-from nginx \
-v /path/to/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro \
-v /var/run/docker.sock:/tmp/docker.sock:ro \
jwilder/docker-gen \
-notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

The first one Nginx works normally, but the second one Docker-gen exited in no time. The docker log shows: 2016/03/15 01:24:42 unable to parse template: read /etc/docker-gen/templates/nginx.tmpl: is a directory

Could you kindly tell me what's wrong and how to make it? Thank you very much.

**Comment by fatk** [comment]
I think your nginx.tmpl is either missing or has a syntax error. could post those 2 commands with the real paths along with the content of your nginx.tmpl?

**Comment by hyp530** [comment]
**First, I simply run the two commands exactly the same with that in the instructions:**
hyp530@vultr:~$ docker run -d -p 80:80 -p 443:443 \
>  --name nginx \
>  -v /etc/nginx/conf.d \
>  -v /etc/nginx/vhost.d \
>  -v /usr/share/nginx/html \
>  -v /path/to/certs:/etc/nginx/certs:ro \
>  nginx
Unable to find image 'nginx:latest' locally
latest: Pulling from library/nginx

fdd5d7827f33: Already exists
a3ed95caeb02: Pull complete
716f7a5f3082: Pull complete
7b10f03a0309: Pull complete
Digest: sha256:f6a001272d5d324c4c9f3f183e1b69e9e0ff12debeb7a092730d638c33e0de3e
Status: Downloaded newer image for nginx:latest
cbe27695310d474aad23eeee28387f3aaad3ade2a510b21e84934324ed27903f

hyp530@vultr:/path/to$ docker run -d \
>  --name nginx-gen \
>  --volumes-from nginx \
>  -v /path/to/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro \
>  -v /var/run/docker.sock:/tmp/docker.sock:ro \
>  jwilder/docker-gen \
>  -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
Unable to find image 'jwilder/docker-gen:latest' locally
latest: Pulling from jwilder/docker-gen
4d690fa98655: Pull complete
a3ed95caeb02: Pull complete
15845219ea85: Pull complete
Digest: sha256:48471b4b3317ca38df9e143ab377ec225d4da64a010a63c86c5508314ff831ec
Status: Downloaded newer image for jwilder/docker-gen:latest
4efb0a437bcd2e408b5ec028db2e27c5f97c56e673aa7c9cd5fe1c10c2001e78

**Second, I found Nginx-gen container not running, and I use docker logs to find the error as below: **

hyp530@vultr:/path/to$ docker logs nginx-gen
2016/03/16 02:32:27 unable to parse template: read /etc/docker-gen/templates/nginx.tmpl: is a directory

**Third, I found /path/to/nginx.tmpl automatically created, and it's a folder. Then I remove it and replace with a new file of /path/to/nginx.tmpl with content copied from (https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl). **

**Then, I restart Docker-gen container again and encounter a new error: **
hyp530@vultr:/path/to$ docker start nginx-gen
Error response from daemon: Cannot start container 4efb0a437bcd2e408b5ec028db2e27c5f97c56e673aa7c9cd5fe1c10c2001e78: [9] System error: not a directory

**Fourth, I check the logs with the following records:**

hyp530@vultr:/path/to$ docker logs 4efb0a437bcd
2016/03/16 02:32:27 unable to parse template: read /etc/docker-gen/templates/nginx.tmpl: is a directory
Timestamp: 2016-03-16 02:36:50.210673626 +0000 UTC
Code: System error

Message: not a directory

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@40
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@57
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@240
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@18
---
6: main
Package: runtime
File: proc.go@111
---
7: goexit
Package: runtime
File: asm_amd64.s@1721
Timestamp: 2016-03-16 02:37:01.470234867 +0000 UTC
Code: System error

Message: not a directory

Frames:
---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@40
---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@57
---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@240
---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35
---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26
---
5: main
Package: main
File: docker.go@18
---
6: main
Package: runtime
File: proc.go@111
---
7: goexit
Package: runtime
File: asm_amd64.s@1721

**Comment by JrCs** [comment]
The directory `/path/to`in the README is an example and must be replace to a path to a directory on the host.
Also this directory must contain (if you follow the commands in the README):
* A directory `certs`
* The `nginx.tmpl` file

Please read the documentation about [docker volumes](https://docs.docker.com/engine/userguide/containers/dockervolumes/) (espacialy the **Mount a host directory as a data volume**)

**Comment by emcniece** [comment]
If future folks need some clarity, the exact problem is the voluming of the `nginx.tmpl` file.

This:

```
-v /path/to/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro 
```

... should be this:

```
-v /path/to:/etc/docker-gen/templates
```
