### ISSUE TITLE
LetsEncrypt Wildcards Option

### ISSUE THREAD

**Issue by evertramos** [JrCs/docker-letsencrypt-nginx-proxy-companion#350]
Hello @JrCs!

Will we have wildcards options? As of LetsEncrypt release ACME v2 that supports it.

Thanks!

**Comment by buchdag** [comment]
Not with the current ACME client (`simp_le`), even if it supports ACME v2 later. See #319

**Comment by evertramos** [comment]
sorry I search for wildcards not wildcard reason why I did not find it. thanks!
