### ISSUE TITLE
Cleaning up certificates (or something)

### ISSUE THREAD

**Issue by 4integration** [JrCs/docker-letsencrypt-nginx-proxy-companion#353]
Hi,

I have tested with jwilder/nginx-proxy and alastaircoote/docker-letsencrypt-nginx-proxy-companion and it works great.

Since I have played with it and with a number of subdomains I seems to have consumed all certificates for this IP.

`2018-03-23 12:56:04,435:INFO:requests.packages.urllib3.connectionpool:756: Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
ACME server returned an error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new registration :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/`

I have 5 active subdomains to my domain where one doesn't work (above).

I am thinking of some cache of old tests blocking.

Any ideas how to solve it?

**Comment by buchdag** [comment]
`alastaircoote/docker-letsencrypt-nginx-proxy-companion` is an extremely outdated fork of this project.

**Comment by buchdag** [comment]
The specific rate limit you just hit is this one:

> You can create a maximum of 10 Accounts per IP Address per 3 hours. You can create a maximum of 500 Accounts per IP Range within an IPv6 /48 per 3 hours. Hitting either account rate limit is very rare, and we recommend that large integrators prefer a design using one account for many customers.

This rate limit is on Let's Encrypt side, and the only thing you can do is wait for three hours.

The recommendation to [use one account for many customer](https://letsencrypt.org/docs/integration-guide/) to prevent that kind of rate limiting has been merged to `jrcs/docker-letsencrypt-nginx-proxy-companion` a few months ago: 7f66758f01855bdd3ac5008702c2ac23611502c0

**Comment by 4integration** [comment]
Yeah... I just replaced the image to jrcs/docker-letsencrypt-nginx-proxy-companion and now it works.
Thanks
