### ISSUE TITLE
Proxy two different ports of the same container (Nexus Registry setup)

### ISSUE THREAD

**Issue by LorenzoCamerini** [JrCs/docker-letsencrypt-nginx-proxy-companion#356]
Hi,
I am facing the problem of proxing different ports to the same container.
This is the case of Nexus Registry setup, where the nexus container exposes 8081 for nexus and a different one (i.e. 18444) for docker registry.
I have defined two sub-domain:
- nexus.mydomain.com
- docker.nexus.mydomain.com
Both of them need to use letsencrypt.

I cannot see any good solution for proxying the request coming from "nexus.mydomain.com" to 8081 and the one coming to "docker.nexus.mydomain.com" to 18444 of the same container using this proxy-companion.
I searched a bit and the only two possibile solutions could be:
- Adding an extra nginx just to have a different container that prox all request to 18444 exposed by nexus container.
- Change the nginx template in order to parse the VIRTUAL_HOST env property in order to support something like: VIRTUAL_HOSTS="nexus.mydomain.com:8081,docker.nexus.mydomain.com:18444"

The first one seems bad to me because I am introducing an extra (not wanted) nginx.
The second one seems better, but am not so confident in changing your template because I am not familiar with that syntax.

Can you give me an advice for solving my problem?
There is any possibility to support this kind of configuration in the future?

**Comment by buchdag** [comment]
Hi.

This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

What you want to achieve depends entirely on the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different peoples.

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)
