### ISSUE TITLE
How to use Let's Encrypt DNS challenge validation

### ISSUE THREAD

**Issue by mdenissov** [JrCs/docker-letsencrypt-nginx-proxy-companion#358]
How I can user the container with manual DNS challenge validation?

Where can I get value for TXT DNS record?

**Comment by fkling** [comment]
> the only challenge method supported is http-01

Are there plans to support other methods?

**Comment by buchdag** [comment]
@fkling yes but that's mid / long term, I can't give you any ETA or even an estimate.

**Comment by Kawetsch** [comment]
Hey all,

are there any updates?

All the best
