### ISSUE TITLE
key.pem is a directory?

### ISSUE THREAD

**Issue by 10io** [JrCs/docker-letsencrypt-nginx-proxy-companion#362]
Hello,

I have a working `docker-compose.yml` file with the 2 containers setup: `nginx-proxy`, `letsencrypt-nginx-proxy-companion` and my `ftp` server. Yesterday, everything was working fine.

Today, we changed the hostname. I updated the `docker-compose.yml` file, recreated the containers and I face this issue (XXX is my new host)

```
letsencrypt-nginx-proxy-companion_1  | Creating/renewal XXX certificates... (XXX)
letsencrypt-nginx-proxy-companion_1  | Traceback (most recent call last):
letsencrypt-nginx-proxy-companion_1  |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1584, in main
letsencrypt-nginx-proxy-companion_1  |     return main_with_exceptions(cli_args)
letsencrypt-nginx-proxy-companion_1  |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1561, in main_with_exceptions
letsencrypt-nginx-proxy-companion_1  |     existing_data = load_existing_data(args.ioplugins)
letsencrypt-nginx-proxy-companion_1  |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1322, in load_existing_data
letsencrypt-nginx-proxy-companion_1  |     all_data = IOPlugin.registered[plugin_name].load()
letsencrypt-nginx-proxy-companion_1  |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 338, in load
letsencrypt-nginx-proxy-companion_1  |     with open(self.path, self.READ_MODE) as persist_file:
letsencrypt-nginx-proxy-companion_1  | IOError: [Errno 21] Is a directory: 'key.pem'
letsencrypt-nginx-proxy-companion_1  | 
letsencrypt-nginx-proxy-companion_1  | Unhandled error has happened, traceback is above
```

Has anyone an idea as to why the `key.pem` location is now suddenly a folder?

I have the same error if I try to force renew the certificate.

Many thanks!

**Comment by 10io** [comment]
Yep, I'm working with docker volumes. I tried to destroy and recreate the volume for the certificates but I get the same issue.

I'll dig this again next week. I'll update this issue if I find anything useful.

**Comment by 10io** [comment]
Ok so the issue had nothing to do with `letsencrypt-nginx-proxy-companion`. It's the `ftp` server that starts and expects to have a `key.pem` file but `letsencrypt-nginx-proxy-companion` can still be handling the file generation and it can be missing. 

For whatever reason, if the `key.pem` file is missing, the `ftp` software (pureftp) creates a `key.pem` folder which then causes `letsencrypt-nginx-proxy-companion` to fail when it tries to write the `key.pem` file.

I workaround that by having all containers started, removing the `key.pem` folder and forcing `letsencrypt-nginx-proxy-companion` to do a renewal with `docker exec XXX /app/force_renew`. A proper fix would be to update the `ftp` container so that it only starts the ftp server when the `key.pem` file is present.

Anyway, thanks for your time.

**Comment by buchdag** [comment]
You're welcome, thanks for the update on the resolved issue.
