### ISSUE TITLE
Certificates generation process gets killed

### ISSUE THREAD

**Issue by kaiokenx10** [JrCs/docker-letsencrypt-nginx-proxy-companion#365]
Hi,

I followed [this](https://vfeskov.com/2017/04/15/free-https-on-multi-container-elastic-beanstalk-without-load-balancer/) tutorial and almost everything is working fine 😄. In general I see that the certificates are tried to be created but they fail. When I do this manually by running the renewal script I get this:
```
[root@ip-x-x-x-x ec2-user]# docker exec -it 0df6c255c4e8 /app/force_renew
/etc/nginx/certs/subdomain.domain.com /app
Creating/renewal subdomain.domain.com certificates... (subdomain.domain.com)
/app/letsencrypt_service: line 118:   184 Killed                  /usr/bin/simp_le -f account_key.json -f key.pem -f chain.pem -f fullchain.pem -f cert.pem $params_d_str --cert_key_size=$cert_keysize --server=$acme_ca_uri --default_root /usr/share/nginx/html/
/app
```

The directory with the certificates has the folder called `subdomain.domain.com` but it is empty, same as the other shared volumes used for the process like `vhost.d` and `html`.

Thx for any help here.

**Comment by buchdag** [comment]
Hi. Were you able to troubleshoot and/or solve this?

**Comment by buchdag** [comment]
Was it working before ? What version of the container are you using ? What OS, Docker and Docker Composer version are you using ? Can you share your compose file ?

**Comment by kaipaysen** [comment]
a) Well it's a first time setup for this particular project but has been used in other projects in the exact same way.
b) latest
c) Linux, 18.04.0-ce, 1.21.1, build 5a3f1a3
d) yes: [docker-compose-prod.yml.txt](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/files/2054855/docker-compose-prod.yml.txt)

**Comment by buchdag** [comment]
I have no idea how `memory_limit` plays with this container.

Have you tried raising the limit ? Using `docker stat` and manually triggering `/app/signal_le_service`, I just saw memory usage slightly above 30 Mib.

**Comment by kaipaysen** [comment]
Good hint. This particular server had swap disabled. That's why it didn't work here but in other projects with the same setup. Cheers mate!

**Comment by buchdag** [comment]
@kaiokenx10 I suspect your issue has the same cause.

**Comment by buchdag** [comment]
No update from issue creator, closing.
