### ISSUE TITLE
Varnish cache server

### ISSUE THREAD

**Issue by brandon-welsch** [JrCs/docker-letsencrypt-nginx-proxy-companion#366]
Hey,

It's be possible to add varnish cache container between reverse proxy and app containers ?

**Comment by buchdag** [comment]
Hi.

This project (`letsencrypt-nginx-proxy-companion`) does not handle the actual proxying so you probably won't get the answer you are looking for here. [`nginx-proxy`](https://github.com/jwilder/nginx-proxy) does and you should ask there instead.

If something is possible at all with nginx, it will probably be possible with `nginx-proxy` too (using a custom nginx.tmpl for `docker-gen`).
