### ISSUE TITLE
--test-cert equivalent. 

### ISSUE THREAD

**Issue by aarobc** [JrCs/docker-letsencrypt-nginx-proxy-companion#37]
In the letsencrypt documentation they talk about using the `--test-cert` flag for testing so you don't go over the limits of 5 certs/week/domain. It would be very useful to have an equivalent parameter that could be set via environment variable.

**Comment by JrCs** [comment]
Look at the `ACME_CA_URI`environment variable in the README.
If you set its value to https://acme-staging.api.letsencrypt.org/directory you will using the ACME test server that don't have the 5 certs/week/domain limits.
