### ISSUE TITLE
[deprecated] signer and verifier have been deprecated in jwa.py

### ISSUE THREAD

**Issue by w4tsn** [JrCs/docker-letsencrypt-nginx-proxy-companion#370]
Just to let you know, I'm receiving a deprecation warning in jwa package:

```
/usr/lib/python2.7/site-packages/acme/jose/jwa.py:110: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = key.signer(self.padding, self.hash)
```

I'm using current latest tagged image 1ce287a17a1c (from 25.04.2018)

**Comment by buchdag** [comment]
Hi, this warning will disappear in the next version, when the`simp_le` version in use will be updated to >= 0.8.0
