### ISSUE TITLE
Necessity of VIRTUAL_HOST env variable

### ISSUE THREAD

**Issue by sherter** [JrCs/docker-letsencrypt-nginx-proxy-companion#38]
I understand that most people use this container to build a reverse-ssl-proxy for their http apps. In that case, when you run a container with `-e LETSENCRYPT_HOST` and `-e LETSENCRYPT_EMAIL` you almost always want to have a virtual host generated for you that forwards traffic to your app (and therefore you specify the same value for `VIRTUAL_HOST` and `LETSENCRYPT_HOST`). However, if I just want to generate (and automatically refresh) a certificate for my SMTP server, I don't really want a permanent virtual http host to be generated for this (sub-)domain (e.g. smtp.example.com).

Not specifying `VIRTUAL_HOST` currently doesn't work.  If `VIRTUAL_HOST` is missing, couldn't we create a virtual host for the domains in `LETSENCRYPT_HOST` for the duration of domain validation and delete it afterwards again? This would make this container a more general "certificate generator and refresher".

**Comment by JrCs** [comment]
Hi, no we can't remove VIRTUAL_HOST environment variable because it is use to configure nginx proxy and it doesn't use for letsencrypt.
If you don't have a VIRTUAL_HOST environment variable on your web container, the nginx proxy will not respond to request for the domain.

**Comment by sherter** [comment]
@JrCs I know that `VIRTUAL_HOST` is used by the proxy-container and not by the letsencrypt container. But the letsencrypt container also modifies the nginx config. The `location /.well-known/ { .. }` part is from the letsencrypt container, isn't it?
So couldn't the letsencrypt container also create a virtual host on its own, if no `VIRTUAL_HOST` variable is defined? This would probably require some modifications to `nginx.tmpl`.

**Comment by JrCs** [comment]
Yes the letsencrypt container add some configurations to the nginx proxy.
Yes we need to change the nginx.tmpl to get this case, and nginx.tmpl is a template from nginx-proxy.
I don't have a specific version of nginx.tmpl for this letsencrypt container. Each container use it's own environment variable (VIRTUAL_HOST for the docker-gen container and LETS_ENCRYPT_XXX for this container) and i don't want to mix all of them.
The nginx reverse proxy can be used with the docker-gen container without the letsencrypt container.
This container is just an add-ons to the nginx/docker-gen containers and it is not design to replace functionnality of one of them:
* nginx container do the reverse proxy
* docker-gen update the nginx proxy configuration when containers are create/remove
* letsencrypt-nginx-proxy-companion create letsencrypt certificats

**Comment by sherter** [comment]
@JrCs I understand. It's totally legitimate to keep things simple and compatible with the `nginx.tmpl` in jwilder/nginx-proxy :+1:
Would you mind adding a LICENSE file to this project so I can fork it and support my specific use case?

**Comment by JrCs** [comment]
@sherter ok i will add a LICENSE file

**Comment by sherter** [comment]
Cool, thanks!
