### ISSUE TITLE
Getting error about three container setup, but I have 2 containers (docker-compose)

### ISSUE THREAD

**Issue by mrg20** [JrCs/docker-letsencrypt-nginx-proxy-companion#381]
Hi, I am having a problem with the nginx-letsencrypt container and I can't find a solution... 

I have this docker-compose:
```version: "2"

services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/etc/nginx-proxy/certs:/etc/nginx/certs:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  nginx-letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/nginx-proxy/certs:/etc/nginx/certs:rw"
    environment:
     - NGINX_PROXY_CONTAINER=nginx-proxy

  sttdb-client:
    image: sttdb/sttdb-client
    container_name: sttdb-client
    environment:
      - VIRTUAL_HOST=sttdb.udl.cat
      - LETSENCRYPT_HOST=sttdb.udl.cat
      - LETSENCRYPT_EMAIL=ma*****
```

And I am getting the error:

`nginx-letsencrypt    | Error: can't get docker-gen container id !
nginx-letsencrypt    | If you are running a three containers setup, check that you are doing one of the following :
nginx-letsencrypt    | 	- Set the NGINX_DOCKER_GEN_CONTAINER env var on the letsencrypt-companion container to the name of the docker-gen container.
nginx-letsencrypt    | 	- Label the docker-gen container to use with 'com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen.'
`

I try to use the jrcs/letsencrypt-nginx-proxy-companion:v1.7 and I get the error:

`nginx-letsencrypt    | Error: can't write to the '/etc/nginx/certs' directory !
nginx-letsencrypt    | Check that '/etc/nginx/certs' directory is export as a writable volume.
nginx-letsencrypt    | Warning: '/etc/nginx/certs' does not appear to be a mounted volume.`

I know it has rw in the letsencrypt volume, but I also changed the ro permission to rw in the nginx container and I have the same error.

**Comment by buchdag** [comment]
Hi, could you try with `jwilder/nginx-proxy` instead of `jwilder/nginx-proxy:alpine` ?

**Comment by buchdag** [comment]
Docker 1.13.1 isn't **that** old, I'd be curious to know why it did not work.

**Comment by addtde** [comment]
Error: nginx-proxy container 78100e16e0fd7cbc9f11e3b9ddfdf0e87b070ca8aad9e00985278d71a06698af isn't running.

help
