### ISSUE TITLE
Getting error 413 'Request Entity too Large' for nextcloud container

### ISSUE THREAD

**Issue by egonzalezjr555** [JrCs/docker-letsencrypt-nginx-proxy-companion#384]
Hello all, 

So I've been looking through the issues and I have been unable to get the error 413 fixed. I have already change added `client_max_body_size `entry to the `/etc/nginx/conf.d` folder and restarted the the docker file and even added it from a file before initializing it.  That seems to be the solution I see from other posts I have seen and I was wondering if am missing something. The nginx-proxy and letsencrypt have been setup the same way it is in the wiki basic usage section instructions.

**Comment by buchdag** [comment]
Hi.

This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

The issue you are facing with nextcloud concerns the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different peoples.

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo](https://github.com/jwilder/nginx-proxy/issues) and/or [to nextcloud](https://github.com/nextcloud).

**Comment by egonzalezjr555** [comment]
As soon as I took off this `JrCs/docker-letsencrypt-nginx-proxy-companion` the issue went away it looks like there are compatibility issues. Either way I am manually adding the certificates.
