### ISSUE TITLE
Testing with Let's Encrypt Pebble - certificate verify failed

### ISSUE THREAD

**Issue by bldrvnlw** [JrCs/docker-letsencrypt-nginx-proxy-companion#395]
Let's Encrypt provides a light weight CA  [Pebble](https://github.com/letsencrypt/pebble) for testing in you local environment.

I have Pebble running in a docker on the same network as the jrcs/letsencrypt-nginx-proxy-companion. To point to the local Pebble CA I added `      ACME_CA_URI: https://172.20.0.2:14000` to the environment. 

letsencrypt-nginx-proxy-companion gives the following error when trying to renew the certificate  `SSLError: HTTPSConnectionPool(host='172.20.0.2', port=14000): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))`. 

On the CA (Pebble) side I get `http: TLS handshake error from 172.20.0.6:59710: remote error: tls: unknown certificate authority
`
Has anyone had any success with this combination?

**Comment by bldrvnlw** [comment]
Forgot to mention - in the Pebble environment I've set ` PEBBLE_VA_ALWAYS_VALID=1` to avoid the need to set up a challenge response server

**Comment by buchdag** [comment]
https://github.com/letsencrypt/pebble#avoiding-client-https-errors

And I don't think it'll work anyway, pebble being ACME v2 only, [which isn't supported by this container yet](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/319).

**Comment by bldrvnlw** [comment]
So I'd need to place a root cert at /etc/nginx/ssl/?

But as you point out that might no work. Is Pebble really ACME v2 only? In that case I suppose I could use Boulder.

**Comment by buchdag** [comment]
> So I'd need to place a root cert at /etc/nginx/ssl/?

No idea, I haven't used Pebble yet and I don't know how to manipulate simp_le trusted root configuration.

> Is Pebble really ACME v2 only?

Yep, that's why we're using Boulder instead in the current test setup.

**Comment by bldrvnlw** [comment]
Thanks for the tip - I'll go that route.
