### ISSUE TITLE
Certificate generation is flaky

### ISSUE THREAD

**Issue by NicolasDorier** [JrCs/docker-letsencrypt-nginx-proxy-companion#396]
So I have an issue time to time happening:

Sometimes, the creation of the diffie hellman takes 10 minutes, sometimes it goes quicker:
```
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
```

When it goes quick, no worry, everything works fine. When it is slow,:

```
....................................+.................................+............++*++*
2018/06/06 15:07:08 Generated '/app/letsencrypt_service_data' from 7 containers
2018/06/06 15:07:08 Running '/app/signal_le_service'
2018/06/06 15:07:08 Watching docker events
2018/06/06 15:07:08 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
Sleep for 3600s
```

At this point I don't have my certificate. 

When I manually restart `docker-letsencrypt-nginx-proxy-companion` container via `docker restart`, everything unlocks:

```
2018/06/06 15:16:28 Received signal: terminated
2018/06/06 15:16:28 Received signal: terminated
/etc/nginx/certs/_test_tempfewiofnw.northeurope.cloudapp.azure.com /app
2018/06/06 15:17:10 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
2018/06/06 15:17:10 Watching docker events
2018/06/06 15:17:11 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
Reloading nginx docker-gen (using separate container nginx-gen)...
Reloading nginx (using separate container nginx)...
Creating/renewal tempfewiofnw.northeurope.cloudapp.azure.com certificates... (tempfewiofnw.northeurope.cloudapp.azure.com)
2018-06-06 15:17:13,937:INFO:simp_le:1382: Generating new account key
2018-06-06 15:17:17,001:INFO:simp_le:1407: By using simp_le, you implicitly agree to the CA's terms of service: https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
2018-06-06 15:17:17,705:INFO:simp_le:1479: Generating new certificate private key
2018-06-06 15:17:25,131:INFO:simp_le:360: Saving account_key.json
2018-06-06 15:17:25,132:INFO:simp_le:360: Saving key.pem
2018-06-06 15:17:25,132:INFO:simp_le:360: Saving chain.pem
2018-06-06 15:17:25,132:INFO:simp_le:360: Saving fullchain.pem
2018-06-06 15:17:25,133:INFO:simp_le:360: Saving cert.pem
/app
Reloading nginx docker-gen (using separate container nginx-gen)...
Reloading nginx (using separate container nginx)...
```

At this time, I get the certificate.

So my question I tried looking [into your code](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/app/letsencrypt_service#L124).

However, `check_nginx_proxy_container_run` should run, because I get HTTP access just fine when HTTPS does not work.

```
[[ -f "$DIR"/letsencrypt_service_data ]] || return
```

Maybe `docker-gen` is too slow to write the file?

I will try to reproduce. This is kind of hard, as sometimes it does not happen. I guess there is some timing issue somewhere.

**Comment by buchdag** [comment]
There is a pending PR that might help with this issue #394

**Comment by buchdag** [comment]
I think I've been experiencing the same issue on Travis CI.

There is definitely a timing issue somewhere, even with background DH group creation merged in.

**Comment by buchdag** [comment]
By the way you can always manually trigger the letsencrypt service loop with

`docker exec your-le-companion-container /app/signal_le_service`

That's might be marginally faster than using `docker restart` when the first cert creation fail.

**Comment by buchdag** [comment]
Ok so the culprit appears to be the `$DIR` variable in `letsencrypt_service.sh` that end up being empty sometimes. I can't figure if this is caused by a shell scope issue or by `"$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"` not working properly for some reason.

Considering that this variable is used a grand total of three times, the safest/fastest fix would be to hardcode `/app/letsencrypt_service_data` rather than use `$DIR/letsencrypt_service_data`.

**Comment by buchdag** [comment]
@NicolasDorier now that #404 has been merged, that **should** be fixed. Could you test and confirm ?

**Comment by NicolasDorier** [comment]
@buchdag yes will do today or tomorrow. I hope #404 is in latest image.

**Comment by NicolasDorier** [comment]
Using image 037927310b56 from docker. Same issue.

**Comment by NicolasDorier** [comment]
Closing for now. My latest error was https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/pull/408 which seems to be a change of behavior of let's encrypt done very recently.

Your PR #404 seems to have solved my issue. It was however working time to time before, so it might just be luck.

I close for now, will reopen if it happens again.
