### ISSUE TITLE
question about multiple instances (swarm)

### ISSUE THREAD

**Issue by publicocean0** [JrCs/docker-letsencrypt-nginx-proxy-companion#398]
in the examples there is not a case can be important: 
if i have the same app in multiple host machines where (where the app instance is running inside docker).
it is possible to make scalable this system?

**Comment by buchdag** [comment]
Hi. Neither `nginx-proxy`, `docker-gen` or `letsencrypt-nginx-proxy-companion` have support for docker swarm.

**Comment by publicocean0** [comment]
ok thanks
