### ISSUE TITLE
Automatic certificate renewal

### ISSUE THREAD

**Issue by wader** [JrCs/docker-letsencrypt-nginx-proxy-companion#4]
Hi, is this done at the moment or will only be done on other events? is it the 3600 second wait? can't figure out how it works.
Thanks for the docker image, works great.

**Comment by JrCs** [comment]
Every 3600 seconds it will check the certificates. Every certificates that will expire  in the next 10 days  are renew.

**Comment by wader** [comment]
Ok, thanks! you sure it's 10 days? is it just the default used by simple_le? https://github.com/kuba/simp_le/blob/ecf4290c4f7863bb5427b50cdd78bc3a5df79176/simp_le.py#L72 that seems to be 30 days (90 days / 3).

**Comment by JrCs** [comment]
@wader sorry you're right. The certificates are renew every 30 days.
