### ISSUE TITLE
special chars in common name

### ISSUE THREAD

**Issue by OmgImAlexis** [JrCs/docker-letsencrypt-nginx-proxy-companion#40]
I'm not sure if this is a issue with this container or if Let's Encrypt don't allow it but I can't get a domain working that uses an underscore at the start of the subdomain. It never triggers the update_certs command and if I run it manually it skips the docker with that domain.

I tried running this and the companion docker says nothing at all in the logs yet if I do the same with any other subdomain it fetches the cert from Let's Encrypt. Obviously I used my own domain instead of `example.com`.

````
docker run -d -p 127.0.0.1::80 \
    --name underscore_example_com \
    --restart=always \
    -v "$PWD":/usr/share/nginx/html \
    -e "VIRTUAL_HOST=_.example.com" \
    -e "LETSENCRYPT_HOST=_.example.com" \
    -e "LETSENCRYPT_EMAIL=example@example.com" \
    nginx
````

**Comment by JrCs** [comment]
You can't use an underscore at start of a dns domain.
This is not allowed:
The Internet standards (Requests for Comments) for protocols mandate that component hostname labels may contain only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the digits '0' through '9', and the hyphen ('-'). The original specification of hostnames in RFC 952, mandated that labels could not start with a digit or with a hyphen, and must not end with a hyphen. However, a subsequent specification (RFC 1123) permitted hostname labels to start with digits. No other symbols, punctuation characters, or white space are permitted.

**Comment by OmgImAlexis** [comment]
http://domainkeys.sourceforge.net/underscore.html I wouldn't be too sure about that. It seems they may be allowed in hostnames.

**Comment by JrCs** [comment]
No. Read the conclusion:

> Underscores are allowed in certain DNS entries

So you can use name starting with _ for SRV, TXT, etc.. entries but not for A, CNAME, MX entries.
