### ISSUE TITLE
Permissions: private keys readable by all users on host machine

### ISSUE THREAD

**Issue by dlazerka** [JrCs/docker-letsencrypt-nginx-proxy-companion#412]
I noticed that certificates together with key.pem are stored on host machine with `-rw-r--r--` permissions.
I believe that should be `-rw-------`.

Just checked how LetsEncrypt certbot does it -- `-rw-------` and `drwx------` on containing directory.

**Comment by buchdag** [comment]
relevant certbot reference:

```
[drwxr-xr-x]  /etc/letsencrypt
├── [drwx------]  accounts
│   └── [drwx------]  acme-v01.api.letsencrypt.org
│       └── [drwx------]  directory
│           └── [drwx------]  somehash
│               ├── [-rw-r--r--]  meta.json
│               ├── [-r--------]  private_key.json
│               └── [-rw-r--r--]  regr.json
├── [drwx------]  archive
│   ├── [drwxr-xr-x]  domain.tld
│   │   ├── [-rw-r--r--]  cert1.pem
│   │   ├── [-rw-r--r--]  chain1.pem
│   │   ├── [-rw-r--r--]  fullchain1.pem
│   │   └── [-rw-r--r--]  privkey1.pem
│   └── [drwxr-xr-x]  subdomain.domain.tld
│       ├── [-rw-r--r--]  cert1.pem
│       ├── [-rw-r--r--]  chain1.pem
│       ├── [-rw-r--r--]  fullchain1.pem
│       └── [-rw-r--r--]  privkey1.pem
└──[drwx------]  live
    ├── [drwxr-xr-x]  domain.tld
    │   ├── [lrwxrwxrwx]  cert.pem -> ../../archive/domain.tld/cert1.pem
    │   ├── [lrwxrwxrwx]  chain.pem -> ../../archive/domain.tld/chain1.pem
    │   ├── [lrwxrwxrwx]  fullchain.pem -> ../../archive/domain.tld/fullchain1.pem
    │   └── [lrwxrwxrwx]  privkey.pem -> ../../archive/domain.tld/privkey1.pem
    └── [drwxr-xr-x]  subdomain.domain.tld
        ├── [lrwxrwxrwx]  cert.pem -> ../../archive/subdomain.domain.tld/cert1.pem
        ├── [lrwxrwxrwx]  chain.pem -> ../../archive/subdomain.domain.tld/chain1.pem
        ├── [lrwxrwxrwx]  fullchain.pem -> ../../archive/subdomain.domain.tld/fullchain1.pem
        └── [lrwxrwxrwx]  privkey.pem -> ../../archive/subdomain.domain.tld/privkey1.pem
```

Translated to our case, that might be:

```
[drwx------]  /etc/nginx/certs
├── [drwx------]  accounts
│   └── [drwx------]  acme-v01.api.letsencrypt.org
│       └── [drwx------]  directory
│           └── [-r--------]  default.json
├── [-rw-r--r--]  dhparam.pem
├── [drwx------]  domain.tld
│   ├── [lrwxrwxrwx]  account_key.json -> ../accounts/acme-v01.api.letsencrypt.org/directory/default.json
│   ├── [-rw-r--r--]  cert.pem
│   ├── [-rw-r--r--]  chain.pem
│   ├── [-rw-r--r--]  fullchain.pem
│   └── [-rw-------]  key.pem
├── [lrwxrwxrwx]  domain.tld.chain.pem -> ./domain.tld/chain.pem
├── [lrwxrwxrwx]  domain.tld.crt -> ./domain.tld/fullchain.pem
├── [lrwxrwxrwx]  domain.tld.dhparam.pem -> ./dhparam.pem
├── [lrwxrwxrwx]  domain.tld.key -> ./domain.tld/key.pem
├── [drwx------]  subdomain.domain.tld
│   ├── [lrwxrwxrwx]  account_key.json -> ../accounts/acme-v01.api.letsencrypt.org/directory/default.json
│   ├── [-rw-r--r--]  cert.pem
│   ├── [-rw-r--r--]  chain.pem
│   ├── [-rw-r--r--]  fullchain.pem
│   └── [-rw-------]  key.pem
├── [lrwxrwxrwx]  subdomain.domain.tld.chain.pem -> ./subdomain.domain.tld/chain.pem
├── [lrwxrwxrwx]  subdomain.domain.tld.crt -> ./subdomain.domain.tld/fullchain.pem
├── [lrwxrwxrwx]  subdomain.domain.tld.dhparam.pem -> ./dhparam.pem
└── [lrwxrwxrwx]  subdomain.domain.tld.key -> ./subdomain.domain.tld/key.pem
```

Changes that need to be made to stick to this:

```
[drwx------]  /etc/nginx/certs
├── [drwx------]  accounts
│   └── [drwx------]  acme-v01.api.letsencrypt.org
│       └── [drwx------]  directory
│           └── [-r--------]  default.json
├── [drwx------]  domain.tld
│   └── [-rw-------]  key.pem
└── [drwx------]  subdomain.domain.tld
    └── [-rw-------]  key.pem
```

I don't see the point of restricting read permissions of certificate, chain, fullchain and dhparam as all those are meant to be publicly available in the end.

**Comment by buchdag** [comment]
@JrCs any thought on this ? Should we lower the read permissions on the private keys and ACME account keys ?

**Comment by P4sca1** [comment]
I think so, however we need to make sure that `nginx` can still read the certificates.
By default `letsencrypt-companion` saves the certificates as `root`, so they won't be readable by `nignx` if we change permissions. An option to specify under which user the `letsencrypt-companion` runs would be sufficient, maybe?

**Comment by buchdag** [comment]
`nginx` won't have any issues, its master process run as root.

**Comment by P4sca1** [comment]
Ah, you're right.

**Comment by buchdag** [comment]
BTW I did a quick test with [the permission changes I suggested](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/412#issuecomment-403144655) ~ a month ago and didn't run into any issue.

**Comment by JrCs** [comment]
If the nginx process can read the certs files it's good.

**Comment by Byteflux** [comment]
Would it be possible to make the permissions configurable through environment variables or some other mechanism? I share my certs volume with other containers that have processes which don't run as root and need to be able to read the certificates.

**Comment by buchdag** [comment]
It should be possible, yes. 

Do you think the permissions check should be enabled or disabled by default ?

**Comment by buchdag** [comment]
Thanks for the feedback. I'm working on changes to the permissions checks that will allow customisations through environment variables. In the meantime please use tagged image `v1.9.1` as is does not include the permissions checking code.

**Comment by AndreMarthaler** [comment]
Hi.

Question:

1) I use RabbitMQ Server with Webinterface behind nginx proxy with HTTPS Cert generated by Letsencrypt.
2) I use RabbitMQ AMPS (TCP with SSL) for connecting my application. For that, i use generated letsencrypt cert and private key easily linked into my rabbitmq container.

Now, RabbitMQ Server can't read private key file, because it's root only owned, nothing group or public read.

I understand this point of security, but is there any way (configurable or anything like that) to give the possibility to read certs and keys to other user to make it accessible by other applications?

Might be great, to find a way to make certs and keys sharable to other apps.

**Comment by buchdag** [comment]
Hi.

Please fall back to tagged version `v1.9.1` and manually change permissions of the private keys with `docker exec` and `chmod`.

Again a PR allowing more customization is on its way ASAP but I'm really really short on time those days.

You can have a look a the intended changes [there](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Persistent-data#ownership--permissions-of-private-keys-and-acme-account-keys), any feedback is more than welcome.

**Comment by buchdag** [comment]
`docker exec your-le-container-name bash -c 'chmod a+r /etc/nginx/certs/*.key'`
