### ISSUE TITLE
default redirect all subdomains  to https? why ? 

### ISSUE THREAD

**Issue by saytik** [JrCs/docker-letsencrypt-nginx-proxy-companion#413]
Hi

have the same problem as https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/293 
HTTPS_METHOD=nohttp    why do i  need it set all subdomains containers  ? 
I set -e "LETSENCRYPT_HOST=main-domain.com,www.main-domain.com" only for one. container with main domain. But nginx-proxy set redirect to https for all containers with subdomains crm.main-domain.com and other. But i don't don't need default redirect to https for all subdomains ....

for  example jenkins.prod.main-domain.com, i haven't set https for it.
But nginx-proxy set redirect  

> # jenkins.prod.main-domain.com
> upstream jenkins.prod.main-domain.com {
> 				## Can be connected with "bridge" network
> 			# jenkins
> 			server 172.17.0.14:8080;
> 				# Cannot connect to network of this container
> 				server 127.0.0.1 down;
> }
> server {
> 	server_name jenkins.prod.main-domain.com;
> 	listen 80 ;
> 	access_log /var/log/nginx/access.log vhost;
> 	return 301 https://$host$request_uri;
> }
> server {
> 	server_name jenkins.prod.main-domain.com;
> 	listen 443 ssl http2 ;
> 	access_log /var/log/nginx/access.log vhost;
> 	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
> 	ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
> 	ssl_prefer_server_ciphers on;
> 	ssl_session_timeout 5m;
> 	ssl_session_cache shared:SSL:50m;
> 	ssl_session_tickets off;
> 	ssl_certificate /etc/nginx/certs/main-domain.com.crt;
> 	ssl_certificate_key /etc/nginx/certs/main-domain.com.key;
> 	ssl_dhparam /etc/nginx/certs/main-domain.com.dhparam.pem;
> 	ssl_stapling on;
> 	ssl_stapling_verify on;
> 	ssl_trusted_certificate /etc/nginx/certs/main-domain.com.chain.pem;
> 	add_header Strict-Transport-Security "max-age=31536000" always;
> 	include /etc/nginx/vhost.d/default;
> 	location / {
> 		proxy_pass http://jenkins.prod.main-domain.com;
> 	}
> }

You can see it uses ssl from main domain ssl_certificate /etc/nginx/certs/main-domain.com.crt;

P.S. Sorry for my english

**Comment by buchdag** [comment]
Hi

Is it the same as this issue ? https://github.com/jwilder/nginx-proxy/issues/1164

**Comment by saytik** [comment]
yes

**Comment by buchdag** [comment]
The is an nginx-proxy issue then, closing this one.
