### ISSUE TITLE
503 for default or non-existent virtual hosts

### ISSUE THREAD

**Issue by mcnesium** [JrCs/docker-letsencrypt-nginx-proxy-companion#416]
There should be a 503 or something, if a request comes in on a domain or IP address that is not defined by `VIRTUAL_HOST` env var. Instead, it just redirects to the first defined one.

According to [this](https://serverfault.com/a/329953) there must be a `default` added to the default `listen`-directive, for which I assume [here is the right place](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L94). This file gets re-generated each time the proxy container starts though.

Is this within the scope of this project or rather upstream at [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy)?

**Comment by buchdag** [comment]
According to the answer from server fault that you quoted:

> If you omit the default parameter, the first server block is treated as the default.

So [this](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L94) `server` block is already the default.

I think you issue is instead yet another duplicate of #74, #373 and #411 

If it is, could you close this issue and continue the discussion on #411 ?

**Comment by mcnesium** [comment]
Looks like it. My experience with nginx is very little, I can only compare it to Apache's `000-default.conf` that prevents requests to arbitrary domains/IP-addresses to reach a wrong web service.
