### ISSUE TITLE
tls-sni-01 support?

### ISSUE THREAD

**Issue by ammmze** [JrCs/docker-letsencrypt-nginx-proxy-companion#42]
I don't know much about the underlying client used here ([simp_le](https://github.com/kuba/simp_le)...doubtful it supports this), but would it be possible to support the tls-sni-01 challenge mode? It does require running the client in [standalone mode](http://letsencrypt.readthedocs.org/en/latest/using.html#standalone) (again probably only supported in the official client). The use case is when one can't/doesn't want to have their site publicly accessible via port 80, so the challenges would need to happen over port 443.

**Comment by JrCs** [comment]
@ammmze this container is a compagnion to nginx in reverse proxy mode.
It is not designed to work in "standalone" mode.
I think you must use a dedicated container (with the official letsencrypt client) to do it.
