### ISSUE TITLE
Every unknown https domain/subdomain redirected to the first active container ?

### ISSUE THREAD

**Issue by dridri** [JrCs/docker-letsencrypt-nginx-proxy-companion#420]
Looks like there is some default feature that should not be default.
This behavior only happens with HTTPS (HTTP works correctly) : every unknown host is proxied to the first active container.

For example considering a container with VHOST=sub1.domain.com : opening domain.com / sub2.domain.com / *.domain.com in my web browser should give me a server-not-found error.
But it actually throws me on the first container available, in this case the one with sub1.domain.com, hence when I browse to sub2.domain.com, I end up in index page of sub1.domain.com.

This also happens directly with domains : if domain2.com is on the same machine as domain.com, and no domain2.com container is active, every https calls end up on the sub1.domain.com

This does not look very secure to me.
(Actually, I don't know if it's directly nginx related or letsencrypt related, so I post this issue here first)

**Comment by dridri** [comment]
Looks like I'm duplicating existing issues, closing

**Comment by buchdag** [comment]
@dridri the discussion is actually on #411
