### ISSUE TITLE
How does it get Env vars from other containers to retrieve the cert

### ISSUE THREAD

**Issue by maxpavlov** [JrCs/docker-letsencrypt-nginx-proxy-companion#425]
Hello. Sorry for using issues section to ask in general how the process of obtaining an SSL through acme happens in companion setup.

In my understanding, a container with nginx also has letsencrypt client onboard. 
Now after running a companion container, after some time, I decided to start the web app on its own domain. Having DNS records point to an external IP of the docker host, I spin up a container specifying Letsencrypt and virtual host environment variables in docker run. I also attach an app container to a shared network where nginx is. Those env are passed into that particular app container, but how does the nginx and letsencryp know that new app's domain to try to retrieve it's SSL?

**Comment by buchdag** [comment]
Hi

The magic happens thanks to [docker-gen](https://github.com/jwilder/docker-gen), a go program that render templated files from container metadatas (which it gets from a docker API endpoint, either the host docker socket exposed inside the container or a tcp endpoint).

You have two docker-gen processes running when you use nginx-proxy with letsencrypt-nginx-proxy-companion : 
- one to render nginx's default.conf from [nginx.tmpl](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl) (this one run either [inside the nginx-proxy container](https://github.com/jwilder/nginx-proxy/blob/a28571765744b6523aea629efc8f657a5fa2c8ef/Procfile#L1) or on its own docker-gen container in the three container setup).
- the other to render the letsencrypt_service_data file from [letsencrypt_service_data.tmpl](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/app/letsencrypt_service_data.tmpl) ([this one run inside the letsencrypt-nginx-proxy-companion container](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/7a3b918a41526531b367f30d035964a7222e17fa/app/start.sh#L19)).

**Comment by maxpavlov** [comment]
Thank you very much @buchdag.
