### ISSUE TITLE
Help please! can't write to /etc/nginx/certs

### ISSUE THREAD

**Issue by aOjRb6W8Y260s66O** [JrCs/docker-letsencrypt-nginx-proxy-companion#427]
I just follow the [usage](/etc/nginx/certs),and run the codes in Example of use step by step.
![aa](https://user-images.githubusercontent.com/6308331/44138721-705d6db0-a0a7-11e8-9332-a9b3a0689f43.JPG)

However, the second container for jrcs/letsencrypt-nginx-proxy-companion exits itself, and can't start successfully neighter. 

console shows that:  can't write to /etc/nginx/certs

system: centos 7 of linode.com

what I have try:

1 change "-v /path/to/certs:/etc/nginx/certs:ro" to "-v /path/to/certs:/etc/nginx/certs:RW" when I run the first container
2 rebuild the system many times
3 run "chmod 777 /path" in localhsot

any help and advice is welcome

**Comment by buchdag** [comment]
Can you try to put `-v /path/to/certs:/etc/nginx/certs/:rw` after `--volumes-from nginx-proxy` in the letsencrypt container `docker run` command ?

**Comment by aOjRb6W8Y260s66O** [comment]
@buchdag thanks,
However, it does work.
First, I removed all the containers and images and the folder "/path/".
Second, I run the command as follow:
 

> [root@li1709-210 ~]# docker run -d -p 80:80 -p 443:443 \
>     --name nginx-proxy \
>     -v /path/to/certs:/etc/nginx/certs:ro \
>     -v /etc/nginx/vhost.d \
>     -v /usr/share/nginx/html \
>     -v /var/run/docker.sock:/tmp/docker.sock:ro \
>     --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy \
>     jwilder/nginx-proxy
Unable to find image 'jwilder/nginx-proxy:latest' locally
Trying to pull repository docker.io/jwilder/nginx-proxy ...
latest: Pulling from docker.io/jwilder/nginx-proxy
f2aa67a397c4: Pull complete
3c091c23e29d: Pull complete
4a99993b8636: Pull complete
75850836e146: Pull complete
62836acd3c37: Pull complete
5d70eba6906f: Pull complete
fe86498801b9: Pull complete
8ec6361273ec: Pull complete
4aa76dcb8305: Pull complete
921c7f44ab5e: Pull complete
Digest: sha256:4e6bae63dab0c4d3ebf3bbecbf5cd2700ca99db02e155efaa6e28baa14033bc8
Status: Downloaded newer image for docker.io/jwilder/nginx-proxy:latest
42e0ffb29a84ef67cd7f8801948053676ae1deef882cbd1aa15a63a7034dd819

> [root@li1709-210~]# docker run -d \
>     -v /var/run/docker.sock:/var/run/docker.sock:ro \
>     --volumes-from nginx-proxy \
>     -v /path/to/certs:/etc/nginx/certs:rw \
>     jrcs/letsencrypt-nginx-proxy-companion
Unable to find image 'jrcs/letsencrypt-nginx-proxy-companion:latest' locally
Trying to pull repository docker.io/jrcs/letsencrypt-nginx-proxy-companion ...
latest: Pulling from docker.io/jrcs/letsencrypt-nginx-proxy-companion
8e3ba11ec2a2: Pull complete
7dcb73d5f119: Pull complete
1b4976a67702: Pull complete
32bac96dff28: Pull complete
8dba44deea8f: Pull complete
d00b9caf89e7: Pull complete
Digest: sha256:4a024004451c5a991f3345dbfb3dddd2c73a87f80d93819d3797ad6c9bb8b2dd
Status: Downloaded newer image for docker.io/jrcs/letsencrypt-nginx-proxy-companion:latest
dffde7166403d80dba8ad5c9590066723d6f9b7c60bc6e508df14a89c9ef3458

> [root@li1709-210~]# docker ps -a
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                      PORTS                                      NAMES
dffde7166403        jrcs/letsencrypt-nginx-proxy-companion   "/bin/bash /app/en..."   17 seconds ago      Exited (1) 14 seconds ago                                              suspicious_davinci
42e0ffb29a84        jwilder/nginx-proxy                      "/app/docker-entry..."   58 seconds ago      Up 57 seconds               0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx-proxy
[root@li1709-210 ~]#

as you see, the second container Exited again.
Then, remove containers again, I try to run the first command without "-d", as follow:

> [root@li1709-210 ~]# docker run -p 80:80 -p 443:443 \
>     --name nginx-proxy \
>     -v /path/to/certs:/etc/nginx/certs:ro \
>     -v /etc/nginx/vhost.d \
>     -v /usr/share/nginx/html \
>     -v /var/run/docker.sock:/tmp/docker.sock:ro \
>     --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy \
>     jwilder/nginx-proxy
WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
forego     | starting dockergen.1 on port 5000
forego     | starting nginx.1 on port 5100
dockergen.1 | 2018/08/15 11:54:25 Generated '/etc/nginx/conf.d/default.conf' from 1 containers
dockergen.1 | 2018/08/15 11:54:25 Watching docker events
dockergen.1 | 2018/08/15 11:54:25 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
2018/08/15 11:55:26 [notice] 39#39: signal process started
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
dhparam generation complete, reloading nginx

IT seems like that the command can't be finished. It may be something wrong with the first container lets the second container exited, is that right?

Is there anything else I can try? by the way, I once to run these two commands successfully months ago in the same server with the same system.

**Comment by buchdag** [comment]
Try using a [named or anonymous docker volume](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Persistent-data) for `/etc/nginx/certs` instead of a bind volume and/or try not using `:ro` on the volume mounted to nginx-proxy `/etc/nginx/certs` unless your absolutely needs to.

**Comment by aOjRb6W8Y260s66O** [comment]
@buchdag thanks again, it works by follow the [basic usage](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Basic-usage), named volume.
