### ISSUE TITLE
Question about Separate Containers

### ISSUE THREAD

**Issue by mfilej** [JrCs/docker-letsencrypt-nginx-proxy-companion#43]
Hello, thank you for making this, I can't believe how easy it was to get started. :smile: 

I would like to ask a question.

I followed the instructions at the beginning of the readme. Now I'm wondering if I should make this work in the way it is described under _Separate Containers_.

What are the security implications of not doing this?

I'm not sure I quite understand this sentence:

> You may want to do this to prevent having the docker socket bound to a publicly exposed container service.

Thanks!

**Comment by JrCs** [comment]
Using the nginx-proxy container the docker socket is bind into the container. So if the nginx-proxy container is compromised the attacker ca use the docker socket to do some bad things.
If you use the _Separate containers_, the docker socket is not bind into the nginx container, that is much better in a security point of view.

**Comment by mfilej** [comment]
Got it, thanks for the response!
