### ISSUE TITLE
Problem with SAN Certificate

### ISSUE THREAD

**Issue by AlexCloudDev** [JrCs/docker-letsencrypt-nginx-proxy-companion#430]
Hi folks,
i hope, somebody can help me:

I have set up a nginx-proxy, docker-gen and letsencrypt-nginx-proxy-companion container to proxy my nginx-webserver. 
The webserver container was started with
`-e VIRTUAL_HOST=bar.net
 -e LETSENCRYPT_HOST=bar.net`
and everything works well.

But now i want to add a xmpp container which needs certificates for:
`foo.bar.net
a.foo.bar.net
b.foo.bar.net
c.foo.bar.net
`
So i tried to start it with:
`-e VIRTUAL_HOST=foo.bar.net,a.foo.bar.net,b.foo.bar.net,c.foo.bar.net
 -e "LETSENCRYPT_HOST=foo.bar.net,a.foo.bar.net,b.foo.bar.net,c.foo.bar.net`

and with:
`-e VIRTUAL_HOST=foo.bar.net
 -e "LETSENCRYPT_HOST=foo.bar.net,a.foo.bar.net,b.foo.bar.net,c.foo.bar.net`

to create a SAN certificate, but both didn't work out.

I have read many posts at this github, some say only one url is required at VIRTUAL_HOST, some say VIRTUAL-HOST needs the same urls like LETSENCRYPT_HOST and so on.

Please help me.

I assume it has something to do with the second level domain bar.net ?
Maybe you can't create a SAN certificate for third level without containing the second level??
So i have to create it at the first container?
I don't know.

Thank you ver much 

regards

**Comment by buchdag** [comment]
You need all domains in both `*_HOST` variables. Can you share the logs of the letsencrypt container ? Be advised that those logs and the eventual links to LE logs will contain your domains in clear, so either anonymize them or share the logs privately if you don't want your domains to be made public here.

**Comment by AlexCloudDev** [comment]
Thank you for your help.

I solved the problem. It was a bad configuration at my domain zonefile. 

But thx to you i know now that i need all domains in both variables.

Sorry, my fault.
