### ISSUE TITLE
Need i386 image

### ISSUE THREAD

**Issue by Turmer** [JrCs/docker-letsencrypt-nginx-proxy-companion#432]
Is there a way to find docker-letsencrypt-nginx-proxy-companion image for i386 architecture? If not - is there a way to generate it? If you could point at the image or some guide to generate one - it would be much appreciated. Thanks!

**Comment by buchdag** [comment]
Have you tried building the Dockerfile directly on your i386 host ?

**Comment by Turmer** [comment]
No I have not - was hoping to find the image. Managed to find the lmdcrash/i386-certbot and cobble together some autorenewal functionality with cron, but would love to experience the power of docker-letsencrypt-nginx-proxy-companion.
If there is no image for i386 architecture, any pointers to a guide/tutorial on building  docker-letsencrypt-nginx-proxy-companion on i386 host would be much appreciated.

**Comment by buchdag** [comment]
We're not offering native multiarch images from Dockerhub yet because that's a real pain to setup (it involves either shoehorning qemu into the base image or having your own Jenkins -or similar- infrastructure, with agents for every target archs).

Building the image locally is easy:

```bash
git clone https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion.git
cd docker-letsencrypt-nginx-proxy-companion
docker build -t jrcs/letsencrypt-nginx-proxy-companion .
```

But i'm not sure `docker-gen` will build on alpine + i386. Let me know if that work or not.

**Comment by Turmer** [comment]
Thanks!
The last command ends with error:
Sending build context to Docker daemon 44.03 kB
Step 1/15 : FROM golang:1.10-alpine AS go-builder
Error parsing reference: "golang:1.10-alpine AS go-builder" is not a valid repository/tag: invalid reference format
Just in case, my 32-it host is Ubuntu 16.04 box with Docker version 17.03.2-ce, build f5ec1e2

**Comment by buchdag** [comment]
Oh, our Dockerfile use [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/), you'll need at least Docker 17.05 to build it.

**Comment by Turmer** [comment]
Any suggestions how to upgrade my Docker to 17.05? The one I have seems to be the latest version for 32-bit Ubuntu I was able to find.

**Comment by buchdag** [comment]
I built an alpine-linux/i386 version of docker-gen, uploaded it to my fork of docker-gen on a new tag, and created a non multi-stage Dockerfile that should work for i386.

```bash
git clone https://github.com/buchdag/docker-letsencrypt-nginx-proxy-companion.git
cd docker-letsencrypt-nginx-proxy-companion
git checkout i386
docker build -t jrcs/letsencrypt-nginx-proxy-companion -f Dockerfile.i386 .
```

**Comment by Turmer** [comment]
Thanks much for your help - it built successfully! I am going to play with the image and report back.
I am stuck with this archaic i386 box for now, but planning to phase it out as soon as circumstances allow.

**Comment by Turmer** [comment]
Happy to report that container based on the locally built image starts and stay up. It will take some time to test the functionality. BTW, could you please recommend some generic test to ensure that docker-letsencrypt-nginx-proxy-companion container works as intended?

**Comment by buchdag** [comment]
I'd say just follow the [basic usage](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Basic-usage) example, then use the [forced renewal script](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#force-certificates-renewal) to see if renewal works.

**Comment by Turmer** [comment]
Thanks much for your help!
Basic usage example takes me to the next stumbling block with nginx-proxy for which I cannot find the  i386 image. Tried building nginx-proxy locally with docker-gen-linux-i386, which went through successfully, but does not run because it needs i386 forego binary. Do you by any chance know where I can find either the i386 image of nginx-proxy or i386 binary of forego?

**Comment by buchdag** [comment]
Yeah, I was expecting nginx-proxy to be an issue too. I don't think forego has i386 binaries available but as it's golang it can be cross compiled like I did with docker-gen. I'll try to patch something together tomorrow.

**Comment by Turmer** [comment]
Thanks, any help with this is much appreciated.

**Comment by buchdag** [comment]
```bash
git clone https://github.com/buchdag/nginx-proxy.git
cd nginx-proxy
git checkout i386
docker build -t jwilder/nginx-proxy -f Dockerfile.i386 .
```

As usual let me know if this work or not.

**Comment by Turmer** [comment]
Thanks a lot! It builds successfully and both nginx-proxy and docker-letsencrypt-nginx-proxy-companion containers are up and running. No more architecture-related error messages. Quick poking through logs indicates that everything seems to be normal with both containers. Will try the basic usage example and the forced renewal as suggested and report the results.

**Comment by Turmer** [comment]
Tested both the basic usage example and the forced renewal script along with certificates status - everything seems to work as intended. Thanks again for your help! 
Although it is not directly related to the original topic, now running into elasticsearch for which there is no supported i386 version.  Any recommendation where I can find i386 elasticsearch or whether it is possible to build one locally?

**Comment by buchdag** [comment]
Glad everything finally works ok. I'm closing the issue as this the letsencrypt-nginx-proxy-companion part is resolved.

No idea for the i386 Elasticsearch Docker image, you'll have to ask on their repo.
