### ISSUE TITLE
Restart Containers on Cert Renewal

### ISSUE THREAD

**Issue by Greek64** [JrCs/docker-letsencrypt-nginx-proxy-companion#434]
SCENARIO:
Let's say you have a micro-service that doesn't only serve HTTP traffic, but also other kind of traffic (e.g. FTP).
Now let's say that we do not only want to encrypt the web traffic, but also the ftp traffic (using FTPS). This can be done easily by integrating the keys generated by the letsencrypt-companion into the FTP container and use them for FTPS.

The problem now arises on Cert renewal. While the letsencrypt-companion restart the nginx reverse-proxy container (meaning that the web traffic uses the new certificates), the FTP container still uses the old ones and also needs to be restarted.

SUGGESTION:
Add an extra environmental variable (e.g. LE_RESTART), that if set true, signals the letsencrypt-companion to restart the respective container.
To avoid overheads, it would also make sense to additionally check the LETSENCRYPT_HOST and only restart if the respective cert of the container is renewed.

**Comment by buchdag** [comment]
I get the idea and see how it could be useful but that's going pretty far from the original project scope.

**Comment by Greek64** [comment]
Hmm, I understand that (even going by the name) the companion is thought to interact only with the nginx container and (if seperate) the docker-gen container.
But the functionality requested is perfect for docker-letsencrypt-nginx-proxy-companion and can be implemented in a few lines. (only adding additional calls to "docker-kill" function).

If I make a PR, will it be merged?
I mean I can always fork the repo and do what I want (which is probably what you are going to suggest to me), but I'm unsure how long I will be able to keep it up to date with this one.

**Comment by Greek64** [comment]
Due to some personal issues I have not had the time yet, but I will fork and make a PR in the next 2-3 weeks.

**Comment by Greek64** [comment]
So, PR is live and the fork can be found [here](https://github.com/Greek64/docker-letsencrypt-companion).  
Due to the unsure nature of the merging of this PR, I will *try* to keep the fork updated with this repo for as long as possible.

**Comment by Greek64** [comment]
@bplein 
If you want a working le-companion that restarts containers NOW, head over to [Greek64/docker-letsencrypt-companion](https://github.com/Greek64/docker-letsencrypt-companion), download/pull the master branch, and build the le-companion from the downloaded dockerfile.
This will build the latest le-companion release with the requested feature.  
As said above, I will try to keep that repo updated until this PR gets merged.

I'm not entirely sure if what you suggest - having the same LETSENCRYPT_HOST on different containers with different VIRTUAL_PORTS - will work.  
What I can say though is, that the le-companion only uses the LETSENCRYPT_* environmental variables. The VIRTUAL_* (and by that the key VIRTUAL_PORT) environmental variables are used directly by the nginx.  
It now comes down to if le-companion can have the same LETSENCRYPT_HOST for multiple containers, where it uses the same certs, but also checks for renewal for all containers (which would be necessary to restart all containers when a renewal happens). My bash-fu is not at a high level, but I guess the "groupBy" and "trim" commands in letsencrypt_service_data.tmpl would prevent this.

I would suggest doing something like in [Mailu](https://github.com/Mailu/Mailu), where the nginx of the front-end (WebGUI) is also responsible for the encryption and forwarding of all relevant ports (IMAP, POP3, etc). This would allow you to only have to "link" the mailcow front container with le-companion.

**Comment by bplein** [comment]
THanks. 

I prefer to have my own independent proxy in front of mailcow and all other containers. It's a more general approach and allows me to customize the proxy and not be concerned that maybe the application (mailu, mailcow, nextcloud, etc.) is going to make a change to the proxy that might break things.
