### ISSUE TITLE
Adding 301 redirect for WWW to nonWWW

### ISSUE THREAD

**Issue by tonysworking** [JrCs/docker-letsencrypt-nginx-proxy-companion#438]
I've been trying all day, basically tossing darts at a dart board.

if anyone can show me a solution for this it would be greatly appreciated.

My main problem is i don't know when or where to add:

server {
    listen 80;
    listen [::]:80;
    server_name www.example.com;
    return 301 https://$host$request_uri;
}

or if that server block is even effective,

My node app works on the domain name, when i run the image:

docker run -d -e VIRTUAL_HOST=www.example.com,example.com \
              -e LETSENCRYPT_HOST=example.com,www.example.com \
              -e LETSENCRYPT_EMAIL=email@email \
              --network=webproxy \
              --name my_app \
              application

anyone know how to get this to work.

**Comment by buchdag** [comment]
Hi.

This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

What you want to achieve depends entirely on the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different peoples.

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)
