### ISSUE TITLE
Generate cert for a non dockerised domain

### ISSUE THREAD

**Issue by leokun** [JrCs/docker-letsencrypt-nginx-proxy-companion#445]
Hello there,

I would like to be able to generate and renew cert for a external website.

For example, I have one domain example.mydomain.com running on my computer on port 8765 with his own nginx/apache/... 

In nginx-proxy I have a __example.conf__ maped in `/etc/nginx/conf.d/example.conf` with everithing I need to redirect to my upstream 127.0.0.1:8765.

And it works, It's also worked with ssl by creating a dummy docker using the same __example.mydomain.com__ but I cant renew it.

As it is possible to add a conf file in nginx-proxy, is there any way to say to the companion thet he should create also this certificate ?

I really hope I make myself clear, as I am not native english speaking person.

Thanks a lot
Leo

**Comment by buchdag** [comment]
@leokun please take a look at https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Standalone-certificates-(beta) and the discussion in #368 

This feature is in `jrcs/letsencrypt-nginx-proxy-companion:dev`

I'm closing this issue so we can stay focused on #368

**Comment by leokun** [comment]
Love that ! Thank you !
