### ISSUE TITLE
problems adding a node-express rest api

### ISSUE THREAD

**Issue by tonysworking** [JrCs/docker-letsencrypt-nginx-proxy-companion#447]
I have an app running on port 3000 which is https://www.example.com

then i have an api running on 2030 which is https://www.api.example.com

the problem is I am unable to reach my routes
	one of my routes being user
	ie: https://www.api.example.com/users = should return JSON list of users.
	I get no response and the server times-out.

I tried adding a proxy_pass in the vhost section but then https://www.api.example.com doesn't respond.

I'm by no means a NGINX expert in fact quite the opposite so any help with this would be much appreciated.

My main question is can I add some code to VHOST to solve my problem,
		
		ex: in vhost dir - www.api.example.com (tried and failed experiment)
		
		location /users {

			proxy_pass: www.api.examples.com/users
		}

**Comment by buchdag** [comment]
Hi.

This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

What you want to achieve depends entirely on the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different peoples.

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)
