### ISSUE TITLE
Entrypoint script should check for writable `$VHOST_DIR`

### ISSUE THREAD

**Issue by DrMurx** [JrCs/docker-letsencrypt-nginx-proxy-companion#451]
`functions.sh` declares a tuneable variable `VHOST_DIR` (defaulting to `/etc/nginx/vhost.d`) which allows to customize the location where the `acme-challenge` location file is placed.

Yet, the `entrypoint.sh` insists directory at `/etc/nginx/vhost.d` in [line 159](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/212e25134a1dea60514c7085bf546d32e81a4a26/app/entrypoint.sh#L159)

**Comment by buchdag** [comment]
Hi.

`/etc/nginx/vhost.d` and the `VHOST_DIR` variable in function.sh are not where the acme challenge file are created but the location of the nginx vhost configuration files. I have no idea of why this is a variable in `functions.sh`, that's probably a leftover that serve pretty much no purpose now (you can't even set the vhost conf location on `nginx-proxy`).

The location of the challenge file is `/usr/share/nginx/html` and is not tuneable.

**Comment by DrMurx** [comment]
> /etc/nginx/vhost.d and the VHOST_DIR variable in function.sh are not where the acme challenge file are created but the location of the nginx vhost configuration files.

That's what I meant. My bad.

But here's the reasoning why it's a good idea to allow customizing the location of the companion vhost snippets: I use my own configuration template for nginx-proxy, and since I have already some custom configuration for specific hosts in my `vhost.d` directory, I want the companion to use a dedicated directory for its own snippets.

It's always good to have a default configuration which makes things work out-of-the-box, but it's also good to give users the possibility to customize via configuration options.
