### ISSUE TITLE
Separated machine web

### ISSUE THREAD

**Issue by Judhianto** [JrCs/docker-letsencrypt-nginx-proxy-companion#456]
Dear All,

I have installation of docker jwilder/nginx-proxy  and jrcs/letsencrypt-nginx-proxy-companion 

The configuration is working perfectly to redirect several dockerized web in the same machine. But i want to using this configuration to redirect traffic to one web located in separated machine.

I tried to put vhost file in  /etc/nginx/vhost.d  folder and it work to provide http connnection but can not provide https connection.

Below is the content of my vhost file:

    upstream www.abc.xxx {server 10.234.16.26}

    server{
    server_name www.abc.xxx ;
    listen 80 ;
    access_log /var/log/nginx/access.log vhost ;
    include /etc/nginx/vhost.d/default;
    location / {
    proxy_pass http://www.abc.xxx ;
    }
    }

    server {
    server_name www.abc.xxx ;
    listen 443 ssl http2 ;
    access_log /var/log/nginx/access.log vhost;
    return 500;
    ssl_certificate /etc/nginx/certs/default.crt;
    ssl_certificate_key /etc/nginx/certs/default.key;
    }

Can someone show me the example of the correct vhost file? 
this configuration can serve traffic for http but not https

Thank You !

**Comment by buchdag** [comment]
Hi.

This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

What you want to achieve depends entirely on the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different peoples.

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)
