### ISSUE TITLE
 proxy_read_timeout setting for nginx generated configuration

### ISSUE THREAD

**Issue by maxpavlov** [JrCs/docker-letsencrypt-nginx-proxy-companion#459]
Hello. 

I've been able to configure much of the parameters that affect how nginx rule for my container is set up, but docker-gen doesn't provide a way to supply a values for two nginx parameters I need. Those as:

- proxy_read_timeout
- proxy_send_timeout

Please advise on the best way I can do this so I can supply those values somehow at container startup.

**Comment by buchdag** [comment]
Hi.

This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

What you want to achieve depends entirely on the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different peoples.

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)
