### ISSUE TITLE
How to restrict a site to internal LAN?

### ISSUE THREAD

**Issue by thayneq** [JrCs/docker-letsencrypt-nginx-proxy-companion#469]
Is it possible to have some sites be publicly accessible from the internet, and others not accessible? I looked into using NETWORK_ACCESS=internal on nginx-proxy, but that doesn't work because nginx always sees the gateway IP of docker (172.x.x.x), so it can't discriminate LAN from WAN.

I also tried using the "internal" tag on the docker network for nginx, but that restricted it entirely to the 172 domain, rendering listening on port 80 publicly rather useless. I'm stumped......

**Comment by buchdag** [comment]
Hi.

This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

What you want to achieve depends entirely on the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different peoples.

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)
