### ISSUE TITLE
Multiple certificates with different VIRTUAL_ROOT

### ISSUE THREAD

**Issue by Divxtaman** [JrCs/docker-letsencrypt-nginx-proxy-companion#474]
Currently, I am creating certificates like this
```
VIRTUAL_HOST = "domain.com,www.domain.com,mail.domai.com"
LETSENCRYPT_HOST = "domain.com,www.domain.com,mail.domai.com"
"VIRTUAL_ROOT=/var/www/public"
```

They all use the same VIRTUAL_ROOT directory, is it possible to set different root for sub-domain? such as I would like to point mail.domain.com to roundcube and `domain.com,www.domain.com` to main site.

Thanks

**Comment by buchdag** [comment]
Hi.

This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

What you want to achieve depends entirely on the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different peoples.

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)
