### ISSUE TITLE
ERROR:simp_le:1446:problem with cert

### ISSUE THREAD

**Issue by cmazzw** [JrCs/docker-letsencrypt-nginx-proxy-companion#475]
here is my setup:
`version: '2'

services:

  wordpress:
    image: wordpress:4.7-apache
    environment:
      WORDPRESS_DB_PASSWORD: 123456
      VIRTUAL_HOST: cloud.hljmdc.org
      LETSENCRYPT_HOST: cloud.hljmdc.org
      LETSENCRYPT_EMAIL: mymail

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"`

this is from 
https://github.com/dmitrym0/simple-lets-encrypt-docker-compose-sample.
but docker-compose logs   show 
`letsencrypt-nginx-proxy-companion_1_34b95a1414a4 | 2018-11-30 11:36:38,296:ERROR:simp_le:1446: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/EC4uA8vpxTfD4qgI2ASYHczY9cR2rSdrrzQiUBCsdCo
letsencrypt-nginx-proxy-companion_1_34b95a1414a4 | 2018-11-30 11:36:38,303:INFO:simp_le:360: Saving account_key.json
letsencrypt-nginx-proxy-companion_1_34b95a1414a4 | Challenge validation has failed, see error log.`

what can I do?thank you!

**Comment by cmazzw** [comment]
> https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Invalid-authorizations#your-domain-name-does-not-resolve-to-your-host-ipv4-andor-ipv6

hi ,thank you!
but this simp_le:1446 is not sovle.
1、docker run -d -p 80:80 -p 443:443 --name nginx-proxy -v /path/to/certs:/etc/nginx/certs:ro -v /etc/nginx/vhost.d -v /usr/share/nginx/html -v /var/run/docker.sock:/tmp/docker.sock:ro --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy jwilder/nginx-proxy
2、docker run -d  -v /path/to/certs:/etc/nginx/certs:rw  -v /var/run/docker.sock:/var/run/docker.sock:ro     -e DEBUG=true  --volumes-from nginx-proxy     jrcs/letsencrypt-nginx-proxy-companion
3、docker run -d -e "VIRTUAL_HOST=cloud.hljmdc.org" -e "LETSENCRYPT_HOST=cloud.hljmdc.org" -e "LETSENCRYPT_EMAIL=zzw.0111@qq.com" wordpress:4.7-apache

but logs show below:
2018-12-01 03:17:51,688:ERROR:simp_le:1446: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/QlPY8J0xNELNQfHAZD3XS_ca1ExNnkrwst0H2Gq_n48
2018-12-01 03:17:51,692:INFO:simp_le:360: Saving account_key.json
2018-12-01 03:17:51,693:DEBUG:simp_le:1165: Removing validation file at /usr/share/nginx/html/.well-known/acme-challenge/Rs7AbSTB87_iPlAYlUTW8T7p8A5nI0_T2GI0mDd3MtM
Challenge validation has failed, see error log.
my domain DNS is private ,is that allow?

**Comment by buchdag** [comment]
Nope, that does not work with the validation method used by `simp_le`. The domain you want to issue a cert for has to be public and reachable.

**Comment by cmazzw** [comment]
> 不，这不适用于使用的验证方法`simp_le`。您要颁发证书的域必须是公开且可访问的。

I see!thank you!
