### ISSUE TITLE
Local Test Suite Failing

### ISSUE THREAD

**Issue by Greek64** [JrCs/docker-letsencrypt-nginx-proxy-companion#482]
Running the local test suite on the `master` like described [here](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/tree/master/test) fails on my local Debian 8 system.
But running the local test suite on the `v.1.9.1` tag works as expected.

I traced the problem back to commit (2adfddc48688f998cd899cab31c0b58d261be8ff).

The problem is, that since the nginx container is now directly connected to the `boulder_bluenet`, and the said network is created in the docker-compose file of the `boulder-setup`, trying to create a nginx container before running the `boulder-setup` will fail, because the network does not exist yet.
This was handled in the commit by switching the order in the `.travis.yml` file for the Travis build, but was not done in the `setup-local.sh` file.

So, a simple swap of [line 78](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/4f0e2140a445ce570f8829b56723f6b429115060/test/setup/setup-local.sh#L78) with line 79 will fix this problem.
It is also necessary to swap the order during the `--teardown` phase, to avoid the `Networks points still active` docker error.

It would also make sense to enable `set -e` in the `setup-local.sh` script, to prevent the script from continuing when an error is encounter (It took me longer than I want to admit to realize, that there was an Error message in the output of the setup script)

If needed I can make a PR with the changes, but I think they are easy to do "on the fly".

**Comment by buchdag** [comment]
fixed by #483
