### ISSUE TITLE
Compatibility with CoreOS Rkt

### ISSUE THREAD

**Issue by julianxhokaxhiu** [JrCs/docker-letsencrypt-nginx-proxy-companion#49]
I know that this project is tied to `jwilder/nginx-proxy`, so I'm creating this issue just to know if in case, your project will also be compatible with Rkt.

See https://github.com/jwilder/nginx-proxy/issues/417 ( since you're mainly tied to the other one ) for more details :)

Thanks in advance!

**Comment by JrCs** [comment]
I think you can convert the docker image to an .aci to use in Rkt.
It must work.

**Comment by julianxhokaxhiu** [comment]
What about docker events? Are you listening to the socket? Is it firing the same events also with rkt?
