### ISSUE TITLE
Links Between Global and Per-Container Test Certificate Documentation

### ISSUE THREAD

**Issue by VincentSaelzler** [JrCs/docker-letsencrypt-nginx-proxy-companion#496]
On [Let's Encrypt / ACME > per proxyed container > Test Certificates](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Let's-Encrypt-and-ACME.md#test-certificates), there is no link to the global configuration via `ACME_CA_URI`.

That existed in the old documentation, but the recent updates removed the line.

I would adding a propose a line similar to @JonasT in Issue #190

> If  you want to do this globally for all containers, set `ACME_CA_URI` as described in [Container Configuration](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Container-configuration.md).

Also, on the [Container Configuration Wiki Page](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/wiki/Container-configuration), the link to `LETSENCRYPT_TEST` documentation is broken. It appears to work fine on the [Container Configuration Markdown Document](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Container-configuration.md).

Link in Question:

> You can also create test certificates per container (see [Test certificates](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/Let's-Encrypt-and-ACME#test-certificates))

**Comment by buchdag** [comment]
Sorry for the multiple pingbacks, I was unsure how to use co-authoring properly.

**Comment by VincentSaelzler** [comment]
No worries on the pingbacks, and thanks for updating.

I like the new, more organized documentation structure!
