### ISSUE TITLE
Documentation improvement suggestions

### ISSUE THREAD

**Issue by bluepuma77** [JrCs/docker-letsencrypt-nginx-proxy-companion#50]
In "**Separate Containers (recommended method)**" maybe mention, that the `nginx.tmpl` file **must** exist on the local server, contrary to using plain `nginx-proxy`. I created a blank file but that doesn't do the trick ;-) It can be obtained via 
`curl https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl > /path/to/nginx.tmpl`.

Furthermore you could add a container name to letsencrypt-nginx-proxy-companion
```
docker run -d \
    --name nginx-letsencrypt \
    -e "NGINX_DOCKER_GEN_CONTAINER=nginx-gen" \
```

In "**Let's Encrypt**" maybe clarify that the environment variables need to be used with each to-be-proxied application containers, maybe add a full example
```
docker run -d \
    --name example-app \
    -e "VIRTUAL_HOST=example.com" \
    -e "LETSENCRYPT_HOST=example.com" \
    -e "LETSENCRYPT_EMAIL=someone@example.com" \
    tutum/apache-php
```

**Comment by JrCs** [comment]
Thx for your comments.
I will update the documentation but you can add a PR.

**Comment by JrCs** [comment]
Done
