### ISSUE TITLE
Cryptic one-of bug

### ISSUE THREAD

**Issue by oivinds** [JrCs/docker-letsencrypt-nginx-proxy-companion#504]
I got this error running renewal of test certs. I have not encountered this error before and the bug did not repeat itself after taking the containers down and up again.  

> letsencrypt-nginx-proxy-companion_1  | 2019/02/05 09:48:01 Received event start for container 35c1e8aca8d0
> nginx-proxy                          | dockergen.1 | 2019/02/05 09:48:01 Received event start for container 35c1e8aca8d0
> nginx-proxy                          | dockergen.1 | 2019/02/05 09:48:01 Generated '/etc/nginx/conf.d/default.conf' from 5 containers
> letsencrypt-nginx-proxy-companion_1  | 2019/02/05 09:48:16 Debounce minTimer fired
> letsencrypt-nginx-proxy-companion_1  | 2019/02/05 09:48:16 Generated '/app/letsencrypt_service_data' from 5 containers
> letsencrypt-nginx-proxy-companion_1  | 2019/02/05 09:48:16 Running '/app/signal_le_service'
> letsencrypt-nginx-proxy-companion_1  | /etc/nginx/certs/_test_mydomain.example.org /app
> letsencrypt-nginx-proxy-companion_1  | Creating/renewal mydomain.example.org certificates... (mydomain.example.org)
> letsencrypt-nginx-proxy-companion_1  | 2019-02-05 09:48:17,396:INFO:simp_le:1564: Certificates already exist and renewal is not necessary, exiting with status code 1.
> letsencrypt-nginx-proxy-companion_1  | /app
> letsencrypt-nginx-proxy-companion_1  | /etc/nginx/certs/_test_mydom.example.org /app
> letsencrypt-nginx-proxy-companion_1  | Creating/renewal mydom.example.org certificates... (mydom.example.org)
> letsencrypt-nginx-proxy-companion_1  | Traceback (most recent call last):
> letsencrypt-nginx-proxy-companion_1  |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1584, in main
> letsencrypt-nginx-proxy-companion_1  |     return main_with_exceptions(cli_args)
> letsencrypt-nginx-proxy-companion_1  |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1567, in main_with_exceptions
> letsencrypt-nginx-proxy-companion_1  |     persist_new_data(args, existing_data)
> letsencrypt-nginx-proxy-companion_1  |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1457, in persist_new_data
> letsencrypt-nginx-proxy-companion_1  |     client = registered_client(args, existing_data.account_key)
> letsencrypt-nginx-proxy-companion_1  |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1395, in registered_client
> letsencrypt-nginx-proxy-companion_1  |     client = acme_client.Client(directory=args.server, key=key, net=net)
> letsencrypt-nginx-proxy-companion_1  |   File "/usr/lib/python2.7/site-packages/acme/client.py", line 270, in __init__
> letsencrypt-nginx-proxy-companion_1  |     net.get(directory).json())
> letsencrypt-nginx-proxy-companion_1  |   File "/usr/lib/python2.7/site-packages/acme/client.py", line 1054, in get
> letsencrypt-nginx-proxy-companion_1  |     self._send_request('GET', url, **kwargs), content_type=content_type)
> letsencrypt-nginx-proxy-companion_1  |   File "/usr/lib/python2.7/site-packages/acme/client.py", line 1003, in _send_request
> letsencrypt-nginx-proxy-companion_1  |     response = self.session.request(method, url, *args, **kwargs)
> letsencrypt-nginx-proxy-companion_1  |   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
> letsencrypt-nginx-proxy-companion_1  |     resp = self.send(prep, **send_kwargs)
> letsencrypt-nginx-proxy-companion_1  |   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
> letsencrypt-nginx-proxy-companion_1  |     r = adapter.send(request, **kwargs)
> letsencrypt-nginx-proxy-companion_1  |   File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 513, in send
> letsencrypt-nginx-proxy-companion_1  |     raise ConnectionError(e, request=request)
> letsencrypt-nginx-proxy-companion_1  | ConnectionError: HTTPSConnectionPool(host='acme-staging.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4c09a9a9d0>: Failed to establish a new connection: [Errno -3] Try again',))
> letsencrypt-nginx-proxy-companion_1  | 
> letsencrypt-nginx-proxy-companion_1  | Unhandled error has happened, traceback is above
> letsencrypt-nginx-proxy-companion_1  | 
> letsencrypt-nginx-proxy-companion_1  | Debugging tips: -v improves output verbosity. Help is available under --help.

**Comment by buchdag** [comment]
Looks like a network error incorrectly handled by `simp_le`.
