### ISSUE TITLE
Help: Basic example with NAT

### ISSUE THREAD

**Issue by ReneCD** [JrCs/docker-letsencrypt-nginx-proxy-companion#505]
I am trying to make the basic example (nginx-proxy / nging-proxy-companion / nginx combo) working but no cigar.

I've setup the 3 containers on Docker on a Debian 9 server.  The containers are set up exactly as described.  

http://*subdomain.yourdomain.tld* is reachable but https://*subdomain.yourdomain.tld* is not. The former get the expected "Welcome to nginx!" message, but the latter gets "This site can’t be reached - *subdomain.yourdomain.tld* refused to connect.".

The containers are all running, and no other errors are given.  The 3 folders described in step 1 are all present and chmod 777 - but no content has ever been found in any of the folders, either before/during/after trying.

Netstat shows that docker-proxy is listening on both ports 80 and 443. Different PID's though, but docker ps only shows one nginx-proxy container running.

I would have expected nginx-proxy to accept traffic on any published port and proxy it to whatever is bound on the socket. What am I doing wrong? Help....

(redid tests without NAT, updated post to reflect this)

**Comment by buchdag** [comment]
Do you have the exact commands or compose file you used and the containers logs ?

**Comment by ReneCD** [comment]
Actually somehow I got over this problem, even though I'm not sure how.   Now I have most of it working to the point I get the page up, but when I enter /media/usb/share/nextcloud/data as my data folder, it comes back with the error "Error Can't create or write into the data directory /media/usb/share/nextcloud/data"

Ownership and permissions should be correct (www-data.www-data and 755). I have a feeling docker might try to create it under /var/lib/docker in spite of me adding NEXTCLOUD_DATA_DIR=/media/usb/share/netcloud/data.  I want my data store out of docker, how do I do that?

`version: '2'  

volumes:
  nextcloud:
  data:
  db:

services:  
  nginx-proxy:
    image: 'jwilder/nginx-proxy'
    container_name: nginx-proxy
    ports:
      - '443:443'
    volumes:
      - '/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/etc/nginx/certs:/etc/nginx/certs:ro' 
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
  letsencrypt-nginx-proxy:
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    container_name: letsencrypt-nginx-proxy
    volumes:
      - '/etc/nginx/certs:/etc/nginx/certs'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    volumes_from:
      - nginx-proxy

  mariadb:
    image: mariadb
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$rootpassword
      - MYSQL_PASSWORD=$mysqlpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    container_name: nextcloud 
    ports:
      - 8080:80
    links:
      - mariadb
    volumes:
      - nextcloud:/media/usb/share/nextcloud
      - /data:/media/usb/share/nextcloud/data
    environment:
      - VIRTUAL_HOST=$myhost
      - LETSENCRYPT_HOST=$myhost
      - LETSENCRYPT_EMAIL=$myemail 
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=$adminpass
      - NEXTCLOUD_DATA_DIR=/media/usb/share/netcloud/data
    restart: always
  
networks:  
  default:
    external:
      name: nginx-net
`

**Comment by buchdag** [comment]
If you attempt to close port 80 of the proxy, domain authorizations will fail. Please check the requirements at the beginning of the doc.

Nextcloud specific questions should be asked on Nextcloud's repository.

**Comment by ReneCD** [comment]
I didnt' close port 80. I really have no idea why it didn't work, suddenly it did work. It seems there is a delay from the container runs until the certificate is ready, maybe that was the reason. Anyway, this part is resolved so I will take the nextcloud question to the nextcloud repo as suggested.

**Comment by buchdag** [comment]
```yaml
services:
  nginx-proxy:
    image: 'jwilder/nginx-proxy'
    container_name: nginx-proxy
    ports:
      - '443:443'
    volumes:
    [...]
```

There is no mapping for `nginx-proxy` port 80, meaning it's unreachable from outside the container's docker network.

It has to be reachable on your host's own port 80.

**Comment by ReneCD** [comment]
Ah, right, thanks!
