### ISSUE TITLE
Received event die for container

### ISSUE THREAD

**Issue by h-rasi** [JrCs/docker-letsencrypt-nginx-proxy-companion#513]
Hello. I am facing this error in the letsencrypt reverse-proxy. It is very annoying and happening every day and making application unavailable.
This is my error:

```
reverse-proxy_1              | dockergen.1 | 2019/02/16 21:25:02 Received event die for container 14822f7b1f16
reverse-proxy_1              | dockergen.1 | 2019/02/16 21:25:02 Received event die for container c68be0c51dd6
reverse-proxy_1              | dockergen.1 | 2019/02/16 21:25:02 Error inspecting container: 
c68be0c51dd6a22c4e81526422ae02ef7a85934d29c531b663d3f2f85d0d1c83: No such container: 
c68be0c51dd6a22c4e81526422ae02ef7a85934d29c531b663d3f2f85d0d1c83
reverse-proxy_1              | dockergen.1 | 2019/02/16 21:25:02 Generated '/etc/nginx/conf.d/default.conf' from 3 containers
reverse-proxy_1              | dockergen.1 | 2019/02/16 21:25:02 Running 'nginx -s reload'
reverse-proxy_1              | dockergen.1 | 2019/02/16 21:25:02 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
reverse-proxy_1              | dockergen.1 | 2019/02/16 21:25:54 Received event start for container 6054a54b65d6
reverse-proxy_1              | dockergen.1 | 2019/02/16 21:25:54 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
reverse-proxy_1              | dockergen.1 | 2019/02/16 21:25:55 Received event start for container 72fac936c3e4
reverse-proxy_1              | dockergen.1 | 2019/02/16 21:25:55 Generated '/etc/nginx/conf.d/default.conf' from 5 containers
reverse-proxy_1              | dockergen.1 | 2019/02/16 21:25:55 Running 'nginx -s reload'
```

The docker-compose is looked like this:
![screenshot from 2019-02-15 17-02-36](https://user-images.githubusercontent.com/39412867/52905155-6ffd3a00-3236-11e9-9515-cca4e9040764.png)

and this is what https://crt.sh shows about my URL:
![screenshot from 2019-02-16 21-54-36](https://user-images.githubusercontent.com/39412867/52905118-cd44bb80-3235-11e9-9293-361a3b9a694f.png)

Could you please let me know what is the problem? Thanks

**Comment by zer0i3** [comment]
I am facing the same error.
It looks fine now by converting my docker-compose file version 3 to 2, you can use `volumes_from` in version 2.

**Comment by buchdag** [comment]
@h-rasi what is this `xalt/nginx` image your are using ?

**Comment by buchdag** [comment]
Also we only deal with issues directly related to `jrcs/letsencrypt-nginx-proxy-companion`. As far as I can tell what you posted is an issue inside an unknown fork of `nginx-proxy`.

crt.sh shows that your certificates have been correctly created.

**Comment by h-rasi** [comment]
@buchdag Thanks for your message. Basically, xalt/nginx is our nginx image that has been created from jwilder image with some customization in environmental variables.
And you are right the issue was not related to jrcs/letsencrypt-nginx-proxy-companion. This issue has been created a month ago and we realize that the problem was related to something else( backup sidecard container) and Unfortunately I forgot to close this issue.
Thanks again for your time.
