### ISSUE TITLE
Container ID does not work reliably in fedora atomic systems

### ISSUE THREAD

**Issue by xiamaz** [JrCs/docker-letsencrypt-nginx-proxy-companion#514]
cgroup and cpuset in fedora atomic seem to start with `/system.slice/....` breaking the current container id discovery.

The current fallback mechanism only takes the existence of files into account and doesn't handle whether the name has a format which it can handle.

**Comment by buchdag** [comment]
Hi.

Could you give me the exact file path we're talking about and its full content ?

**Comment by xiamaz** [comment]
Yes, sorry for not including it in the initial bug report.

/proc/1/cpuset:

```
system.slice/docker-d31df8b9e8ca610dfc1e2be28bbedd7bf47c7691ae70671312cc06253b7ec930.scope
```

```

/proc/self/cgroup:
```
11:pids:/system.slice/docker-d31df8b9e8ca610dfc1e2be28bbedd7bf47c7691ae70671312cc06253b7ec930.scope
10:devices:/system.slice/docker-d31df8b9e8ca610dfc1e2be28bbedd7bf47c7691ae70671312cc06253b7ec930.scope
9:blkio:/system.slice/docker-d31df8b9e8ca610dfc1e2be28bbedd7bf47c7691ae70671312cc06253b7ec930.scope
8:cpuset:/system.slice/docker-d31df8b9e8ca610dfc1e2be28bbedd7bf47c7691ae70671312cc06253b7ec930.scope
7:freezer:/system.slice/docker-d31df8b9e8ca610dfc1e2be28bbedd7bf47c7691ae70671312cc06253b7ec930.scope
6:memory:/system.slice/docker-d31df8b9e8ca610dfc1e2be28bbedd7bf47c7691ae70671312cc06253b7ec930.scope
5:net_cls,net_prio:/system.slice/docker-d31df8b9e8ca610dfc1e2be28bbedd7bf47c7691ae70671312cc06253b7ec930.scope
4:perf_event:/system.slice/docker-d31df8b9e8ca610dfc1e2be28bbedd7bf47c7691ae70671312cc06253b7ec930.scope
3:hugetlb:/system.slice/docker-d31df8b9e8ca610dfc1e2be28bbedd7bf47c7691ae70671312cc06253b7ec930.scope
2:cpu,cpuacct:/system.slice/docker-d31df8b9e8ca610dfc1e2be28bbedd7bf47c7691ae70671312cc06253b7ec930.scope
1:name=systemd:/system.slice/docker-d31df8b9e8ca610dfc1e2be28bbedd7bf47c7691ae70671312cc06253b7ec930.scope
0::/system.slice/docker-d31df8b9e8ca610dfc1e2be28bbedd7bf47c7691ae70671312cc06253b7ec930.scope
```

Are there situations where the docker_api approach might not work correctly? Otherwise that seems to be most reasonable default short of doing a more comprehensive trial and checking.

**Comment by buchdag** [comment]
> Are there situations where the docker_api approach might not work correctly?

Yes, because it relies on the fact that the container name and hostname are the same, and indeed you can set different values for those.

The idea of falling back to the API was also that reading content from a file was going to be faster than an API call (an order of magnitude faster, the API call taking around 0.05s and the file method around 0.005s when measured with `time`).

The problem here is not the `system.slice/` prefix itself but the fact that they add `docker-`and `.scope` to the container ID (probably because it has something to do with systemd). Maybe we chould check for both the file existence AND the length of the string returned by this method before using it ? That should correctly fall back to the API call in this case.

**Comment by buchdag** [comment]
@xiamaz any advice on the previous proposition ?

**Comment by xiamaz** [comment]
Sorry for the late reply.

> > Are there situations where the docker_api approach might not work correctly?
> 
> Yes, because it relies on the fact that the container name and hostname are the same, and indeed you can set different values for those.

Okay, this is a major issue.

> The idea of falling back to the API was also that reading content from a file is faster than an API call (an order of magnitude faster, the API call taking around 0.05s and the file method around 0.005s when measured with `time`).
> 
> The problem here is not the `system.slice/` prefix itself but the fact that they add `docker-`and `.scope` to the container ID (probably because it has something to do with systemd). Maybe we chould check for both the file existence AND the length of the string returned by this method before using it ? That should correctly fall back to the API call in this case.

Yes, alternatively we could use a regex to grab a substring of the correct length. This should be robust, as long as the string has the correct length, which we would need to expect anyways.

The API based method, seems to be more error prone in the long run, since people might not expect it, when it breaks.
