### ISSUE TITLE
Multi-Server / Swarm Configuration ?

### ISSUE THREAD

**Issue by Gaibhne** [JrCs/docker-letsencrypt-nginx-proxy-companion#517]
Can this setup be used to route traffic to multiple docker containers, such as a swarm setup ? From the documentation, it seems I can only get the nginx proxy to route to a single container (per domain), or am I misunderstanding ?

We are fine with only running a small handful of containers, we don't need a full swarm setup. But we do need proxying/balancing to at least two containers somehow.

**Comment by buchdag** [comment]
Hi.

This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

What you want to achieve depends entirely on the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different peoples.

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)

**Comment by Gaibhne** [comment]
Thank you, sorry for posting this on the wrong repository.
