### ISSUE TITLE
ACME challenge over http

### ISSUE THREAD

**Issue by DominikUrban** [JrCs/docker-letsencrypt-nginx-proxy-companion#520]
First of all thank you for your work on this very useful project :)

I use client certificates and set the NGINX configuration over the vhosts:

ssl_client_certificate /etc/ssl/certs/ca-chain.cert.pem;
ssl_verify_client on;

Since the ACME Challenge is made over HTTPS, Letsencrypt always gets back a "400 Bad Request". Unfortunately, NGINX can only set the ssl_verify_client setting per server block.

To my question: Is there a configuration possibility to make the challenges over HTTP, which I overlooked? If not, would it be possible to add an environment variable that would allow to do challenges over HTTP instead of HTTPS?

**Comment by buchdag** [comment]
Hi.

ACME `http-01` challenge isn't made over HTTPS but over HTTP as the name imply, but it will follow redirect to HTTPS.

**Comment by DominikUrban** [comment]
I am aware that Letsencrypt tries it over HTTP but is then forwarded to HTTPS.
The problem is rather that the location block for the ACME challenge is added to my vhost configuration. Exactly this location block could also be added to the HTTP server configuration, that case eliminates the redirect for the ACME challenges.

For example the current generated configuration:
```
# kibana.xyz.com
upstream kibana.xyz.com {
	# logging_kibana_1
	server XXX;
}
server {
	server_name kibana.xyz.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name kibana.xyz.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	[...]
	include /etc/nginx/vhost.d/kibana.xyz.com;
	
	## CONTENT of vhost include ##

	## Start of configuration add by letsencrypt container
	location ^~ /.well-known/acme-challenge/ {
	    auth_basic off;
	    allow all;
	    root /usr/share/nginx/html;
	    try_files $uri =404;
	    break;
	}
	## End of configuration add by letsencrypt container
	ssl_client_certificate /etc/ssl/certs/ca-chain.cert.pem;
	ssl_verify_client on;

	## CONTENT of vhost include ##

	location / {
		proxy_pass http://kibana.xyz.com;
	}
}
```

And that's the configuration I'd like to create with the letsencrypt-companion:
```
# kibana.xyz.com
upstream kibana.xyz.com {
	# logging_kibana_1
	server XXX;
}
server {
	server_name kibana.xyz.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;

	## Start of configuration add by letsencrypt container
	location ^~ /.well-known/acme-challenge/ {
	    auth_basic off;
	    allow all;
	    root /usr/share/nginx/html;
	    try_files $uri =404;
	    break;
	}
	## End of configuration add by letsencrypt container

	return 301 https://$host$request_uri;
}
server {
	server_name kibana.xyz.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	[...]
	include /etc/nginx/vhost.d/kibana.xyz.com;
	
	## CONTENT of vhost include ##
	ssl_client_certificate /etc/ssl/certs/ca-chain.cert.pem;
	ssl_verify_client on;
	## CONTENT of vhost include ##

	location / {
		proxy_pass http://kibana.xyz.com;
	}
}
```

Is that possible?

**Comment by buchdag** [comment]
This depends on nginx-proxy's `nginx.tmpl` file.

We try to have something that work out of the box with the upstream `nginx.tmpl` file but as you found out it does not work for every scenario. You can however use a custom `nginx.tmpl` file tailored to your needs. I think I did something similar a few months ago, let me search.

**Comment by buchdag** [comment]
Found it : #299 

Let me know if that helps.

**Comment by buchdag** [comment]
@DominikUrban Can I close the issue ?

**Comment by buchdag** [comment]
No updates from the issue's creator in 60 days, closing.
