### ISSUE TITLE
502 Bad Gateway with alfresco

### ISSUE THREAD

**Issue by march76** [JrCs/docker-letsencrypt-nginx-proxy-companion#523]
Hi, did anyone use this project even with alfresco docker? 
I'm tried to publish a docker from [gui81/docker-alfresco](https://github.com/gui81/docker-alfresco) with command

> docker run --name='alfresco-test' -it --rm --env "VIRTUAL_HOST=test.sinekarta.com" gui81/alfresco 

 but unfortunately i always get **502 bad gateways**.

Alfresco have a tomcat listening on port 8080 and 8443 but it seems that ngix fails to redirect correctly. I have other tomcat application and i don't have this problem.

Does anyone have any particular configuration ideas?

**Comment by buchdag** [comment]
Hi.

This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

What you want to achieve depends entirely on the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different peoples.

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)
