### ISSUE TITLE
no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status

### ISSUE THREAD

**Issue by Redsandro** [JrCs/docker-letsencrypt-nginx-proxy-companion#524]
Something is going wrong with the DNS resolver every now and then. Are there other options we can add?

```
2019/03/21 15:48:15 [warn] 9#9: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/certs/*******.com.crt"
```

Is this an issue with `docker-letsencrypt-nginx-proxy-companion`? Or are there other factors at play?

```
resolver 8.8.8.8;
```

I deploy again, and then it goes fine.

**Comment by buchdag** [comment]
What container is this log line from ?

**Comment by buchdag** [comment]
If this is from `letsencrypt-nginx-proxy-companion`, how you obtained it is not clear to me has I personally never encountered it and it's not part of this repo's specific code.

With `/app/cert_status` ?

**Comment by Redsandro** [comment]
It came from `docker-letsencrypt-nginx-proxy-companion` or `nginx-proxy`. I tried to dig a bit deeper, but unfortunately in order to work around this I did `docker-compose down && docker-compose up -d` to trigger a new certificate request, but as a result the previous logs have been cleared.

> With `/app/cert_status` ?

I did not run anything manually, this is just the nginx-proxy with letsencrypt-companion setup.

I've seen this 3 times out of maybe 50 new domains requested through the letsencrypt-companion, so it does not happen often. [According to this](https://community.letsencrypt.org/t/no-resolver-defined-to-resolve-ocsp-int-x3-letsencrypt-org-while-requesting-certificate-status-responder-ocsp-int-x3-letsencrypt-org/21427) however, it happens due to obsolete resolver configuration in nginx. I do not know if we should look at nginx-proxy or letsencrypt-companion for this issue, but it happens when letsencrypt requests a certificate for the first time, so I thought I'd post an issue here. I don't know a lot about the inner workings of either, and I don't understand what the solution suggested in aforementioned link actually means.

**Comment by buchdag** [comment]
The LE community thread you linked make it rather clear that this is an `ningx-proxy` related issue.

If you are using an up to date version of the `nginx-proxy` container (or of the `nginx.tmpl` file), [the suggested solution is already there](https://github.com/jwilder/nginx-proxy/blob/8c590fc68ffb0551cfa99875f1a8fd1cdf6a3e66/nginx.tmpl#L261).

**Comment by Redsandro** [comment]
I have verified that the template I checked out does already have that line of code. Today I've experienced the same issue three times in a row. I will take this issue to the `nginx-proxy` repo. 

There seems to be reciprocity between `nginx-proxy` and `docker-letsencrypt-nginx-proxy-companion`.

**Comment by buchdag** [comment]
> There seems to be reciprocity between `nginx-proxy` and `docker-letsencrypt-nginx-proxy-companion`.

What do you mean ?

**Comment by Redsandro** [comment]
@buchdag?
> What do you mean ?

Sorry English is not my native tongue. I'm trying to say some form of interaction.

I can hang two, four, eight or twenty services in the `nginx-proxy` stack. But the only one _indirectly_ having (random occasional) problems is the `letsencrypt-companion`.

So whether or not the root issue is with `nginx-proxy`, it seems to show itself exclusively as a response to `letsencrypt-companion` activity.

**Comment by buchdag** [comment]
What your `nginx-proxy` container is telling you is that it's trying to perform [OCSP validation](https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol) for a Let's Encrypt issued certificate but can't resolve the DNS name of their OCSP responder (`ocsp.int-x3.letsencrypt.org`).

That's an issue 100% internal to the `nginx-proxy` container and completely outside of what the `letsencrypt-nginx-proxy-companion` container can do. The companion has no bearing on `nginx-proxy` DNS settings.

The companion is actually pretty simple in what it does, it's just bash automation around an ACME / LE client, and the one and only direct interaction it has with `nginx-proxy` is reloading it when certificates are created or modified.

**Comment by Redsandro** [comment]
@buchdag thank you for clarifying. I will close this issue and hope someone can help me out at https://github.com/jwilder/nginx-proxy/issues/1256

**Comment by dm17** [comment]
> The LE community thread you linked make it rather clear that this is an `ningx-proxy` related issue.
> 
> If you are using an up to date version of the `nginx-proxy` container (or of the `nginx.tmpl` file), [the suggested solution is already there](https://github.com/jwilder/nginx-proxy/blob/8c590fc68ffb0551cfa99875f1a8fd1cdf6a3e66/nginx.tmpl#L261).

I have that suggested solution already in my nginx.tmpl - I'm still getting lots of these warnings; not sure how they're affecting my system. Any idea how I can debug this? nginx-proxy doesn't have curl installed unfortunately.
