### ISSUE TITLE
How to generate ssl for sites that is not in docker?

### ISSUE THREAD

**Issue by katemicse** [JrCs/docker-letsencrypt-nginx-proxy-companion#528]
With nginx-proxy alongsite i used to create docker-compose
and place 

`      VIRTUAL_HOST: www.example.site.com,example.site.com
      LETSENCRYPT_HOST: www.example.site.com,example.site.com
      LETSENCRYPT_EMAIL: email@email.email
`
for each projects docker-compose file.

How can i use the docker-letsencrypt-nginx-proxy-companion and nginx-proxy to generate ssl for services that is not in docker, for example some meteor app?

**Comment by buchdag** [comment]
Hi, please take a look at #368 and https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Standalone-certificates-(beta).md

If you have further questions, please subit them to #368
