### ISSUE TITLE
Any way to pass extra hosts manually?

### ISSUE THREAD

**Issue by Bre77** [JrCs/docker-letsencrypt-nginx-proxy-companion#53]
I love this for handling all my docker containers hosted using unRAID, but I would really like to also have this container manage a cert for my unRAID GUI itself. I am passing a custom .conf file to configure nginx-proxy to achieve the reverse proxy side, but is there any way to pass this container a manual host name as well?

(or If I get the lets encrypt cert manually, will this container keep it renewed?)

**Comment by JrCs** [comment]
I didn't know unRAID.
The certificate will be renewed if you have a docker container with the right variables (LETS_ENCRYPT_XXXX) and that can be access from the internet through the nginx proxy.
