### ISSUE TITLE
Customize nginx.conf

### ISSUE THREAD

**Issue by immertroll** [JrCs/docker-letsencrypt-nginx-proxy-companion#535]
Update:
Or how can I achieve this?
Currently my nginx redirects to subdomain.domain.com if somebody requests subdomain.domain.com/xyz. He should not be redirected and get a 404 or 444 instead.

Thx

-----------------------------
It's not a really issue but I could not find anything in the wiki or documentation.

This project generates the config files of nginx in it's volumes. Will them overwritten if I change something in this config, e.g. other endpoints?

Thx

**Comment by buchdag** [comment]
Hi.

This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

What you want to achieve depends entirely on the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different peoples.

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)

**Comment by immertroll** [comment]
Yeah concrete config solution is a part for the nginx repo.

Could you get me an answer for this?
This project generates the config files of nginx in it's volumes. Will them overwritten if I change something in this config, e.g. other endpoints?

Thx
