### ISSUE TITLE
Unable to access .well-known/carddav/

### ISSUE THREAD

**Issue by majoux** [JrCs/docker-letsencrypt-nginx-proxy-companion#54]
I have a container with official owncloud 9 . I can't access to the carddav contacts.
I guess the configuration done by this container :
```
location /.well-known/ {
    auth_basic off;
    root /usr/share/nginx/html;
    try_files $uri =404;
}
```
This is blocking the way to access .well-known/carddav ? Am I right ?

**Comment by JrCs** [comment]
Fixed in ae21e24
