### ISSUE TITLE
Proxy multiple ports of one subdomain in docker-compose

### ISSUE THREAD

**Issue by ProteanCode** [JrCs/docker-letsencrypt-nginx-proxy-companion#541]
I am trying to access my docker containers using a different ports, and it works without using letsencrypt, on example I have 2 different web apps

`app.example.com:80 # some nginx thing`
`app.example.com:8080 # a swagger ui`

I am messing around VIRTUAL_PORT settings but it eventually ends with SSL_CERTIFICATE_ERROR or 502

Afaik, the only one container within docker-compose that should be "lets encrypted" is the nginx one, and then accessing the https://app.example.com:8080 should work the same way as accessing the http version, right?

**Comment by Greek64** [comment]
The `nginx-proxy` only listens to ports 80 and 443, and forwards the requests to the containers according to the configured `VIRTUA_HOST` variables.  
If you try to access `app.example.com:8080` (and you have mapped the swagger docker container port to the local host port 8080), you are effectively bypassing the `nginx-proxy` and accessing the swagger container directly.

So, you either define two different hosts to access the containers and use the `nginx-proxy` / `docker-letsencrypt-nginx-proxy-companion` combo as it was intended:
```
app1.example.com # some nginx thing
app2.example.com # a swagger UI
```
or you deliberately bypass the `nginx-proxy` and terminate the HTTPS on the end-container by yourself.

The second method means that you have to provide the certificates to the container, and it has to handle the HTTPS connections. You can (mis-)use `docker-letsencrypt-nginx-proxy-companion` to automatically create/renew certificates that you map inside the target container.

**Comment by buchdag** [comment]
@ProteanCode any update on this issue ?

**Comment by ProteanCode** [comment]
> @ProteanCode any update on this issue ?

I created a subdomain entries and used it in a normal way without complicating things.
