### ISSUE TITLE
Specify self-signed cert for internal domain [question]

### ISSUE THREAD

**Issue by sunomie** [JrCs/docker-letsencrypt-nginx-proxy-companion#549]
Hi.  Firstly, this is awesome; thanks!  This has quickly became one of my goto tools.

Have a use-case where a container behind this tool needs to be accessed on a domain name that resolved to public IP (works great) and also from VPN to a domain name that resolves to a private IP (where I'm stuck).  Letsencrypt cannot handle private-IPs; no surprise there.  But is there a best practice for have this tool to serve up a specific (self-signed) certificate for a specific domain-name that resolves to a private IP?  Can I just edit the nginx proxy config file manually or will that get overwritten?

Thanks again for this great tool.

**Comment by buchdag** [comment]
Hi.

Let say your public and private domains both resolve to IPs on which the `nginx-proxy`/`nginx` container is listening, and that your proxyed app container is configured with those environment variables :

```
VIRTUAL_HOST=your.publicdomain.com,privatedomain.tld
LETSENCRYPT_HOST=your.publicdomain.com
```

If you want to enable `https` with a self signed certificate on `privatedomain.tld`, [just follow `nginx-proxy` documentation for SSL](https://github.com/jwilder/nginx-proxy#ssl-support) and mount your private key and certificate inside `/etc/nginx/certs` as `privatedomain.tld.key` and `privatedomain.tld.crt` respectively.

Don't forget to mount them inside **both** the `nginx` and `docker-gen` container if you use a three container setup. Mounting them inside the `letsencrypt-nginx-proxy-companion` container isn't required as it won't be involved at all.

This is more an `nginx-proxy` question by the way, so I'm going to close this issue.
