### ISSUE TITLE
Still issues with auto-renew - 503?

### ISSUE THREAD

**Issue by falcon15500** [JrCs/docker-letsencrypt-nginx-proxy-companion#55]
Hi,

I fixed my previous issues with renewal, however I am still having issues.  I have all of my addresses on the one SAN certificate (great feature).  Creating the cert was no problem, however the renewal doesn't seem to work.  Checking the logs it seems that the validation (via the .well-known/acme-challenge thing) doesn't work.

The debug logs show:

> 2016-04-25 06:18:39,767:DEBUG:acme.challenges:263: Verifying http-01 at http://couch.nine-hells.net/.well-known/acme-challenge/zk0acTDR1rJ4seBosynJA5niKsJU0nKqD_STKwBtkD0...
> 
> 2016-04-25 06:18:39,768:INFO:requests.packages.urllib3.connectionpool:207: Starting new HTTP connection (1): couch.nine-hells.net
> 
> 2016-04-25 06:18:39,922:DEBUG:requests.packages.urllib3.connectionpool:387: "GET /.well-known/acme-challenge/zk0acTDR1rJ4seBosynJA5niKsJU0nKqD_STKwBtkD0 HTTP/1.1" 503 213
> 
> 2016-04-25 06:18:39,922:DEBUG:acme.challenges:270: Received <Response [503]>: <html>
> <head><title>503 Service Temporarily Unavailable</title></head>
> <body bgcolor="white">
> <center><h1>503 Service Temporarily Unavailable</h1></center>
> <hr><center>nginx/1.9.14</center>
> </body>
> </html>
> . Headers: {'Date': 'Mon, 25 Apr 2016 06:18:39 GMT', 'Content-Length': '213', 'Content-Type': 'text/html', 'Connection': 'keep-alive', 'Server': 'nginx/1.9.14'}
> 
> 2016-04-25 06:18:39,922:DEBUG:acme.challenges:276: Key authorization from response (u'zk0acTDR1rJ4seBosynJA5niKsJU0nKqD_STKwBtkD0.yCerLuhuTaQrEdvYLhNIzp_RW3EKJ1A8FXwQUyl8oqw') doesn't match HTTP response (u'<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body bgcolor="white">\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx/1.9.14</center>\r\n</body>\r\n</html>')
> 
> 2016-04-25 06:18:39,923:WARNING:simp_le:1292: couch.nine-hells.net was not successfully self-verified. CA is likely to fail as well!

And the access log for the nginx container shows:

`couch.nine-hells.net 60.240.175.196 - - [25/Apr/2016:06:18:39 +0000] "GET /.well-known/acme-challenge/zk0acTDR1rJ4seBosynJA5niKsJU0nKqD_STKwBtkD0 HTTP/1.1" 503 213 "-" "python-requests/2.8.1"
couch.nine-hells.net 66.133.109.36 - - [25/Apr/2016:06:18:40 +0000] "GET /.well-known/acme-challenge/zk0acTDR1rJ4seBosynJA5niKsJU0nKqD_STKwBtkD0 HTTP/1.1" 503 213 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"`

However, I just stopped the companion container, deleted all the old cert data and restarted the companion.  New certificate is generated without any issues (none of the other containers were stopped, started or otherwise touched) and the nginx access logs show:

`couch.nine-hells.net 60.240.175.196 - - [25/Apr/2016:06:22:20 +0000] "GET /.well-known/acme-challenge/XihsBP2JxaZHA0j_n8Jl4S_EiEH2k8mCETC0dQ09v6U HTTP/1.1" 200 87 "-" "python-requests/2.8.1"
couch.nine-hells.net 66.133.109.36 - - [25/Apr/2016:06:22:21 +0000] "GET /.well-known/acme-challenge/XihsBP2JxaZHA0j_n8Jl4S_EiEH2k8mCETC0dQ09v6U HTTP/1.1" 200 87 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"`

It doesn't make sense?  Surely they use the same verification method?  Why would creation work without any issues, but the same setup fails to verify for renewal?  What is different about the two scenarios?

I can schedule a script to stop the app, delete the certs and restart the app every coulple of months to workaround this - but I would obviously rather have this working as intended.

Any ideas?

Mike

**Comment by JrCs** [comment]
The first time (without any cert) nginx is not configured to proxy the https requests (because no certs exists).
But after the certs are created, the nginx configuration is changed to proxy the https request.
So i think you have a bad nginx.tmpl file or any other nginx configuration that create this issue.
So look closely the default.conf file.

**Comment by falcon15500** [comment]
It's very odd, because the certificates work correctly when browsing the websites.  If I grab one of the verification URLs from the log and put it in the browser, it downloads the file?

**Comment by falcon15500** [comment]
Okay, so that's not true.  Just performed a test with openssl:

> [root@ferryman templates]# openssl s_client -connect www.nine-hells.net:443
> CONNECTED(00000003)
> depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
> verify return:1
> depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
> verify return:1
> depth=0 CN = couch.nine-hells.net
> verify return:1
> ---
> Certificate chain
>  0 s:/CN=couch.nine-hells.net
>    i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
>  1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
>    i:/O=Digital Signature Trust Co./CN=DST Root CA X3
> ---
> Server certificate
> -----BEGIN CERTIFICATE-----
> MIIG1jCCBb6gAwIBAgISAyruGi7WEsiZHgVY7OJhIX3pMA0GCSqGSIb3DQEBCwUA
> MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
> ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xNjA0MjUwNTUzMDBaFw0x
> NjA3MjQwNTUzMDBaMB8xHTAbBgNVBAMTFGNvdWNoLm5pbmUtaGVsbHMubmV0MIIC
> IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA6g0NaR7ChR/J+0imUNXsEqdz
> 0B3CgZkJJqrlXuCu4SDFdNGqE/zf90IA7aI7AzcY/ltFYnLiZyu18RRjVO/1NKLT
> 8tXfkmmfgdIXfawhf9sTQhuAmMG9eEtV9exWg/H+kU9E/LjPkjdS3RReDgikgs7W
> 5XNprpCjASZRJAQlU/Jw24B4CZkGXIPpYBMlj9FFZ1GiaZpbSYhxkTCwSCedjXzg
> mEiUEyFAtn3i13Wzylw3UrRS4xdIOX9myWI7EEeqZ3XYjPfUrRWCjZojMmwhIf4f
> 91UG346QLcMIjf60VURcOdIyzFGKEByV9YpRe3djFqVPX1M6NW7l7+NB3C5+oWJ0
> DUu3L4Arj2t8nIdv7naYPgCLh7npUJEzB/V1bM89DG44EmnNsg107jb2rPgRuyAm
> 8VGomPdB4CWZTiHcrWREsxTbyGfE9ho8OD+QoMRTJQ7Pr5xgHI4uUOoRy+obRe3V
> 2ugAQcOtqTRH0UD9jv/KVoItL9iXlDltXYC8YFOsDzgbfNwau/H+JtjBmC0RRG/Y
> Pq5t5PE0LzS5pjdWhZiI14p2onFkCJFSavKRA5qfSZmSdao84QntQc85J+Iw4imm
> 4IrC/+53MCUkHAai3DhRPp2rfdD8ojr0UBz1T1tBwuNGmSi5+BM01yOO+W5y9T3N
> VHqLfRstcX0fPc0nEtkCAwEAAaOCAt8wggLbMA4GA1UdDwEB/wQEAwIFoDAdBgNV
> HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
> FgQUDRV5v76HMmJdl2kgGlDm0V4A6XEwHwYDVR0jBBgwFoAUqEpqYwR93brm0Tm3
> pkVl7/Oo7KEwcAYIKwYBBQUHAQEEZDBiMC8GCCsGAQUFBzABhiNodHRwOi8vb2Nz
> cC5pbnQteDMubGV0c2VuY3J5cHQub3JnLzAvBggrBgEFBQcwAoYjaHR0cDovL2Nl
> cnQuaW50LXgzLmxldHNlbmNyeXB0Lm9yZy8wgegGA1UdEQSB4DCB3YIUY291Y2gu
> bmluZS1oZWxscy5uZXSCFWRlbHVnZS5uaW5lLWhlbGxzLm5ldIIVZWJvb2tzLm5p
> bmUtaGVsbHMubmV0gg5uaW5lLWhlbGxzLm5ldIITcGxleC5uaW5lLWhlbGxzLm5l
> dIIacGxleGNvbm5lY3QubmluZS1oZWxscy5uZXSCFnNhYm56YmQubmluZS1oZWxs
> cy5uZXSCF3NpY2tyYWdlLm5pbmUtaGVsbHMubmV0ghJ3d3cubmluZS1oZWxscy5u
> ZXSCEXptLm5pbmUtaGVsbHMubmV0MIH+BgNVHSAEgfYwgfMwCAYGZ4EMAQIBMIHm
> BgsrBgEEAYLfEwEBATCB1jAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5sZXRzZW5j
> cnlwdC5vcmcwgasGCCsGAQUFBwICMIGeDIGbVGhpcyBDZXJ0aWZpY2F0ZSBtYXkg
> b25seSBiZSByZWxpZWQgdXBvbiBieSBSZWx5aW5nIFBhcnRpZXMgYW5kIG9ubHkg
> aW4gYWNjb3JkYW5jZSB3aXRoIHRoZSBDZXJ0aWZpY2F0ZSBQb2xpY3kgZm91bmQg
> YXQgaHR0cHM6Ly9sZXRzZW5jcnlwdC5vcmcvcmVwb3NpdG9yeS8wDQYJKoZIhvcN
> AQELBQADggEBADBkQZGrBBptzZ0Fjqd5iNHO5zp6kuRIROirg3K19VpygOJVHE1C
> MYduFuOE+MF9FAdLbVYTBNuTJVI5n6OG7N6Dxp9MNZ2ckTFebkGSnwufxu+QyTzg
> hICcizAeYM3prE+SFjgZjF49bWDuoWYsFz8PY+tgdDtarUveein5pdwApET/MWlK
> 3FfaM79r6QFiGyO9+kTQE6op1dsdKHMgMefdG2zjmT60yEvdIkXftx6rTWl3HJXI
> 7bAb5wTHn/6gHnKfabLKn3QbxT+j3798/xHuVRwN6F7UJwDKoWwe6VrDgUNTEm6W
> 5OXWwz0WAKhpTgviIqUGLXuBmplkfQ7IDXI=
> -----END CERTIFICATE-----
> subject=/CN=couch.nine-hells.net
> issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
> ---
> No client certificate CA names sent
> Peer signing digest: SHA512
> Server Temp Key: ECDH, P-256, 256 bits
> ---
> SSL handshake has read 3862 bytes and written 327 bytes
> ---
> New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
> Server public key is 4096 bit
> Secure Renegotiation IS supported
> Compression: NONE
> Expansion: NONE
> No ALPN negotiated
> SSL-Session:
>     Protocol  : TLSv1.2
>     Cipher    : ECDHE-RSA-AES128-GCM-SHA256
>     Session-ID: 5F1A0FE31DCC123E2D1E2D44CB531986E4B86AE9EF9C27B8AABE06C5A3656215
>     Session-ID-ctx:
>     Master-Key: 2E4A24B5584BB39AB77C9D7D0721A9F2CC7768FDE12BEA0830F7ACB72A77BE0C38CCB17579C5F54C1CADE7DD1A86411F
>     Key-Arg   : None
>     Krb5 Principal: None
>     PSK identity: None
>     PSK identity hint: None
>     TLS session ticket lifetime hint: 300 (seconds)
>     TLS session ticket:
>     0000 - e9 78 23 86 40 0b 2d b2-ac 9a ba f3 1e 5e 75 35   .x#.@.-......^u5
>     0010 - 64 f5 23 f5 57 d9 22 52-73 d8 2a 41 e1 d9 a8 77   d.#.W."Rs.*A...w
>     0020 - 56 fb ae 19 a3 24 20 14-fe 7b 8e 9d 0b 5a 77 67   V....$ ..{...Zwg
>     0030 - 0d 4e e5 7e d7 00 45 4c-f9 33 ff 81 b5 af e4 27   .N.~..EL.3.....'
>     0040 - c6 a2 7d d6 50 2f 47 84-fa 4b 99 bc 9a 03 52 92   ..}.P/G..K....R.
>     0050 - fb 34 08 31 44 fa d5 36-ab dd 27 67 12 50 30 ce   .4.1D..6..'g.P0.
>     0060 - fb 5c 11 8e 87 5d 17 a4-b3 73 ea c4 58 41 8d 0c   .\...]...s..XA..
>     0070 - 9b af 8f b4 c7 80 ff bf-a0 02 a6 e1 de 6b 13 79   .............k.y
>     0080 - 45 69 45 64 4f ce 73 a2-b1 79 e6 74 26 ad 5b 48   EiEdO.s..y.t&.[H
>     0090 - 14 a5 8a a7 3a 7c 29 43-3a 9e ac 8e e8 ab 5b 09   ....:|)C:.....[.
>     00a0 - b0 d5 19 a1 7b 34 3b 0b-25 d3 91 86 ec e2 a0 71   ....{4;.%......q
> 
>     Start Time: 1461652579
>     Timeout   : 300 (sec)
>     Verify return code: 0 (ok)
> ---
> GET /.well-known/acme-challenge/zk0acTDR1rJ4seBosynJA5niKsJU0nKqD_STKwBtkD0 HTTP/1.1
> Host: www.nine-hells.net
> 
> HTTP/1.1 200 OK
> Server: nginx/1.9.14
> Date: Tue, 26 Apr 2016 06:36:27 GMT
> Content-Type: application/octet-stream
> Content-Length: 87
> Last-Modified: Mon, 25 Apr 2016 06:18:39 GMT
> Connection: keep-alive
> ETag: "571db6bf-57"
> Strict-Transport-Security: max-age=31536000
> Accept-Ranges: bytes
> 
> zk0acTDR1rJ4seBosynJA5niKsJU0nKqD_STKwBtkD0.yCerLuhuTaQrEdvYLhNIzp_RW3EKJ1A8FXwQUyl8oqw

As you can see from the above, I connected over HTTP/1.1 & SSL to www.nine-hells.net on port 443 doing a GET on the verification file I listed above - and it all worked.  The data was received... <sigh>

**Comment by falcon15500** [comment]
Here is a copy of my nginx default.conf:

[default.conf.txt](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/files/239912/default.conf.txt)

I am no NGINX expert, but it appears to be fine to me.  And the sites work fine over HTTPS.

**Comment by JrCs** [comment]
If i remember well (perhaps i'm wrong) verification is done using http protocol, not https protocol.
Can you try to get the challenge file using http protocol ?

**Comment by mvdstam** [comment]
@falcon15500 @JrCs I think I have pinpointed the problem!

Having the exact same issues here, without changed anything in particular to the `nginx.tmpl` file or anything else; it's all out of the box stuff regarding the `nginx-proxy` containers and the proxy companion container. However, this issue only seems to arise when adding new hosts after restarting the nginx containers with either `docker-compose restart` or `docker-compose stop && docker-compose start`. Restarting the three individual containers one by one is fine. This is all tested on the staging environment of letsencrypt.org.

# Environment

- Host OS: `CoreOS 1010.3.0`
- Docker version: `1.10.3`
- Docker-compose format used: `'2'`

# Reproducing the issue

- Make sure the `certs` directory which stores the certificates is empty to start off with
- Setup and start the three nginx containers (proxy, gen and ssl companion)
- Add some containers that need to be proxied with SSL, each with it's own SSL certificate being generated. This will succeed, without any problems.
- Restart all of the containers with `docker-compose restart`
- Add a new container after the restart. This will result in the `HTTP-503` issue described when creating and verifying the new SSL certificate. Each renewal or creation action will result in this issue.

# Workaround

Simply remove the set of `nginx` containers using `docker-compose stop` and `docker-compose rm -f`. After that, start them again using `docker-compose up -d` and new certificates are generated without issues. In case of a server malfunction or really needing to restart the containers, running the following command should "fix" the SSL generation:

`docker-compose stop && docker-compose rm -f && docker-compose up -d`

Since all certificates are stored on the docker host, this doesn't really matter much except for the fact that it's kind of a hassle to do.

# Cause

My guess is that this has something to do with the way containers are linked with other containers, and that restarting all of them at once causes a interruption somehow. As said, the (testing) SSL certificates that are created with errors seem to work fine. Which makes sense, as we're not interested in validated certificates anyway on staging environments.

Hope this gives you enough info to at least know where to look.

**Comment by JrCs** [comment]
Perhaps the issue is the docker-compose fault ?
Have you try to start the container in order manually without using docker-compose ?

**Comment by mvdstam** [comment]
@JrCs Well, restarting the containers one by one with (or without) docker-compose doesn't cause the problem. It's the full `docker-compose stop` command that causes some kind of desynchronization issue. 

The cause of the HTTP-503 itself seems logical, as `nginx-proxy` creates a default block for the nginx.conf config which handles all unknown URI's and returns them as a HTTP-503. My guess is that the nginx server doesn't correctly pick up the `/.well-known/acme-challenge` (as done by https://github.com/kuba/simp_le) after a restart. Thoughts?

**Comment by falcon15500** [comment]
I don't use docker-compose at all.

And while the renew process is getting 503's, if I use a browser to go to
the same URL, it works perfectly.

**Comment by JrCs** [comment]
@mvdstam can you try and make tests using the stable image instead of the latest one ?

**Comment by JrCs** [comment]
@falcon15500 do you use a dedicated network for your container.
If yes can you check that the LE container can access the challenge files using the public ip ?

**Comment by falcon15500** [comment]
BOOM! Headshot! :)

Yes, I use the same dedicated bridge network for all my containers.  No, the LE container gets a 503 when I try to do a wget of any of the challenge files! :)

So now we can reproduce it in the container - how do we resolve it?

**Comment by JrCs** [comment]
You need to connect the nginx proxy container to your dedicated network.
If you use a firewall check also that you can telnet the port 80 of the nginx proxy container from the LE container.
Also if you use a version of docker > 1.10 be sure to not start docker with the option `--userland-proxy=false`

**Comment by falcon15500** [comment]
I have just checked.  All my containers are on the same network, including the nginx instance and the LE instance.  Telnet to port 80 of the nginx instance works fine from the LE container... However.

When I simulate a genuine HTTP call to the nginx proxy, passing correct host etc, I get the same 503 error in return.

GET /index.html HTTP/1.1
HOST: www.nine-hells.net

HTTP/1.1 503 Service Temporarily Unavailable
Server: nginx/1.9.14
Date: Wed, 01 Jun 2016 04:00:11 GMT
Content-Type: text/html
Content-Length: 213
Connection: keep-alive

<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.9.14</center>
</body>
</html>

**Comment by falcon15500** [comment]
I see it... I think.  The only part of the generated nginx default.conf that listens on port 80 is:

server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}

All of the other stanzas are:

listen 443 ssl http2 ;

So if a HTTP request shows up, it's going to get a 503.

**Comment by falcon15500** [comment]
And to test... I added a:

Listen 80;

Line to one of my vhosts in the default.conf and reloaded the nginx config (without triggering the docker-gen process).  And this time to port 80 from the LE container:

```
bash-4.3# telnet nginx 80
GET /index.html HTTP/1.1
HOST: www.nine-hells.net

HTTP/1.1 200 OK
Server: nginx/1.9.14
Date: Wed, 01 Jun 2016 04:21:41 GMT
Content-Type: text/html
Content-Length: 7
Connection: keep-alive
Last-Modified: Tue, 02 Feb 2016 00:51:18 GMT
ETag: "7-52abee64115fc"
Accept-Ranges: bytes
Strict-Transport-Security: max-age=31536000

Hello!
```

So... The generated default.conf doesn't allow for normal HTTP traffic?

**Comment by falcon15500** [comment]
<sigh> Newest template 
https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl

Seems to fix this issue.

Was fixed via commit on May 2.

:)  Thanks for your help.

**Comment by falcon15500** [comment]
Next thought...

Will the renewal process work with the default "redirect" instead of "noredirect"?  I can't really test until my certs are up for renewal. :(

**Comment by falcon15500** [comment]
Okay...  An update.  There is a known issue for the docker-gen container, whereby the newest nginx.tmpl file causes the "no server line in upstream stanza" issue I referred to above.  There is a workaround, however.

When you run the docker-gen container, expose some arbitrary port (doesn't have to be published) and then the nginx default.conf will be generated correctly.

So it's now "all good", provided that the LE renewal process accepts starting a HTTP connection and being 301'd up to HTTPS.

(Sorry for all the posts today!)

**Comment by JrCs** [comment]
Thx for all the informations

**Comment by maxkueng** [comment]
I had the same problem. Then I used the [nginx.tmpl from the 0.3.0 tag](https://github.com/jwilder/nginx-proxy/blob/0.3.0/nginx.tmpl) and the error changed from 503 to 404. The next thing I figured out is that you can't customize the html directory of the nginx container with `-v /my/custom/html/dir:/usr/share/nginx/html`. It has to be `-v /usr/share/nginx/html`.

**Comment by falcon15500** [comment]
> The next thing I figured out is that you can't customize the html directory of the nginx container with -v /my/custom/html/dir:/usr/share/nginx/html. It has to be -v /usr/share/nginx/html or you get 404 errors.

Can't say my experience mirrors that.  My run command for my nginx container has:

`-v /docker/nginx/html:/usr/share/nginx/html`

And I have no issues at present.

M.

**Comment by maxkueng** [comment]
@falcon15500: Interesting. After not getting it to work for days, that's the only thing I had to change to make it work. I'm using `nginx:latest`, `jwilder/docker-gen:latest` and `jrcs/letsencrypt-nginx-proxy-companion:stable`.

```
$ docker -v
Docker version 1.11.2, build b9f10c9
```

**Comment by falcon15500** [comment]
Okay... My certificate successfully self-renewed today!  w00t! :)
The only very minor niggle, is that even though nginx was reloaded (as per logs), the old certs still showed until I restarted the nginx container.

Still, am happy!  You can close this.  Thanks again!
