### ISSUE TITLE
Your connection to this site is not fully secure

### ISSUE THREAD

**Issue by indapublic** [JrCs/docker-letsencrypt-nginx-proxy-companion#559]
Hi!

Could somebody explain why I receive this notification for my website? Certificate looks valid.

![image](https://user-images.githubusercontent.com/856260/61794986-c6197d80-ae65-11e9-809e-65c484621811.png)

<img width="484" alt="Screenshot 2019-07-24 at 22 53 20" src="https://user-images.githubusercontent.com/856260/61795306-6f607380-ae66-11e9-92a3-2b9271b24b2b.png">

At the same time, there is a second domain on same machine where everything is fine.

**Comment by indapublic** [comment]
BTW. It shows warning for https://website.com, but for https://website.com/some-path all is fine. Why?

**Comment by lounagen** [comment]
Hello,
May be you could track in the dev console (and in your code) if you have an unsecure 'http://...' form in your main page?
https://stackoverflow.com/questions/46563293/chrome-you-connection-to-this-site-is-not-fully-secure

**Comment by indapublic** [comment]
Thanks @lounagen! Will check any resources. But no any messages in my console.

**Comment by lounagen** [comment]
Are you using a WordPress behind?
Just found a 'wordpress plugin' on Google to set your WordPress ssl compliant (seriously? :-) )
https://youtu.be/AUHPrgvNthc

**Comment by indapublic** [comment]
Nope, it's my Symfony application

**Comment by buchdag** [comment]
@indapublic if the certificate was generated correctly I'm not sure to understand how this is a `letsencrypt-nginx-proxy-companion` issue. That's pretty much the only thing this container does, getting certificate from Let's Encrypt, putting them in a specific place with a specific name, and reloading another container.

**Comment by indapublic** [comment]
Ok. Will close
