### ISSUE TITLE
[SOLVED] Challenge validation has failed.

### ISSUE THREAD

**Issue by kjlhgfds** [JrCs/docker-letsencrypt-nginx-proxy-companion#563]
Hi there !
Since the last update of Windows Docker (2.1.0.0), I can't acces my containers from outside (http pr https). It worked before the update and I changed nothing but did the update and it broke the redirection.
I have the 

> Challenge validation has failed

error.
My DynHost are well configured (I can see my IP address resolved in the logs) and my internet box has all the mandatory ports open (80, 443 and those for each containers).
Since there are sensible informations in the logs, is there some specific infos you could need to have a better understanding of my issue ?
Thanks

**Comment by kjlhgfds** [comment]
I downgraded Windows Docker and the problem is gone, so it's definitly an upgrade issue.

**Comment by kjlhgfds** [comment]
Solution to the probleme here : #4409

**Comment by buchdag** [comment]
@kjlhgfds : is this the correct solution ?  https://github.com/docker/for-win/issues/4391#issuecomment-520420942

**Comment by kjlhgfds** [comment]
> 
> 
> @kjlhgfds : is this the correct solution ? [docker/for-win#4391 (comment)](https://github.com/docker/for-win/issues/4391#issuecomment-520420942)

For me, yes.

**Comment by buchdag** [comment]
Ok, closing this issue then.
