### ISSUE TITLE
Documentation for default.conf in this case?

### ISSUE THREAD

**Issue by dm17** [JrCs/docker-letsencrypt-nginx-proxy-companion#565]
In docker, nginx-proxy has a default /etc/nginx/conf.d/default.conf, which I don't see action items about in the docs... It has a lot of config, but I don't know how it applies to the default setup. Is everyone replacing this default.conf file with a custom one?

In my case, I have 3 node services, all need access to the internet, all run on different ports (and talk to each other within docker). The main one is running on port 3000:3000 in docker, but it has VIRTUAL_HOST=3000 specified - so won't it get bound to 80/443 via the docker-letsencrypt-nginx-proxy-companion setup? How does the default.conf relate to the various docker containers running that have VIRTUAL_HOST & VIRTUAL_PORT specified?

Any good examples for a default.conf in this kind of docker setup?

Thanks!

**Comment by dm17** [comment]
And also, if I replace /etc/nginx/conf.d/default.conf with something fairly default, then how will the docker-letsencrypt-nginx-proxy-companion setup break?

**Comment by buchdag** [comment]
Hi. I think you've kind of missed how `nginx-proxy`/`docker-gen` works. It actually generates `/etc/nginx/conf.d/default.conf` automatically from your containers environment variables. That's the whole point of the entire setup, you start containers with a specific set of environment variables and the proxy set itself up automatically. You should definitely read `nginx-proxy`'s doc in detail.

Furthermore, this repo and [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) are two different projects (event if the latter is meant to complement the former) and aren't maintained by the same peoples. We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues).

As a reminder, this project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purposes are to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by the `docker-gen` template, wether `docker-gen` runs with `nginx-proxy` or in its own container.
-  reload the nginx proxy when needed (cert creation or renewal).

**Comment by dm17** [comment]
Thanks - I understand better now. It is a relief that I can count on that default.conf to be correctly generated - and I assume the rest of the nginx config files as well.

I'm mostly confused how the VIRTUAL_HOST & VIRTUAL_PORT vars from my 3 containers (that also have port: "host:container" defined) get mapped to nginx's 80 & 443. Inside of docker my 3 containers talk to each other on various ports - and they all need to talk to the internet as well. Each service talks to the other services using its docker service name - and each service name is also in /etc/hosts. This all had it working well in dev - but not production.

Any debugging suggestions?
Thanks again.

**Comment by buchdag** [comment]
Again this repo is not [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy)

Please submit your `nginx-proxy` related questions directly to the `jwilder/nginx-proxy` repo.

**Comment by dm17** [comment]
OK thanks - FYI: I'm using the nginx:alpine, not jwilder/nginx-proxy - but I will ask on that repo too.

**Comment by buchdag** [comment]
Whether you use the basic setup with `nginx-proxy` or [separate containers setup](https://github.com/jwilder/nginx-proxy#separate-containers) with `nginx` + `docker-gen`, this is still `nginx-proxy`.

**Comment by dm17** [comment]
OK, still waiting on a reply there. I'm wondering if multiple docker-compose services have the same VIRTUAL_HOST=domain_name, then if that is the cause of the problem. Perhaps each docker services needs its own subdomain in terms of the VIRTUAL_HOST.
