### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by davidmoshal** [JrCs/docker-letsencrypt-nginx-proxy-companion#567]
wondering if there is an example showing how to reverse proxy websockets.
ie: https and wss

**Comment by buchdag** [comment]
Hi.

This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

What you want to achieve depends entirely on the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different peoples.

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)

**Comment by davidmoshal** [comment]
Got it, thanks. 
My apologies.
 Dave
