### ISSUE TITLE
"exec format error" on Raspberry Pi 4 with Buster

### ISSUE THREAD

**Issue by RRFfm** [JrCs/docker-letsencrypt-nginx-proxy-companion#568]
A newly setup Raspberry Pi 4 with Buster-Release and docker-compose version 1.21.0 (docker-py version: 3.4.1, CPython version: 3.7.3, OpenSSL version: OpenSSL 1.1.1c  28 May 2019) caused '_standard_init_linux.go:211: exec user process caused "exec format error_"'.
I found "https://github.com/containers/buildah/issues/475", saying
_For anyone who got a standard_init_linux.go:190: exec user process caused "no such file or directory" error after applying this fix, you're probably on an alpine base image which does not come with bash.

Replacing #!/bin/bash with #!/bin/sh will do the trick!_

Is this a possible solution?

**Comment by buchdag** [comment]
Hi.

Was the image built locally on your Raspberry Pi 4 from the Dockerfile ?

**Comment by RRFfm** [comment]
Hi,
no, i just used docker pull to get the image.

rgds,
rrffm

**Comment by buchdag** [comment]
We don't have any other arch beside `amd64` available on Dockerhub (related discussion here).

If you want to use this container on `arm` archs, you'll have to clone the repo on your `arm` host and build the image on it with `docker build`.

Note that `nginx-proxy` and `docker-gen` aren't available on Dockerhub for non `amd64` archs either, so having a fully working stack will involve a bit more work. I've made https://github.com/buchdag/multiarch-letsencrypt-nginx-proxy to help people do this.

**Comment by RRFfm** [comment]
Hi,

thanks for your quick response.

i already have nginx running as proxy and a second one for nextcloud. i inteded to use nginx-companion with my existing nginx/nextcloud environment. but if i understand your advice correctly, i have to use nginx-proxy…

 

rgds,

rrffm

 

Von: Nicolas Duchon [mailto:notifications@github.com] 
Gesendet: Montag, 19. August 2019 13:17
An: JrCs/docker-letsencrypt-nginx-proxy-companion <docker-letsencrypt-nginx-proxy-companion@noreply.github.com>
Cc: RRFfm <git@roland-roeder.de>; Author <author@noreply.github.com>
Betreff: Re: [JrCs/docker-letsencrypt-nginx-proxy-companion] "exec format error" on Raspberry Pi 4 with Buster (#568)

 

We don't have any other arch beside amd64 available on Dockerhub (related discussion here).

If you want to use this container on arm archs, you'll have to clone the repo on your arm host and build the image on it with docker build.

Note that nginx-proxy and docker-gen aren't available on Dockerhub for non amd64 archs either, so having a fully working stack will involve a bit more work. I've made https://github.com/buchdag/multiarch-letsencrypt-nginx-proxy to help people do this.

**Comment by buchdag** [comment]
By "nginx running as a proxy", do you mean you manually configured a vanilla `nginx` container to serve as a reverse proxy for your `nextcloud` container ?

**Comment by RRFfm** [comment]
yes

 

Von: Nicolas Duchon [mailto:notifications@github.com] 
Gesendet: Montag, 19. August 2019 13:50
An: JrCs/docker-letsencrypt-nginx-proxy-companion <docker-letsencrypt-nginx-proxy-companion@noreply.github.com>
Cc: RRFfm <git@roland-roeder.de>; Author <author@noreply.github.com>
Betreff: Re: [JrCs/docker-letsencrypt-nginx-proxy-companion] "exec format error" on Raspberry Pi 4 with Buster (#568)

 

By "nginx running as a proxy", do you mean you manually configured a vanilla nginx container to serve as a reverse proxy for your nextcloud container ?

**Comment by buchdag** [comment]
As the name imply and the first line of the doc clearly states, this container is meant to be used with [`nginx-proxy`](https://github.com/jwilder/nginx-proxy) (the container, not `nginx` used as a reverse proxy in the broader sense). It's not meant to be used with a static, manually configured reverse proxy.

**Comment by buchdag** [comment]
Closing due to lack of update from issue's creator.
