### ISSUE TITLE
generate multiple certs for single nginx container

### ISSUE THREAD

**Issue by sandrodz** [JrCs/docker-letsencrypt-nginx-proxy-companion#57]
is it possible to generate multiple certificates like:

+    VIRTUAL_HOST: domain1.com,domain2.com,domain3.com
+    LETSENCRYPT_HOST: domain1.com,domain2.com,domain3.com

I've single nginx server behind nginx-proxy. I don't want to have separate nginx server for each domain.

this companion doesn't generate ssl for all mentioned domains: domain1.com,domain2.com,domain3.com

**Comment by JrCs** [comment]
Yes it must work as you describe.

**Comment by sandrodz** [comment]
Hi, sorry it took me a while to play with all possible combinations, hence the belated reply.

But I don't seem to understand the logic. Sometimes specific ssl is generated for domain, sometimes same one is used for several domains... I cannot really comprehend the logic behind these.

![screen shot 2016-05-09 at 6 46 34 pm](https://cloud.githubusercontent.com/assets/8479569/15117814/5de8b640-161a-11e6-8ccc-a35a1013e9f2.png)
![screen shot 2016-05-09 at 6 47 03 pm](https://cloud.githubusercontent.com/assets/8479569/15117815/61287354-161a-11e6-8127-cceab2fbbd51.png)
![screen shot 2016-05-09 at 7 06 04 pm](https://cloud.githubusercontent.com/assets/8479569/15117816/6441b1fe-161a-11e6-98bd-8fb6afef4763.png)

**Comment by JrCs** [comment]
All seems ok except wiseadvices.com. Perhaps you create it before grouping all domains. So remove wiseadvices.com directory and relaunch the companion.

**Comment by sandrodz** [comment]
so:
```
adjara -> adjara
cdn -> adjara
demos -> adjara
njord -> njord
shop -> shop
```

both shop and njord are in the group too, but they have their own certs?

**Comment by sandrodz** [comment]
I deleted old certs dir and let it recreate. and I see this:

![screen shot 2016-05-09 at 9 11 26 pm](https://cloud.githubusercontent.com/assets/8479569/15122134/b24167c8-162e-11e6-85a2-cca2d8b6f58a.png)

**Comment by JrCs** [comment]
The "main" domain is the ** first ** domain set in LETSENCRYPT_HOST variable

**Comment by sandrodz** [comment]
yeah I got that :) also symbolic links make sense. But why is that domain displayed in ssl overview? common name should be we are.de  not adjara right?

**Comment by JrCs** [comment]
Because it's the "main" domain. Open certificat details to see other domain that are in the certificat:
![screenshot](http://puu.sh/oMFR9/3f1664f578.png)

**Comment by sandrodz** [comment]
we are de is the first in LETSENCRYPT_HOST variable, you can also see that symbolic links point to we are de not adjara. So how come adjara is the main?

**Comment by sandrodz** [comment]
![screen shot 2016-05-10 at 3 03 22 pm](https://cloud.githubusercontent.com/assets/8479569/15144424/625da068-16c0-11e6-9a72-76013387dd37.png)

**Comment by JrCs** [comment]
Remove all certs and restart companion.

**Comment by sandrodz** [comment]
result is same, could it be alphabetic?

**Comment by JrCs** [comment]
No, it's the first one i'm sure

**Comment by sandrodz** [comment]
hang on 5mins I'll make a video

**Comment by JrCs** [comment]
You must see this message in the logs:
> Creating/renewal $base_domain certificates...

Where $base_domain is your first host of LETSENCRYPT_HOST variable

**Comment by sandrodz** [comment]
Here you go, contains log messages also.

**Comment by JrCs** [comment]
Sorry i can't acces to the video at the moment. Check if the message in the logs is right.

**Comment by sandrodz** [comment]
its correct 
![screen shot 2016-05-10 at 3 38 05 pm](https://cloud.githubusercontent.com/assets/8479569/15145201/48c59250-16c5-11e6-8da2-bcf68f483fe3.png)

**Comment by JrCs** [comment]
So all certs must point to the weare.de.com directory ?

**Comment by sandrodz** [comment]
yes all of them point to weare.de.com dir like on screenshots.

problem is common name that certificate displays on all pages, which is adjaragroup.

**Comment by JrCs** [comment]
Check that a new certificat has been created (check details in certificate about creation date).
You can try also to remove adjaragroup from LETSENCRYPT_HOST and in the certs directory and restart the companion. If a new certificat is created you must not see adjaragroup in the common name.

**Comment by JrCs** [comment]
It seems that simp_le create SAN with domain sort alphabetically. So the common name will be adjaragroup. But it's doesn't care because your certificat is valid for all alternate domains.

**Comment by sandrodz** [comment]
So your saying even if I remove adjara, I will get common name next in the alphabetic order that is cdn ?

**Comment by JrCs** [comment]
Yes i think.

**Comment by sandrodz** [comment]
Could this be an issue? https://community.letsencrypt.org/t/common-name-change-after-using-expand-flag/14174

**Comment by sandrodz** [comment]
after searching and reading everything this seems to be the root issue: https://github.com/certbot/certbot/issues/2798

so since v 0.5 this bug was introduced in letsencrypt client. 0.6 version includes the fix.

At what version is your docker container?

**Comment by JrCs** [comment]
The companion container doesn't use the letsencrypt client but [simp_le](https://github.com/kuba/simp_le).

**Comment by sandrodz** [comment]
I see, and there is PR that changes things: https://github.com/kuba/simp_le/pull/105

**Comment by sandrodz** [comment]
btw, my workaround: I added subdomain abc.main.domain to get it to be the common name.

**Comment by JrCs** [comment]
Good !
