### ISSUE TITLE
Custom Nginx Error Messages?

### ISSUE THREAD

**Issue by dm17** [JrCs/docker-letsencrypt-nginx-proxy-companion#574]
It seems like most people use CDNs for this type of functionality these days, but is there some way to have "site will be back momentarily" sign until all of the nginx-proxy-fed docker services finish starting? This seems like a pretty common use case, so I figured someone here would have a good suggestion or extensions they've written to do this. So if visiting the domain while the services are still coming up - instead of seeing an nginx error (meaningless to most people) - it shows a "please check back in a few moments" message.

**Comment by buchdag** [comment]
Hi.

This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

What you want to achieve depends entirely on the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different peoples.

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)
