### ISSUE TITLE
Custom changes to nginx config overwritten by letsencrypt renewal

### ISSUE THREAD

**Issue by kelsotodd** [JrCs/docker-letsencrypt-nginx-proxy-companion#575]
Good day. 

I have an instance running and mapped the config volumes to the local host. 

I needed to increase the client_max_body_size to cater for larger file uploads, therefore I changed the config and restarted the container. 

The expected behaviour would be that nginx would now increase the upload size based on the changed config, but it seems that starting both nginx and le result in the nginx config being overwritten and the parameter being removed.

I'd like to find out if there is a hook or another method to include the parameter update in order to update the configuration as part of the le refresh.

Thanks

**Comment by buchdag** [comment]
Hi.

This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

What you want to achieve depends entirely on the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different peoples.

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)
