### ISSUE TITLE
Any site just shows "welcome to nginx"

### ISSUE THREAD

**Issue by jkbecker** [JrCs/docker-letsencrypt-nginx-proxy-companion#577]
Hi,
I just set up nginx-proxy plus the companion, and started migrating my websites to this setup.I started out with two static websites, just using nginx:alpine and a volume connecting the web root. This is how I run my two static sites:

```
docker run -d \
	--name example.com \
	--env "VIRTUAL_HOST=example.com" \
	--env "VIRTUAL_PORT=80" \
	--env "LETSENCRYPT_HOST=example.com" \
	--env "LETSENCRYPT_EMAIL=mail@example.com" \
	--volume example.com_site:/usr/share/nginx/html \
	--restart always \
	nginx:alpine
```

when I navigate to the site, all I get is a "Welcome to nginx!" message.
Navigating explicitly to URLs that I know exist (e.g. example.com/test/test.html) yields a 404.

At this point, I don't even know how to debug this.. where do I start? Thanks in advance for your help!

**Comment by jkbecker** [comment]
Okay, so I just discovered that there are directories in `/var/lib/docker/volumes`which are named `example.com_site` and contain a `_data`  directory. In there sits an index.html which is the file that is served (when I change that file I can see the changes live).

Why is this _data stuff in my volume rather than the directory I set up for it?

**Comment by buchdag** [comment]
Hi.

`--volume example.com_site:/usr/share/nginx/html` instruct your container to mount [named volume](https://docs.docker.com/storage/volumes/) `example.com_site` inside the container at `/usr/share/nginx/html`.

If you want to bind mount a directory from your host instead, please follow [those instructions](https://docs.docker.com/storage/bind-mounts/) and use absolute paths.

**Comment by jkbecker** [comment]
Thank you! It was resolved by using an absolute path.
