### ISSUE TITLE
v1.12: account_key.json does not exist. Skipping ownership and permissions check

### ISSUE THREAD

**Issue by jwaes** [JrCs/docker-letsencrypt-nginx-proxy-companion#591]
Since upgrading to v12 (latest) i see the `acme-v02.api.letsencrypt.org` directory is created under accounts in my `nginx-proxy_certs` volume but the `directory `subdirectory is empty

But i see these errors appear in my logs

```
/etc/nginx/certs/www.jaco.tech /app
Creating/renewal www.jaco.tech certificates... (www.jaco.tech)
2019-10-17 08:53:09,561:INFO:simp_le:1546: Certificates already exist and renewal is not necessary, exiting with status code 1.
/app
Warning: /etc/nginx/certs/www.jaco.tech/account_key.json does not exist. Skipping ownership and permissions check.
Warning: /etc/nginx/certs/www.jaco.tech/account_reg.json does not exist. Skipping ownership and permissions check.
Warning: /etc/nginx/certs/accounts/acme-v02.api.letsencrypt.org/directory/default_key.json does not exist. Skipping ownership and permissions check.
Warning: /etc/nginx/certs/accounts/acme-v02.api.letsencrypt.org/directory/default_reg.json does not exist. Skipping ownership and permissions check.
Sleep for 3600s
```

**Comment by buchdag** [comment]
Thanks for reporting this.

My guess is your certificate is still valid, so `simp_le` does not attempt to renew it and does not create the new ACME v2 account. The subsequent permission check then complain about non existent files.

This should have no consequences other than those bogus warning messages in the log.

I'll come up with a fix asap.

**Comment by jwaes** [comment]
Indeed, my certificate is still valid and works as expected.
But clutter in the logfile.

**Comment by buchdag** [comment]
Could you try pulling `duch/letsencrypt-nginx-proxy-companion:fix-591` and confirm it fixes the bug ?

**Comment by jwaes** [comment]
i confirm that the warnings are gone
