### ISSUE TITLE
Alternate Ports?

### ISSUE THREAD

**Issue by LeeThompson** [JrCs/docker-letsencrypt-nginx-proxy-companion#593]
`Your host must be publicly reachable on both port 80 and 443.`

I want to use this to SSL/reverse-proxy for Rocket.Chat which I want to keep 3000 as it's external port, does the above requirement still apply?

**Comment by buchdag** [comment]
Yep. See https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/428 for detailed reason.

Also note that if your are using another external port than `80`/`443` your are actually bypassing the reverse proxy entirely. The whole point of the reverse proxy is to make your services reachable over standard ports and to proxy traffic to them based on the hostname being requested.
