### ISSUE TITLE
Good practice to mount logs - so they don't get wiped @ stop/start?

### ISSUE THREAD

**Issue by dm17** [JrCs/docker-letsencrypt-nginx-proxy-companion#595]
Question: do you think it is good practice to add the logs to a volume on the host (like the config files), so they don't get lost with stopping / starting of our docker-compose setups?
Thanks.

**Comment by buchdag** [comment]
Nope. User Docker's logging drivers if you need logs persistence.

https://docs.docker.com/config/containers/logging/configure/
