### ISSUE TITLE
Companion is using ACMEv1 instead of ACMEv2

### ISSUE THREAD

**Issue by Ponchia** [JrCs/docker-letsencrypt-nginx-proxy-companion#598]
Hello!
Everything was working fine until this morning, I had the bad idea of deleting the volume containg the cert.
Now when the companion try to get a new cert it will return this error:
`ACME server returned an error: urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
`

As far as I'm understanding this should not happen as [here](https://docs.docker.com/compose/compose-file/) it is written that the library use the new protocol

I'll leave here my docker-compose, before I was using normal Nginx and doker gen, now I'm switching to just nginx-proxy and the companion.

I'm not even sure where to look in order to solve this issue, I'm sorry if it is the wrong place :)

I've removed the docker compose for now beacuse I was unable to format it right. If neede I'll add it again as attachment

**Comment by Ponchia** [comment]
Well, I'm not even sure what or why, but I pulled the image again.
Now everything is working fine.

**Comment by bastibense** [comment]
For those hitting the same problem. In my case my docker had a 5 month old cached version of the companion image cached. I ran `docker-letsencrypt-nginx-proxy` and now it's working correctly.

**Comment by k-sav** [comment]
@bastibense did you have to restart the container after pulling the latest image?
