### ISSUE TITLE
New key every month 

### ISSUE THREAD

**Issue by exussum12** [JrCs/docker-letsencrypt-nginx-proxy-companion#599]
Using this package the certificate seems to renew each month. Is that correct ? I would have expected this to renew 2 weeks before the expiration instead of 2 months before

**Comment by ignasdamunskis** [comment]
> Using this package the certificate seems to renew each month. Is that correct ? I would have expected this to renew 2 weeks before the expiration instead of 2 months before

I believe they have no information on expiration date of a certificate so it runs the generation every month just in case.

**Comment by exussum12** [comment]
Why wouldn't it have that info ? It manages the certs you can use the exit status of openssl -checkend to check if the cert will expire in x days.

**Comment by buchdag** [comment]
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Let's-Encrypt-and-ACME.md#automatic-certificate-renewal

**Comment by exussum12** [comment]
I will check that out. It's odd as that definitely isn't the case in my case

**Comment by buchdag** [comment]
I just checked one my le companion container used in production, most of the active certificates have been issued more than one month ago.

How did you determine that your certificates are being renewed every month ?

**Comment by exussum12** [comment]
I use the CT monitoring from Facebook and get alerts way too often.

**Comment by buchdag** [comment]
Can you check what's going on in your le companion container logs ?

**Comment by exussum12** [comment]
The box behind my load balancer was getting a cert too. Closing as it's my own mistake
