### ISSUE TITLE
export CONTAINER_ID in entrypoint.sh does not reliably evaluate to the container id

### ISSUE THREAD

**Issue by ggramlich** [JrCs/docker-letsencrypt-nginx-proxy-companion#6]
The line

    export CONTAINER_ID=$(cat /proc/self/cgroup | grep 'docker' | sed 's/^.*\///' | tail -n1 | sed 's/^.*-//;s/\..*$//')

from entrypoint.sh does not seem to work reliably for me.

For debugging purposes, I did a `docker run --entrypoint=/bin/bash`. When I call `cat /proc/self/cgroup`, inside the container, I get

```
9:devices:/system.slice/docker.service/docker/6713ebd59c0cc35f61282835fbfabf37c8275caaa83a006ff94f0bff5f713258
8:cpuset:/docker/6713ebd59c0cc35f61282835fbfabf37c8275caaa83a006ff94f0bff5f713258
7:blkio:/docker/6713ebd59c0cc35f61282835fbfabf37c8275caaa83a006ff94f0bff5f713258
6:cpuacct,cpu:/docker/6713ebd59c0cc35f61282835fbfabf37c8275caaa83a006ff94f0bff5f713258
5:debug:/
4:perf_event:/docker/6713ebd59c0cc35f61282835fbfabf37c8275caaa83a006ff94f0bff5f713258
3:memory:/docker/6713ebd59c0cc35f61282835fbfabf37c8275caaa83a006ff94f0bff5f713258
2:freezer:/docker/6713ebd59c0cc35f61282835fbfabf37c8275caaa83a006ff94f0bff5f713258
1:name=systemd:/system.slice/docker.service
```

You can see, that the `tail -n1` cannot deliver the container ID.

I built a custom image for armhf. (See https://github.com/ggramlich/docker-letsencrypt-nginx-proxy-companion/blob/armhf/Dockerfile.armhf)

```
> uname -a
Linux 6713ebd59c0c 3.10.92-3-ARCH #1 SMP PREEMPT Mon Nov 23 18:35:54 MST 2015 armv7l Linux

> docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5-dirty
 Built:        Mon Nov 23 14:47:45 UTC 2015
 OS/Arch:      linux/arm

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.5.1
 Git commit:   a34a1d5-dirty
 Built:        Mon Nov 23 14:47:45 UTC 2015
 OS/Arch:      linux/arm
```

Thanks for your work. I would be really interested in getting this to run on ARM boards.

**Comment by ggramlich** [comment]
Just some ideas from stackoverflow, which should work for me and hopefully everybody:

Use --cidfile Option
http://stackoverflow.com/a/26980210/32679

Go for a specific line from the output, like the cpu line
http://stackoverflow.com/a/28483314/32679

**Comment by JrCs** [comment]
@ggramlich can't use --cidfile in docker-compose currently :(

I will find a solution that work for everybody

**Comment by ggramlich** [comment]
Thanks so much.

I was just able to make my first https request to a gogs server behind my dyndns address. This is freaking awesome :-)

**Comment by klud1** [comment]
I know support for other platform is not that important, still it would be great to have an official image of this project for armhf

**Comment by ggramlich** [comment]
In the meantime I switched over to traefik. Took me a little longer to configure, but the arm image is up to date and, unlike the nginx-proxy and the companion, no breaking changes.

https://hub.docker.com/r/hypriot/rpi-traefik/
https://hub.docker.com/r/nsteinmetz/traefik-arm/

**Comment by klud1** [comment]
Thing is you can't set proxy headers in traefik yet, as you do in nginx
