### ISSUE TITLE
only put nginx config in 1 vhost default

### ISSUE THREAD

**Issue by sandrodz** [JrCs/docker-letsencrypt-nginx-proxy-companion#60]
Is it possible to stop writing this to each vhost?

```
## Start of configuration add by letsencrypt container
location /.well-known/acme-challenge/ {
    auth_basic off;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
## End of configuration add by lets encrypt container
```

ideally it would write to 1 host, like default and not each and every one it finds.

**Comment by JrCs** [comment]
No because if you have a vhost declared it will override the default config.
So we need to declare the config in that specific vhost.
