### ISSUE TITLE
t

### ISSUE THREAD

**Issue by ngoonee** [JrCs/docker-letsencrypt-nginx-proxy-companion#615]

**Comment by buchdag** [comment]
Err, okay.

**Comment by ngoonee** [comment]
Sorry, must have accidentally opened this (probably did not realize the compose box was focused when trying to switch tabs with tridactyl).

**Comment by ngoonee** [comment]
Sorry, must have accidentally opened this (probably did not realize the compose box was focused when trying to switch tabs with tridactyl).
