### ISSUE TITLE
filerun running on port 8080

### ISSUE THREAD

**Issue by manish-fn** [JrCs/docker-letsencrypt-nginx-proxy-companion#621]
How can i get my app (running on port 8080) to work on https after i have installed nginx-proxy and letsencrypt?
version: '2'

services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_USER: your_filerun_username
      MYSQL_PASSWORD: your_filerun_password
      MYSQL_DATABASE: your_filerun_database
    volumes:
      - /filerun/db:/var/lib/mysql

  web:
    image: afian/filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: your_filerun_database
      FR_DB_USER: your_filerun_username
      FR_DB_PASS: your_filerun_password
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8080:80"
    volumes:
      - /filerun/html:/var/www/html
      - /filerun/user-files:/user-files

**Comment by buchdag** [comment]
Please do not open three separate issues for the same problem.
