### ISSUE TITLE
Update "stable" Version to 1.12 or greater

### ISSUE THREAD

**Issue by gloomytree** [JrCs/docker-letsencrypt-nginx-proxy-companion#622]
Hi, 

i'd recommend to upgrade the version with the "stable" tag soon. I have an automated update process that uses jrcs/letsencrypt-nginx-proxy-companion:stable and i had to switch to the "latest" tag, so ACME 2 is supported. Letsencrypt is sending emails if you are using the deprecated v1. 

I figure I'm not alone with this issue, and especially new domains will fail always. The stable version can not be labled as stable anyways, because of this. 

Greetings and thank you for developing this awesome container!! It makes everything so easy.

**Comment by guysoft** [comment]
Does anyone have an idea how to Pull request this?
Also I have a feeling someone already has a solution on docker hub?

**Comment by buchdag** [comment]
The `stable` branch is now even to the `master` branch, and the corresponding `stable` image has been pushed to Dockerhub. Sorry for the delay.

**Comment by guysoft** [comment]
@buchdag So it should work now if I do docker pull? Or is there anything else that needs to be done?

**Comment by gloomytree** [comment]
> @buchdag So it should work now if I do docker pull? Or is there anything else that needs to be done?

make sure you use the "stable" or "latest" tag. Then you are fine.

**Comment by buchdag** [comment]
@guysoft yep, `latest` and `stable` tags on Dockerhub are now on the same code level.

**Comment by guysoft** [comment]
ACME 2 is supported is default or only supported?

**Comment by buchdag** [comment]
@guysoft ACME V2 is the only protocol supported from `v1.12` onward, so yes it's default.
