### ISSUE TITLE
Proxy config wiped after certicicates renewal

### ISSUE THREAD

**Issue by jarkkoto** [JrCs/docker-letsencrypt-nginx-proxy-companion#627]
Hey!

I use this jrcs-letscrypt-nginx-proxy-companion with Nextcloud. I have to put max file size config in default.conf file that i can upload anything to the cloud. When this letsencrypt-companion automatically renwes certicicates my added line disappear. Which is the best way to keep changes in proxy config after certificate renewal?

**Comment by buchdag** [comment]
Hi.

This project (`JrCs/docker-letsencrypt-nginx-proxy-companion`) "only" purpose is to:

-  enable the automatic creation of certificates from containers env var.
-  put them in the right place with the right name so they can be used by nginx-proxy docker-gen template.
-  reload the nginx proxy when needed (cert creation or renewal).

What you want to achieve depends entirely on the [`jwilder/nginx-proxy`](https://github.com/jwilder/nginx-proxy) project, which does the actual proxying and is maintained by different peoples.

You shouldn't put anything in `default.conf` as it is auto generated (and overwritten) by `nginx-proxy`. Please check `nginx-proxy`'s doc, more specifically https://github.com/nginx-proxy/nginx-proxy#per-virtual_host

We only deal with issues related to letsencrypt-nginx-proxy-companion, so [please submit your nginx-proxy issues directly to the nginx-proxy repo.](https://github.com/jwilder/nginx-proxy/issues)
