### ISSUE TITLE
How does well-known challenge work with default nginx.tmpl?

### ISSUE THREAD

**Issue by funkypenguin** [JrCs/docker-letsencrypt-nginx-proxy-companion#63]
So I'm trying to migrate from https://github.com/dmp1ce/nginx-proxy-letsencrypt. I've built separate docker-gen and nginx containers. All works well, except the LE client can't validate my hostnames by serving the challenge-response from /usr/share/nginx/html

In the nginx template used in nginx-proxy-letsencrypt (https://github.com/dmp1ce/nginx-proxy-letsencrypt/blob/master/nginx.tmpl), I found the following:

	location /.well-known/ {
		root /usr/share/nginx/html;
		try_files $uri @proxy_pass;
	}

But there's no equivalent config in https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl, as highlighted in your instructions.

As a result (I think), incoming challenges are served with a default http->https redirect to the proxied container, and the validation fails.

Is this expected, or have I missed a step somewhere? :)

Thanks!
D

**Comment by funkypenguin** [comment]
Think I figured it out, submitted pull request:
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/pull/64

D

**Comment by falcon15500** [comment]
This doesn't need to be (and shouldn't be) in the nginx.tmpl as we want it to stay stock.  The companion container provides this functionality via the vhosts.d/default entry. 

M.

**Comment by JrCs** [comment]
Closed. See #64

**Comment by funkypenguin** [comment]
Ah, thanks for the explanation. I'd managed (during the process of fiddling about) to start my 3 containers out-of-order, which meant that the nginx volume mounts didn't work, thus my problem.
