### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by gimler** [JrCs/docker-letsencrypt-nginx-proxy-companion#65]
please make a new release so that we can use a tagged version

thanks for the container

**Comment by JrCs** [comment]
There already a stable and latest tag.
Is not enough ?

**Comment by jboesl** [comment]
I think the point is people want to control which version they are using. Just using latest or stable you never know for sure whether your container changes on restarting.

**Comment by JrCs** [comment]
Ok i see, i will add version tag

**Comment by gimler** [comment]
thx this was exactly the problem
