### ISSUE TITLE
Auto-renewal?

### ISSUE THREAD

**Issue by asmaloney** [JrCs/docker-letsencrypt-nginx-proxy-companion#7]
First off - thanks for releasing this!  I *really* like the simplicity and the fact that it doesn't build on jwilder/nginx-proxy directly.

Other than being mentioned as a feature, I didn't see in your docs information about cert renewal.  Is it automatic or do I need to turn it on somewhere?  When/how does it happen?

**Comment by JrCs** [comment]
Yes it's automatic.
Every hour it will check if a certs need to be renew and if it expires in less than 20 days it will be renew automatically.

**Comment by asmaloney** [comment]
OK -  thanks.  That might be worth adding to the README.
