### ISSUE TITLE
Multi-domain (SAN) certificate and multiple containers?

### ISSUE THREAD

**Issue by jokogr** [JrCs/docker-letsencrypt-nginx-proxy-companion#72]
Hello,

Is it possible to have multiple containers all having the same SAN certificate? Care to make a small example provided that nginx-proxy, -gen and letsencrypt-companion are already all working as intended?

Thanks in advance

**Comment by JrCs** [comment]
I think yes if you have the same LETSENCRYPT_HOST variable. Try yourself.
