### ISSUE TITLE
Posiblity to whitelist and blacklist hosts

### ISSUE THREAD

**Issue by deadcyclo** [JrCs/docker-letsencrypt-nginx-proxy-companion#79]
Would it be possible to implement features for blacklisting and whitelisting hosts? Running multiple instances would be much less nasty with these features.

The reason why I need this is that I'm running two instances of nginx-proxy each listening to a separate IP, and two instances of your container. One of the IPs needs a single certificate, while the other one can handle multiple. The first IP handles webhooks and similar that can't handle SNI. 

The setup works, but It's rather nasty to have all of the "Authorization failed" messages. With a blacklist and whitelist feature I could simply whitelist the single host on the first instance, and blacklist the single host on the second instance, and avoid all issues. 

It shouldn't be to much hassle I think. Two additional environment variables, and a couple of if clauses at line 46 of letsencrypt_service. I would do it myself now, except I'm leaving the country for a while, so won't have time, and would like this feature asap. If you don't get around to it, you will probably get a pull request from me some time this fall ;)

**Comment by JrCs** [comment]
Hi @deadcyclo.
I don't have time too to add new features to this companion.
Look at the https://traefik.io project, perhaps you can do what you want with it.
