### ISSUE TITLE
Upgrade to DOCKER_GEN_VERSION=0.7.3

### ISSUE THREAD

**Issue by pascalandy** [JrCs/docker-letsencrypt-nginx-proxy-companion#82]
Hi sir !

Any plan to upgrade? 
As this issue is now resolve, I want to include letsencrypt in my setup. 

As docker-gen is now using 0.7.3, I feel this project should be updated too.

Cheers!

**Comment by JrCs** [comment]
Done

**Comment by pascalandy** [comment]
cheers!
