### ISSUE TITLE
Error for containers with VIRTUAL_PORT

### ISSUE THREAD

**Issue by auchri** [JrCs/docker-letsencrypt-nginx-proxy-companion#84]
I have a container which listens on port 8080 for incoming HTTP traffic.

To use this container with the [wilder/nginx-proxy](https://github.com/jwilder/nginx-proxy#multiple-ports), I've started it with `-e VIRTUAL_PORT=8080` and it works fine.

But Let's encrypt fails to generate the certificate, because the challenge request is not caught by this container:

![image](https://cloud.githubusercontent.com/assets/5092164/16964501/f541bc1c-4dfb-11e6-9369-a6b7771d3fff.png)

Instead, the response is the html code of the container

**Comment by JrCs** [comment]
It's nginx-proxy that intercept challenge request. So it must never proxy to your container for all the `/.well-known` paths.
Check your nginx.tmpl and your nginx configuration
