### ISSUE TITLE
Adding a compose v2 version

### ISSUE THREAD

**Issue by pascalandy** [JrCs/docker-letsencrypt-nginx-proxy-companion#85]
Would be nice to add a docker-compose v2 file.

Something like this:
https://github.com/fatk/docker-letsencrypt-nginx-proxy-companion-examples/blob/master/docker-compose/v2/simple-site/docker-compose.yml

Cheers!

**Comment by JrCs** [comment]
There already a link in the readme file: https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#examples

**Comment by pascalandy** [comment]
Alright! I was look at yaml files when I cloned the project. 
Cheers!
