### ISSUE TITLE
Support for execution as docker service

### ISSUE THREAD

**Issue by yamalight** [JrCs/docker-letsencrypt-nginx-proxy-companion#89]
Docker 1.12 is out and has a much better swarm now, but also has a different way to start containers - [services](https://docs.docker.com/engine/reference/commandline/service_create/).
Are there any plans to support deploying this companion as a docker service?
Currently, the only thing preventing it from running is usage of `--volumes-from` which is not available there.

**Comment by JrCs** [comment]
Idealy it will be great to add an example in https://github.com/fatk/docker-letsencrypt-nginx-proxy-companion-examples.

**Comment by yamalight** [comment]
@JrCs here's a few snippets, but as I said - the proxy-companion is broken at the moment since it needs `--volumes-from` to be used.

Running the following commands requires docker 1.12 and inited swarm mode.
1) Create overlay network for all services to share:
```
docker network create --driver overlay nginx-network
```

2) Create shared volumes for `html` and `vhost.d` folders:
```
docker volume create --name nginx-vhost
docker volume create --name nginx-html
```

3) Start `jwilder/nginx-proxy` as a service:
```
docker service create \
    --name nginx-proxy \
    --network nginx-network \
    -p 80:80 -p 443:443 \
    --mount type=bind,source=`pwd`/nginx/htpasswd,target=/etc/nginx/htpasswd \
    --mount type=bind,source=`pwd`/nginx/certs,target=/etc/nginx/certs,readonly \
    --mount type=volume,source=nginx-vhost,target=/etc/nginx/vhost.d \
    --mount type=volume,source=nginx-html,target=/usr/share/nginx/html \
    --mount type=bind,source=/var/run/docker.sock,target=/tmp/docker.sock,readonly \
    jwilder/nginx-proxy
```

4) Start `jrcs/letsencrypt-nginx-proxy-companion` as a service:
```
    docker service create \
    --name nginx-letsencrypt \
    --network nginx-network \
    -e NGINX_PROXY_CONTAINER=7604ff51fff5 \
    --mount type=bind,source=`pwd`/nginx/certs,target=/etc/nginx/certs \
    --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock,readonly \
    --mount type=bind,source=`pwd`/nginx/htpasswd,target=/etc/nginx/htpasswd \
    --mount type=volume,source=nginx-vhost,target=/etc/nginx/vhost.d \
    --mount type=volume,source=nginx-html,target=/usr/share/nginx/html \
    jrcs/letsencrypt-nginx-proxy-companion
```

Note env variable `NGINX_PROXY_CONTAINER=7604ff51fff5` - when not providing it, the container will try to search for other containers using `--volumes-from` and fail. If you provide that - it works. But considering nature of docker services and that they can die/be restarted/update/etc, it'd be best to find a different way to get that container ID.
And that's the main problem here.

5) Start nginx as a service:
```
    docker service create \
        --network nginx-network \
        --name nginx-test \
        -e VIRTUAL_HOST=test.dev \
        -e LETSENCRYPT_HOST=test.dev \
        -e LETSENCRYPT_EMAIL=test@test.dev \
        nginx
```

**Comment by JrCs** [comment]
Thanks for the snippets.
But do we really need an orchestrator (swarm in that case) to launch 3 containers that it prefer to be start on the same host ?

**Comment by yamalight** [comment]
@JrCs we have a use case where we have a front-facing web server that needs to be exposed outside (via nginx-proxy/letsencrypt companion), but communicates with a number of microservices that can be scaled using docker. 
After initial evaluation of that approach, I figured that starting all of the containers using services:
1) allows to use swarm for auto-balancing running containers across nodes
2) gives a uniform way to work with them
I might be mistaken, so would love to hear a better/simpler approach if you have one in mind :smile:

**Comment by JrCs** [comment]
Yes a better approach is perhaps to use https://traefik.io

**Comment by yamalight** [comment]
@JrCs that looks exactly like what we need. thank you!
I guess this issue can be closed then.

**Comment by roffe** [comment]
Found this page when looking around for alternativs to Traefik as all test in Swarm Mode has given horrible performance with it :(
