### ISSUE TITLE
Dealing with existing vhost files

### ISSUE THREAD

**Issue by mynameisfiber** [JrCs/docker-letsencrypt-nginx-proxy-companion#9]
So I've noticed that if a particular vhost already has a file in the `vhost.d/` directory, the default template from `nginx-proxy` doesn't pick up the changes made to `default`.  This basically means that those hosts won't have the `/.well-known/` path... any way to deal with this?

**Comment by JrCs** [comment]
If a particular vhost already exists in `vhost.d`it is modified has the default.
Can you double check ?

**Comment by mynameisfiber** [comment]
Ah, yea... it works.  The problem was that I was using a wildcard domain for `VIRTUAL_HOST` and then drilling down to one specific host for `LETSENCRYPT_HOST`. 

Now that I have `VIRTUAL_HOST` contain a list of hosts, `LETSENCRYPT_HOST` has one of those hosts and `vhosts.d/` contains one entry for every `VIRTUAL_HOST` things work just fine.
