### ISSUE TITLE
using the same cert for multiple sub domains

### ISSUE THREAD

**Issue by HendrikRoth** [JrCs/docker-letsencrypt-nginx-proxy-companion#97]
Hello, we are stuck at the rate limits https://letsencrypt.org/docs/rate-limits/

We are just using many sub domains.. Is docker-letsencrypt-nginx-proxy-companion able to create just one multidomain cert for the main domain?

why?

letsencrypt says:
"If you have a lot of subdomains, you may want to combine them into a single certificate, up to a limit of 100 Names per Certificate. Combined with the above limit, that means you can issue certificates containing up to 2,000 unique subdomains per week. A certificate with multiple names is often called a SAN certificate, or sometimes a UCC certificate."

But i have no clue how to configure/do it. Any ideas?

**Comment by JrCs** [comment]
Look the readme espacially https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#multi-domain-san-certificates.
There also an example to create multidomain certificats
