### ISSUE TITLE
Disable force redirect to https

### ISSUE THREAD

**Issue by m2sh** [JrCs/docker-letsencrypt-nginx-proxy-companion#98]
How can i disable force redirect to ssl (https) ?

**Comment by ggramlich** [comment]
This question belongs to https://github.com/jwilder/nginx-proxy
See https://github.com/jwilder/nginx-proxy#how-ssl-support-works
The ENV Variable HTTPS_METHOD controls the behavior.

**Comment by zedtux** [comment]
The link https://github.com/jwilder/nginx-proxy#how-ssl-support-works is dead.

**Comment by buchdag** [comment]
@zedtux https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#ssl-support
